### ISSUE TITLE
LDAP authentication broken

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#1201] opened 2016-04-11 13:01 UTC
# Environment
 
 * Ampache version: Latest Develop Branch b1c7cf9ef680d12a55fbb772541d839713f6fb05
 * Web server + version: IIS 8.5 with PHP 7.0.5 or PHP 5.6.20 (both have the issue)
 * Server operating system: Windows 2012 R2
 * Client operating system: Windows
 * Client type:
   - [x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
```
;#########################################################
; LDAP login info (optional)                             #
;#########################################################

; LDAP server URL (required)
; DEFAULT: none
ldap_url = "ldap://dc1/"
;ldap_url = "ldaps://localhost/"

; LDAP credentials (optional)
; DEFAULT: none
ldap_username = "USER"
ldap_password = "PASSWORD"

; LDAP Base DN for the search (required)
; DEFAULT: none
ldap_search_dn = "OU=Local,OU=Users,OU=Home,DC=home,DC=lan"

; LDAP objectClass (required)
; DEFAULT: none
;ldap_objectclass = "posixAccount"          ; OpenLDAP
ldap_objectclass = "organizationalPerson"  ; Microsoft Active Directory

; LDAP filter for search (required)
; DEFAULT: none
;ldap_filter = "(uid=%v)"                   ; OpenLDAP
ldap_filter = "(sAMAccountName=%v)"        ; Microsoft Active Directory

; Require that the user is in a specific group (optional)
; DEFAULT: none
ldap_require_group = "CN=Ampache Access Group,OU=Groups,OU=Home,DC=home,DC=lan"

; LDAP name field
; DEFAULT = "cn"
ldap_name_field = "cn"
;ldap_name_field = "givenName sn"

; LDAP email field
; DEFAULT = "mail"
ldap_email_field = "mail"

; LDAP protocol version to use
; DEFAULT: 3
;ldap_protocol_version = 3

; LDAP StartTLS
; DEFAULT: false
;ldap_start_tls = "false"

; LDAP member attribute name.
; That's the name of the attribute of the group that will contain
; the usernames.
; DEFAULT: member
;ldap_member_attribute = "member"
;ldap_member_attribute = "memberuid"
```

# Description
Somewhere along the commits my LDAP (Microsoft AD) authentication is broken.

# Logs
```
2016-04-11 14:55:17 [ampache] (session) -> Unable to read session from key kp96hevknlo4m2aec9l4qbtfh4 no data found 
2016-04-11 14:55:17 [ampache] (LDAP) -> search: (&(objectclass=organizationalPerson)(sAMAccountName=Test)) 
2016-04-11 14:55:17 [ampache] (LDAP) -> Error during authentication: `Test` is not member of the group `CN=Ampache Access Group,OU=Groups,OU=Home,DC=home,DC=lan` 
2016-04-11 14:55:17 [ampache] (Login) -> Test From xxx.xxx.xxx.xxx attempted to login and failed 
```
The user is in the AD group that is cheched for;
![image](https://cloud.githubusercontent.com/assets/4103090/14427711/3c4643ac-fff6-11e5-8026-10c90ebee714.png)

The big logs including the trace logging from SQL etc can be found at pastbin: http://pastebin.com/gXP4Ncb6

**Comment by Afterster** [comment] 2016-04-14 07:02
Could be related to latest changes on LDAP implementation yes.
That would be something for @Niols :smile:?

**Comment by Afterster** [comment] 2016-04-14 07:02
Could be related to latest changes on LDAP implementation yes.
That would be something for @Niols :smile:?

**Comment by Niols** [comment] 2016-04-14 11:04
Hello,

Yes, this is probably my fault. I have read my old commit again and I think that I know where the problem comes from.

However, I can't really test against a Microsoft Active Directory. Maybe I can provide you a monkey-patched version of `lib/class/ldap.class.php` (with what I think would be a fix, and lots of debug message), and, if it works correctly, open a PR to solve this.

Sorry for the trouble

**Comment by Rouzax** [comment] 2016-04-14 12:40
Sure, if you can give me the file I can test with it.

**Comment by Niols** [comment] 2016-04-15 10:16
Hi again @Rouzax, sorry I didn't answer earlier, I had some work to do.

I have something that, I believe (well, I hope) will fix your issue.

You can find the `ldap.class.php` file here:
https://github.com/Niols/ampache/blob/fix_1201/lib/class/ldap.class.php

You can also clone the whole `Niols/ampache:fix_1201` branch (it's up-to-date with `ampache/ampache:develop`).

I'm waiting for your comment. If the problem is fixed, I'll suggest a PR

**Comment by Rouzax** [comment] 2016-04-15 12:09
It works :+1: 
```
2016-04-15 14:07:49 [ampache] (session) -> Unable to read session from key 9b5o06v73u8jsj7m6afdapf9l3 no data found 
2016-04-15 14:07:49 [ampache] (LDAP) -> search: (&(objectclass=organizationalPerson)(sAMAccountName=Test)) 
2016-04-15 14:07:49 [Test] (session) -> Session created: fp540lvt0tc2ui0fgmukv3hdi2 
2016-04-15 14:07:49 [Test] (User Ip) -> Login from ip adress: 84.24.126.211 
2016-04-15 14:07:49 [Test] (session) -> fp540lvt0tc2ui0fgmukv3hdi2 has been extended to Fri, 15 Apr 2016 15:07:49 +0200 extension length 3600 
2016-04-15 14:07:49 [Test] (session) -> Session created: 163c1cd03738ad21829833a4fc40c4a5 
2016-04-15 14:07:50 [Test] (session) -> fp540lvt0tc2ui0fgmukv3hdi2 has been extended to Fri, 15 Apr 2016 15:07:50 +0200 extension length 3600 
2016-04-15 14:07:50 [Test] (session) -> fp540lvt0tc2ui0fgmukv3hdi2 has been extended to Fri, 15 Apr 2016 15:07:50 +0200 extension length 3600 
2016-04-15 14:07:50 [Test] (ajax.server.php) -> Called for page: {index} 
2016-04-15 14:07:50 [Test] (session) -> fp540lvt0tc2ui0fgmukv3hdi2 has been extended to Fri, 15 Apr 2016 15:07:50 +0200 extension length 3600 
2016-04-15 14:07:50 [Test] (ajax.server.php) -> Called for page: {stats} 
```

**Comment by Niols** [comment] 2016-04-15 14:08
Nice!
I prepare my PR, suggest it and link this issue, so that we can close it after the merge.

**Comment by Rouzax** [comment] 2016-04-28 09:19
Any idea when the fix will be pushed to the dev branch?

**Comment by Niols** [comment] 2016-04-29 12:00
Hello,

I've done what I could do. We now need @Afterster to merge my pull request #1208.
He's quite busy at the moment, but I believe he will find the time to check it out soon.

If you want to be informed as soon as more information is available, you could *subscribe* to the PR.

Regards,
Niols

**Closed** 2016-05-05 14:55 UTC

**Comment by Niols** [comment] 2016-05-05 22:44
Hey @Rouzax,

The PR has beed merged, the fix is on the `dev` branch now.
I hope it is working, since this is not the exact same file.

Regards,
Niols

**Comment by Rouzax** [comment] 2016-05-06 10:18
:+1: It works
