### ISSUE TITLE
Edge browers with windows 10 anviversary update no play

### ISSUE THREAD

**Issue by raxip1** [ampache/ampache#1372] opened 2016-08-27 18:47 UTC
running the lastest ampache 3.8.2

windows 10 machine with edge and the latest anniversary update 1607 and now ampache will not play anything.

edge on my other windows 10 machine prior and the web player and everything functions fine.

Thanks

**Comment by Phyks** [comment] 2016-08-27 19:14
Has anyone else access to a machine with windows 10 anniversary update and edge? I only have Linuxes here… =(

**Comment by Gano16** [comment] 2016-08-27 19:22
Everything works just fine with me (Ampache develop branch and Edge with Windows 10 anniversary update).

**Comment by Phyks** [comment] 2016-08-27 19:24
Closing as the issue cannot be reproduced in latest develop branch. Could you try to check out this branch and confirm it is actually solved?

Feel free to reopen with extra infos if this is not the case.

@Afterster Maybe we should release a 3.8.3 version soon, we are having a big diff between 3.8.2 and develop branch, and many issues that are actually solved in develop branch.

**Comment by raxip1** [comment] 2016-08-27 22:30
well

here is the version info thats working and not

do you have the same?

[image1.JPG]

[image2.JPG]
[image3.JPG]

On Aug 27, 2016, at 1:24 PM, Lucas Verney <notifications@github.com<mailto:notifications@github.com>> wrote:


Closing as the issue cannot be reproduced in latest develop branch. Could you try to check out this branch and confirm it is actually solved?

Feel free to reopen with extra infos if this is not the case.

@Afterster<https://github.com/Afterster> Maybe we should release a 3.8.3 version soon, we are having a big diff between 3.8.2 and develop branch, and many issues that are actually solved in develop branch.

-

**Comment by Phyks** [comment] 2016-08-27 22:33
@raxip1 Hmm, there was an error with the attached images apparently.

**Comment by raxip1** [comment] 2016-08-27 22:37
well here it is typed out...

1607 anniversary update and cu august 23rd

Microsoft edge 38.14393.00
Microsoft edge html 14.14393
cant play anything and links unresponsive but can log in and bang around menus.. tried web player and all other options

before 1607 anniversary update and august 23 CU
Microsoft edge 25.10586.00
Microsoft edge html 13.10586
works fine

**Comment by Phyks** [comment] 2016-08-28 12:52
Looks like the same version as the one used by @Gano16 from what I know. This is weird…

**Comment by Gano16** [comment] 2016-08-28 13:48
Indeed:
![capture d ecran 2](https://cloud.githubusercontent.com/assets/20047972/18034195/c4e8080a-6d36-11e6-93b2-36e0c7cad06b.png)

**Comment by raxip1** [comment] 2016-08-28 15:10
i wonder if its because its a touch screen surface.

anyway thanks , not sure why its not working, tried to make sure it wasn't anything else , still no luck

will have to load chrome or firefox i guess



On Aug 28, 2016, at 6:52 AM, Lucas Verney <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #1372<https://github.com/ampache/ampache/issues/1372>.

-

**Comment by raxip1** [comment] 2016-08-28 17:34
well

looks like it might be cortana plugin or a security setting... working now....thanks guys and sorry to bug you.

love this app... too bad none of the mobile ios apps seem to work for it..might have to switch to android

please close ticket


On Aug 28, 2016, at 6:52 AM, Lucas Verney <notifications@github.com<mailto:notifications@github.com>> wrote:


Reopened #1372<https://github.com/ampache/ampache/issues/1372>.

-

**Comment by Phyks** [comment] 2016-08-28 22:08
Thanks for the feedback on the issue resolution!

**Closed by Phyks** 2016-08-28 22:08 UTC
Labels: isolated, support
