### ISSUE TITLE
c-pchart has a licensing clause that makes it potentially non-open source

### ISSUE THREAD

**Issue by bowlofeggs** [ampache/ampache#1515] opened 2017-03-29 23:14 UTC
Hello!

I've been working on [packaging](https://fedoraproject.org/wiki/Ampache) Ampache for the [Fedora project](https://getfedora.org/) for some time. Fedora has a peer review process for adding packages to the distribution, and during [package review](https://bugzilla.redhat.com/show_bug.cgi?id=1425275) one of my peers noticed an odd clause in the readme file for c-pchart that mentioned that c-pchart can only be used under the GPL [if it is not being used in a commercial project](https://github.com/szymach/c-pchart/blob/2.0.4/README.md#license). This raised a red flag and so we consulted Fedora's legal list to ask whether this would be a problem:

https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/4MDAWLRSVR3QIIYFJLVKMEELS5OPBIMI/

The legal list ruled that c-pchart was not suitable for Fedora due to the remarks about making money and commercial use, as the GPL doesn't make any such restrictions, and adding restrictions like that does mean the software isn't truly Free Software. One of the comments was from [Richard Fontana](https://en.wikipedia.org/wiki/Richard_Fontana), a notable authority on the GPL.

I've spent the last couple of weeks trying to contact the author of the upstream to c-pchart to ask him to clarify his [licensing statements](http://www.pchart.net/license), but have been unable to get in touch. I sent him an e-mail and a message on Linked In, but he has not responded after about 2.5 weeks. I then contacted the c-pchart author about this issue to ask if he knew how to get in touch, but unfortunately he did not:

https://github.com/szymach/c-pchart/issues/35

Note that you can see the e-mail I sent to the upstream pchart author in that issue, that explains the issue a bit more than I've done here.

I would like to request that the Ampache project consider taking some action to remedy this situation, as I will not be able to add Ampache in its current form to Fedora. Here are some options I can think of:

1. Ampache could also attempt to contact the pchart author to ask for license clarification. It might help to get some more voices.
2. Ampache could attempt to replace c-pchart with a different library.
3. Ampache could make c-pchart optional through configuration, and Fedora could simply configure a boolean to be False. This assumes c-pchart isn't crucial to Ampache's core functionality.
4. Also depending on how crucial c-pchart is, Fedora could carry a patched version of Ampache that removes functionality that depends on c-pchart, and distribute the rest of Ampache.

What do you think? Please let me know if you can think of other options.

**Comment by wagnered** [comment] 2017-06-16 02:41
@bowlofeggs,

You could investigate packaging for rpmfusion at [https://rpmfusion.org/](https://rpmfusion.org/). They provide non-free packages for Fedora.

**Comment by bowlofeggs** [comment] 2017-06-16 17:37
On Thu, 2017-06-15 at 19:41 -0700, Ernest Wagner wrote:
> You could investigate packaging for rpmfusion at https://rpmfusion.or
> g/. They provide non-free packages for Fedora.

Indeed!

I finally got in touch with the pchart author and made my case to him
to reword his licensing page, but I have not heard back from him yet.

I've been meaning to investigate how important c-pchart is to Ampache.
If it's only used for minor features, I may be able to package Ampache
with patches to remove those features with everything else working as
expected. That might not be so bad. If it's used heavily that's
probably not an option, and perhaps rpmfusion is the most appropriate
place for it.

Thanks for the suggestion!

**Comment by bowlofeggs** [comment] 2017-11-26 16:48
I spent some time messing with my Ampache installation this morning and I was able to get it to run without c-pchart. In fact, I was unable to find anything in the web ui that makes graphs in the first place (perhaps it is a plugin I don't have enabled), so I am not even able to find functionality that I use that is lost.

Thus, I think I can proceed with packaging Ampache for Fedora with the caveat that I will have to patch out its code that uses c-pchart.

**Comment by wagnered** [comment] 2017-11-26 17:15
You are correct, the graphs are enabled with this config switch in ampache.cfg.php:
`;statistical_graphs = "false"

When this is enabled and set to true, the graphs will be displayed when "Statistics" is selected in the UI.

I don't know  if removing this switch from the config file would be acceptable to the Fedora peer review: I think it is acceptable according to Ampache's "GNU Affero General Public License, version 3 (AGPLv3)".

I will be looking into another charting package in the Laravel based version of Ampache.

**Comment by wagnered** [comment] 2017-11-26 22:22
I was just looking into various packages.  You have a better
understanding of the various licenses, so I wanted to ask. I found a
package called jpGraph with a free version containing QPL 1.0 (Qt Free
License) <http://www.opensource.org/licenses/qtpl.php> for
"non-commercial, open-source or educational us" and a professional
version with more functions.  Would there be any conflicts in using the
free package that Fedora might object to?


73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by bowlofeggs** [comment] 2017-11-27 04:17
Hello @wagnered!

The QPL is an [acceptable license for Fedora](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Software_License_List), but the language about "non-commercial" might be concerning for the same reason that c-pchart is. It does say "*or* open source use", but the term "open source use" isn't clear to me. It also sounds like it is implying that a commercial entity cannot use the QPL since it says their other license is for commercial use. Can a commercial entity use it for "open source use"?

I am not a lawyer, so I [wrote the Fedora legal list to ask their opinion on it](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/ORNU3ZGSEPCPBELR667SOAWUUPYNWLLM/).

In general, I don't think it is a problem for libraries to dual license like this, but it is tricky when they use unclear wording. It would be better if they left words like "commercial" out of it and simply said that it was licensed QPL and that there is another version of it under a non-free license as well (i.e., not specifying any conditions on how it is used in either case, other than the license itself).

**Comment by bowlofeggs** [comment] 2017-11-27 22:04
I got a reply from the Fedora legal list that the restriction on commercial use makes the jpGraph license effectively non-free software, and thus it cannot be included in Fedora. You can read the reply on the thread here:

https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/ORNU3ZGSEPCPBELR667SOAWUUPYNWLLM/

**Comment by wagnered** [comment] 2017-11-27 22:52
Thanks for the heads up.

So far, the only package that I can find without any limitations is chart.js [www.chartjs.org](http://www.chartjs.org/) . it is appears to be totally open source and MIT licensed.  The problem is that I'm not very strong in JS and hope I can find a php wrapper for it.

**Comment by a7medo778** [comment] 2017-11-27 23:10
hey guys, i think it might be better to just wait out the laravel release, there are many charts packages that works out of the box for laravel like
https://github.com/ConsoleTVs/Charts

**Comment by wagnered** [comment] 2017-11-27 23:27
@a7medo778 

Thanks for the info. 

>hey guys, i think it might be better to just wait out the laravel release,

That's primarily what I was doing: research on licenses to be used in the Ampache/Laravel project, just in case.  In the mean time, if I could have found a "drop in" package for c-pchart... but it doesn't look like that's going to happen.

**Comment by bowlofeggs** [comment] 2017-11-28 18:48
chart.js does seem to be Free Software. Unfortunately I also am not a JS guru (I'm actually secretly just a Python/C++ dev, so I also don't really know PHP) so I can't aid much there.

https://github.com/ConsoleTVs/Charts also seems to be Free Software under MIT.

**Comment by lachlan-00** [comment] 2019-05-24 04:31
I know this is a few years late but here's some current info

There is an ampache.cfg.php option that must be set. By default this is false.
statistical_graphs = "false"

The only place these graphs are used is on the stats page.
![image](https://user-images.githubusercontent.com/1305249/58302715-ea3deb80-7e2f-11e9-966f-fadecc372ea4.png)

and as an action in object pages (album, song podcast podcast_episode, video)
![image](https://user-images.githubusercontent.com/1305249/58302785-3e48d000-7e30-11e9-9db0-4e334ac74948.png)

Over all it's actually a pretty useless feature when you could use analytics instead. I'm thinking this will get dropped from the next version.

**Comment by lachlan-00** [comment] 2019-05-30 00:29
Closing, p-chart has been removed in the core branch in my fork and will be merged into the official core branch today.

If someone wants to restore charts they can do it using a fee software library but it's not a feature that is important to the music.

The only things left using the graph class are the stream* plugins. This class is only used for calculating the limits now and not generating charts.

**Comment by lachlan-00** [comment] 2019-11-18 23:00
I've put it back into the current source for develop. I've also asked the debian maintainers the same questions.

3. Ampache could make c-pchart optional through configuration, and Fedora could simply configure a boolean to be False. This assumes c-pchart isn't crucial to Ampache's core functionality.

The config option to enable this feature is set using 'statistical_graph' in the config file. Fedora could remove that line from the source config in a patch or just leave it as is depending on the level of need.

4. Also depending on how crucial c-pchart is, Fedora could carry a patched version of Ampache that 
removes functionality that depends on c-pchart, and distribute the rest of Ampache.

This is pretty simple to do as well. Remove from composer.json, remove statistical_graph from the config file and then patch it out of the graph.class.

**Comment by lachlan-00** [comment] 2019-11-19 00:06
I've moved this library out of the default composer.json now so it can be dropped in fedora. i'll also put in file checks to stop any issues with it missing from the default install and will test that tonight.
https://github.com/ampache/ampache/wiki/chart-faq

**Comment by lachlan-00** [comment] 2020-02-10 11:52
again we've changed path while looking at #2278 
I've removed the nonfree composer files and instead have just documented that the user must install that component manually to use the graph feature.

This is a much cleaner way to do it.

**Closed by lachlan-00** 2020-02-10 11:52 UTC
Labels: UI
