### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by nakinigit** [ampache/ampache#1537] opened 2017-05-16 23:50 UTC
Just curious.

**Comment by a7medo778** [comment] 2017-05-17 00:07
As i understood there is a change in leadership that happened just 2 weeks ago

The project in general is due for some updates in terms of library updates, subsonic catchup and fixes
But personaly i cant complain since i am not a developer and i havnt been contributing, that being said i really do hope the project catch up in popularity with the prev devs to push it ahead, now even projects like madsonic are getting way ahaead

**Comment by vollmerk** [comment] 2017-05-19 17:15
I'll likely never have time to give this project what it deserves so I'm looking for someone to take the reins, I have enough free time to keep it's head above water but that's likely it.

**Comment by wagnered** [comment] 2017-05-19 23:59
@vollmerk and @Afterster,

I am considering "taking the reigns".
I have been working with Ampache for the last 3 years, Mostly with the video section.

I have taken the liberty of checking out the Laravel branch out of curiosity. I have gained a more than moderate understanding of Laravel. and have attempted to follow up on Afterster's work: fixing typos, and implementing Admin=>User Tools.

Granted, I don't have a whole picture of Ampache-3.83-develop, primarily because of it's disorganisation and lack of documentation, but Laravel's Architecture Concepts lead to an understandable organization of the project.

Last but not least, I am retired, so I will have time for development of Laravel Ampache.

I am a bit reserved about jumping right in because I don't know what I don't know, such as managing the github project and other oversight tasks.

Regards,

Ernie

**Comment by nakinigit** [comment] 2017-05-21 00:26
Well, I have seen a lot of progress since about mid 2013, when @Afterster & @Psy-Virus got involved. If you think documentation is scant now, you should have seen it back then!

Anyway, hate to see the project die, seems just as it was coming into it's prime. For Android, anyway, I'm seeing a slight uptick in the number of apps that utilize the Ampache api.

I wish I could offer more other than testing & pointing out issues, but I hope the right candidate ( @wagnered?)  comes along to breath new life into this project.

**Comment by Psy-Virus** [comment] 2017-05-21 00:56
Well, I'm still here and will further handle the translation stuff and maybe further work it out to a more automated system. But to be honest, I didn't have the motivation yet. Maybe if the project comes to new life I'll have it again. :-)

To take over the project I wouldn't be the right one. I'm still freshly in PHP and have still a lot to learn, what I also do as a hobby and not professional. But I will support everyone who takes the helm.

:-)

**Comment by a7medo778** [comment] 2017-05-21 01:05
Guys as a user who is worthless when it comes to dev, i suggest to go the freemium way
Maybe the plugins and the api section to be enabled with a small monthly fee that goes to the dev team

I know its never about the money, but anything to keep the project alive

Regards
Ahmed

**Comment by Psy-Virus** [comment] 2017-05-21 01:20
I don't think it's possible. If I see it right, the user base is not big enough for something like this. I already tried to spread it and wrote to some software portals to write about Ampache but they mostly didn't react or didn't have any interest in it...

**Comment by gryphonmyers** [comment] 2017-05-21 17:06
IMO, users of ampache are too savvy to sap money out of them with a monthly fee, unless monetization was reserved for highly non-essential features. Personally, I specifically avoid Subsonic / Madsonic because of their aggressive monetization model. I think it's wildly inappropriate to demand a monthly fee for a self-hosted product. Ampache is not a service, it's code. Yes, it takes time (money) to develop and maintain code, but there is no real overhead associated with user acquisition. 

The problem is Ampache and similar products are targeting a niche within a niche market: web developers who care SO MUCH about managing their own music libraries that their willing to configure and maintain a web server to do it. I happen to fall within that category, but I think we're a pretty rare breed - most people are content with Spotify, apparently. Those who aren't can use Google Play Music, leaving pretty much only the most anal retentive power users to Ampache. 

I would love to see this project thrive because it is far from perfect, but I'm not very surprised by the relative lack of activity here.

**Comment by lachlan-00** [comment] 2017-05-28 23:09
Are there links to where all this is going on? I only use github for ampache so i wasn't aware of anything happening!!

If people are dropping out it's probably time to work on a 3.8.3 release as it's been a while since a stable release. Then work out how to move on from there.

I use ampache every day and would never want this to die. when you compare to subsonic/et al ampache is pretty much the only choice for free software users.

**Comment by Phyks** [comment] 2017-05-29 00:14
> Are there links to where all this is going on? I only use github for ampache so i wasn't aware of anything happening!!

I guess the [mailing list](https://groups.google.com/forum/#!forum/ampache) is where most of the infos pass.


> If people are dropping out it's probably time to work on a 3.8.3 release as it's been a while since a stable release. Then work out how to move on from there.

That is something that has been discussed a few times lately, as far as I know. Problem is that `develop` branch still has a quite large number of blocking bugs to tag a new stable release. I think the plan, about a year ago was to fix these bugs, tag a new stable release and then completely drop the actual architecture for something cleaner, more flexible and more modern. Problem was (and still is I think), Ampache really lacks "pro" developers with quite a lot of free time :/

**Comment by a7medo778** [comment] 2017-05-29 00:16
Well the issues are piling up, unless the project gains traction with devs, its dead i am afraid :(
Most libraries are already outdated

Regards
Ahmed

**Comment by gryphonmyers** [comment] 2017-05-29 07:20
> then completely drop the actual architecture for something cleaner, more flexible and more modern

@Phyks Have any decisions been made as to what technologies a "more modern" ampache might utilize? I would be interested to get involved in a rebuild, though I fall into that category of devs who don't have much free time :(

**Comment by Phyks** [comment] 2017-05-29 13:17
The idea was too build something on top of Laravel/Lumen (there is a dedicated branch on the repo, but quite empty I fear) and expose some clean standardized API and eventually build the front on top. There is an attempt of a new frontend using React and Ampache API here : https://github.com/Phyks/ampache_react.

It features basic stuff to browse the library and play music and is already working. 

Last year, Koel (https://github.com/phanan/koel) gained some exposure. It is basically what the new Ampache should be, except that it lacks a lot of features from Ampache, and has no public API. Not sure also about the number of developers involved and the stability over time. 
-- 
Phyks

**Comment by vollmerk** [comment] 2017-05-29 13:26
I don't want to see it die, but I also do not have personal time to devote to it... keep looking for alternatives, and whoever is willing to pick it up get in touch and I'll get you write access.

**Comment by Phyks** [comment] 2017-05-31 00:43
Sure, same for me :/ Ampache is so featurefull, it would be a pity to see it disappears.

My impression as a former (sadly, I no longer have enough spare time at the moment for Ampache :/) contributor is that Ampache codebase is quite huge and legacy. There was a discussion some time ago about splitting most of Ampache features in dedicated plugins, and maintaining them separately. My opinion on this is that for instance most of catalogs and localplay code can really easily be split in a separate repo as plugins (it is actually almost handled this way already https://github.com/ampache/ampache/tree/develop/modules/localplay), which would largely reduce the size of the codebase and ease maintainance (as their could be dedicated maintainers for each feature more easily than in the current case).

Still, a major refactoring might not happen soon :/ I was wondering at some point if Ampache should not take profit of the gain Koel exposure to backport most of the features as Koel plugins, as Koel is alraedy stable and has basic features and uses the stack that was planned for the refactor. Problems are Koel does not yet have a plugin mechanism and it is mainly the work of [a single contributor](https://github.com/phanan/koel/graphs/contributors), so there might be same issues as with Ampache concerning long term maintainance. :/

**Comment by lachlan-00** [comment] 2017-06-01 00:02
If the quality of the replacement options is anything to go by it's not looking great.

Koel has 7 times the stars that ampache has but i can't even scan my music library successfully. It also took well over 12 hours to do the initial library scan!

If ampache_react is basically working would we be able to separate ampache into a core and UI? The core of ampache is very solid and has the features that others are missing.

There are a lot of commandline options available so it could be possible to manage a server from cli in some way.

**Comment by a7medo778** [comment] 2017-06-01 00:30
I think a mobile friendly UI as a start will attract many new users and perhaps dev's in the mix
I do love the idea of using the plugins to separate the core functions, but again we need to have something rolling first.

I am looking at madsonic as a replacment but reluctant since its a single guy closed sourced project, non the less hes doing some awesome job 
http://beta.madsonic.org/pages/changelog.jsp
The libraries upgrades alone says something

Regards
Ahmed

**Comment by Phyks** [comment] 2017-06-01 02:16
> Koel has 7 times the stars that ampache has but i can't even scan my music library successfully. It also took well over 12 hours to do the initial library scan!

Thanks for the feedback, I was aware of such issues at the beginning of Koel but was thinking it had been solved in the meantime. I could never tried it extensively yet, just looked at it and heard about it and thought it could be a good starting point.

I was very busy lately, but hopefuly I should have some time to put back my (large) music library online at some point. It will be the occasion to deeper test Koel and see how it goes and if anything is possible to backport Ampache features, or try to find people motivated to refactor Ampache together. :)


> If ampache_react is basically working would we be able to separate ampache into a core and UI? The core of ampache is very solid and has the features that others are missing.

It should be working for basic stuff, although I could not touch it for some time now. You can try it [from the Github hosted demo](https://phyks.github.io/ampache_react/public/#/login?_k=c0x6ft) provided you have a working Ampache instance somewhere. Have a look also at the [opened issues](https://github.com/Phyks/ampache_react/issues) to have an idea of possible bugs.


> If ampache_react is basically working would we be able to separate ampache into a core and UI? The core of ampache is very solid and has the features that others are missing.
> There are a lot of commandline options available so it could be possible to manage a server from cli in some way.

We could, but `ampache_react` (really bad name actually :/) does not yet cover all Ampache features. That mean that the server will have more features than the client exposes. For this reason, a split is not viable in my opinion. But one may use this alternative UI (which is still very much beta, I should emphasize).


> I think a mobile friendly UI as a start will attract many new users and perhaps dev's in the mix I do love the idea of using the plugins to separate the core functions, but again we need to have something rolling first.

:+1:
Another idea might be to have a look at "modern" UIs for music, and adapt it to Ampache. Typically, `Koel` UI can be used provided that we implement its API in Ampache, or that we adapt the [webapp](https://github.com/phanan/koel/tree/master/resources/assets/js/services) to use Ampache API, and we can also find [some alternatives UIs](https://github.com/Zhangdroid/Gokotta).


> I am looking at madsonic as a replacment but reluctant since its a single guy closed sourced project, non the less hes doing some awesome job

I don't think `madsonic` can be considered as a replacement, especially since it is closed source.

**Comment by gryphonmyers** [comment] 2017-06-01 02:18
So I'm not the only one! I installed koel and cannot successfully scan any
of my music.

I have also considered writing a new front end for ampache as a way of
significantly improving the product without having to touch the backend, so
picking up the ampache react work may be a good path forward. The reality
is that there are no good desktop clients for ampache or subsonic. They're
all feature incomplete, usually ugly abandonware. And the current ampache
frontend is pretty hideous

**Comment by lachlan-00** [comment] 2017-06-01 06:29
I think i'll start looking at ampache_react then; Koel wasn't good enough for a large library.

I agree that all the desktop/client apps aren't paid enough attention although power ampache on android is quite nice and even though the server is proprietary now the subsonic app on android is really solid.

I guess by focusing on an electron/html5 style app you can use them as desktop clients as well?

**Comment by gryphonmyers** [comment] 2017-06-01 13:52
Does anyone know if any thought was put into designing a new client? The
existing ampache interface is very... Organic. I might suggest wholesale
ripping off an existing interface like koel did. I personally like Google
play music's interface and have thought if I ever got around to making a
web client I'd model it after that, material design and all.

**Comment by vollmerk** [comment] 2017-06-01 13:54
So whoever wants to take some-what of the reigns e-mail me at karl.vollmer@gmail.com, I can help to a limited about, I just don't really have the time to code/answer questions etc etc

**Comment by Phyks** [comment] 2017-06-01 15:53
> The reality is that there are no good desktop clients for ampache or subsonic.

Yes, this was the idea in rewriting Ampache UI on top of the API and using "modern" web technologies such as React / Vue.JS etc. You can easily have some web app, go responsive for the model (and even package it into a real app with React Native / Cordova and so on), and eventually get a desktop app using Electron (although Electron is super heavy :/).

Basically the UI discussion was located [here](https://github.com/ampache/ampache/issues/359) and Ampache_react was an attempt at writing some PoC for a new UI. I should emphasize that it is still really beta, and was one of my first code using React, so I am not 100% satisfied about the way stuff is done (typically, store etc are not optimal, and I might go with Vue now if I was to start it again).

@gryphonmyers see supra and linked issues.

**Comment by lachlan-00** [comment] 2017-06-02 04:51
I really like the whole drop in aspect of ampache_react although i see what you mean about how basic it is. But at least for me this is the way to go so i'm going to pull the source and start learning about it.

I could live with a simplified php-based server package that is used to configure ampache and a UI/player like react to focus on the actual playing.

**Comment by Afterster** [comment] 2017-06-15 05:00
Hi Guys. First, thanks for the motivation :smile:.

In my opinion, new UI, business model (I don't like it, Ampache is not a business), architecture and clients shouldn't be the discussion here. There is already dedicated topics for it, and it can be done on branches. Here we are more looking for a maintainer who would maintains and improve the current codebase, keeping Ampache goals in mind.
There could be two maintainers, one on current codebase, another on Laravel branch if someone want to continue the work.

@wagnered, I will add you to the team just as @Phyks is already. Please focus on making a release before making any major changes.

**Comment by wagnered** [comment] 2017-06-15 17:56
@Afterster,

Thanks. I'll start working on the 3.8.3 release. I don't think that I
will be making any major changes to the current development code. Over
the last several months, I've  been working with and continuing the
Laravel framework version with the coding you started.   I'll look
into implementing new features into the new framework as it is much more
efficient.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by wagnered** [comment] 2017-06-23 04:21
Version 3.8.3 has been released.
@Afterster I would like to pin a notice in the Ampache Google forum.  Could I have elevated privileges to add a notice to that group

**Comment by wagnered** [comment] 2018-11-24 18:12
I published a pre-release (preview) of Ampache/Laravel with very limited functionality.  There are only  source files.  So composer needs to be installed and run in Ampache's root folder.

I reopened this issue because using this issue is the only way I could find a way to keep track of comments and keep them isolated from issues on the develop branch.  

I'm sure there will be problems and questions,  So If you find that you need to open a new issue about Ampache/Laravel, please label it with the **Laravel** label and possibly with a **Discussion** label also. Otherwise it will probably be ignored.

Click [Ampache/Laravel](https://github.com/ampache/ampache/releases/tag/4.0.0) to go to the release.

**Comment by wagnered** [comment] 2018-11-29 00:37
OH yea, I changed the tag name and forgot to change the link above.  I just edited the previous comment: It now points to the actual release page.  I did that because someone iis allowing autoupdates and noticed the pre-release version was being displayed.  The pre-release is not suitable for updating.  I modifed the current release to ignore the pre-release and changed the tag name to have something to check against.

You really need to go to the [wiki](https://github.com/ampache/ampache/wiki/Ampache-Laravel-Next-Generation-Preview) for installation instructions.  it is quite different from earlier versions.

**Comment by stebe** [comment] 2018-12-04 14:00
I have the Laravel version installed. What areas are ready for testing. For example, the admin server config options page has no save button. I get an E_Error when I click on server config interface. 

It seems I'm unable to label new issues, so I can always reference this issue instead.

**Comment by stebe** [comment] 2018-12-05 12:15
I've been playing with the 4.0 version for a couple of days now. I'm very impressed with how fast the interface is compared to the 3.9 version. The layout is very familiar so finding options and menu items is quick and easy. Considering this is an alpha or pre-alpha release I've got to compliment @wagnered on the work he has done by himself to get to this point.

**Comment by a7medo778** [comment] 2019-02-01 05:48
question is still valid, @wagnered still around?

**Comment by Psy-Virus** [comment] 2019-02-11 22:41
@vollmerk, @Afterster 

Did you hear from @wagnered ?

**Comment by a7medo778** [comment] 2019-02-19 21:02
@vollmerk, @Afterster, @wagnered ?

**Comment by Afterster** [comment] 2019-02-21 08:30
Looks like @wagnered is away for two months now. He may have other priorities, lets hope it is temporary.
He did a great job on the Laravel version, it would be sad to stop all of this now ^^.

**Comment by Psy-Virus** [comment] 2019-02-21 15:52
> [...] lets hope it is temporary.

Yepp

It would be nice to give me some rights. so I can at least keep the translations up to date. Or would you be so kind and merge them?

**Comment by lachlan-00** [comment] 2019-02-21 22:32
Dec/Jan are big months for everyone so it's not out of the ordinary. Personal lives are more important.

I'm trying to look into v4 code and get abreast of things but I just don't know enough about laravel/js to be that helpful compared to php. (not that i know a lot about php either.)

**Comment by lachlan-00** [comment] 2019-03-07 01:37
If Ampache is abandoned by wagner (which would be terrible as wagner has done a lot of good work picking it up after everyone else. :) ) there probably needs to be talk on what to do instead.

I don't know anything about laravel but i would like to keep the legacy ampache alive with a focus on audio only as a secondary function of an api/database for playback in other sources.

it seems like ampache itself is such a large thing for what really amounts to one person that it needs to cut down to survive.

Features i would remove -> what your alternative is
video -> jellyfin
channels -> icecast2
podcasts -> thousands of options
localplay -> ???

I use/used these features but they aren't actually that important to the function of ampache to be viable.

features that i don't understand well but do need changes
 * html5 player needs an overhaul
 * composer packaging seems to be falling out of date
 * A lot of the current bugs are probably beyond my understanding at this stage

For me, the biggest feature ampache has is being used as a single point of truth for all my other playback sources. Playback in the website is just a bonus really as i can use dsub/android apps and then sync my playback from rhythmbox automatically.

So what i'm really saying is does this seem reasonable? I'm only partially understanding of ampache code as i primarily code in python so i'm not a great dev but i would really not like to let ampache die. i'm pretty sure i've been using this software for a decade now and i would rather work on a fork than let it die.

**Comment by lachlan-00** [comment] 2019-03-15 00:03
I've started working on this last night.
https://github.com/lachlan-00/amuzak

I'm using a copy of my current database and will work on testing a base installation once I've finished cutting down the features.

- Videos are gone, Podcasts and channels are next.
- I'll start looking at the current pull requests after that.

If Wagner or anyone else pick Ampache up again I'll be really happy but for now i'll maintain this fork as an ampache-legacy option.

**Comment by a7medo778** [comment] 2019-03-16 22:19
> If Ampache is abandoned by wagner (which would be terrible as wagner has done a lot of good work picking it up after everyone else. :) ) there probably needs to be talk on what to do instead.
> 
> I don't know anything about laravel but i would like to keep the legacy ampache alive with a focus on audio only as a secondary function of an api/database for playback in other sources.
> 
> it seems like ampache itself is such a large thing for what really amounts to one person that it needs to cut down to survive.
> 
> Features i would remove -> what your alternative is
> video -> jellyfin
> channels -> icecast2
> podcasts -> thousands of options
> localplay -> ???
> 
> I use/used these features but they aren't actually that important to the function of ampache to be viable.
> 
> features that i don't understand well but do need changes
> 
> * html5 player needs an overhaul
> * composer packaging seems to be falling out of date
> * A lot of the current bugs are probably beyond my understanding at this stage
> 
> For me, the biggest feature ampache has is being used as a single point of truth for all my other playback sources. Playback in the website is just a bonus really as i can use dsub/android apps and then sync my playback from rhythmbox automatically.
> 
> So what i'm really saying is does this seem reasonable? I'm only partially understanding of ampache code as i primarily code in python so i'm not a great dev but i would really not like to let ampache die. i'm pretty sure i've been using this software for a decade now and i would rather work on a fork than let it die.

would be awesome if you can add the artist youtube channel as a profile section, but in general i agree, ampache core should be all about music

**Comment by Psy-Virus** [comment] 2019-03-17 13:44
> I would not jump into a fork so fast, this project survived decades it should stand a little bit longer :).

True. @lachlan-00, If you have any fixes or improvements, that you think, need to be merged, you can still add Pull Requests. The community can still decide if the changes are okay or not.
Github is meant to be a platform for collaboration between every kind of person with their specific skills and ideas. I'm not a pro dev either but I try to fix things that bug me and create my PRs after I tested my changes and think they're stable enough to be merged.

For example: a few years ago, I discovered Ampache and was fascinated by the functions but no one was actively developing it anymore and the UI was gross XD. Then I found Ampache-Doped, forked by Afterster and SUTJael, that added more functionality and a completely overhauled UI.
I installed it and everything was working. **But** the German translation was horrible. So I started digging into it, completely rewrote it and took over the Translation part of Ampache. I also provided several fixes and improvements, not only for translations.

I think: The problem with those projects is simply that they start as a hobby and transform into work after a while. That makes it hard to keep up the motivation to work on it without getting paid or get any kind of reward or compensation, except thankfulness ( Don't misunderstand me. Thankfulness is a big thing! Stay thankful people! :P ), for all the time you have spend.
**Especially** when you're working as the lone leader and only see the issue count growing. :D
And of course there's this weird thing called _real life_ :P

_Just some thoughts I wanted to share after reading the discussion here._

> @Psy-Virus you have now write permissions so you can continue to do what you are doing great since so long. Thanks.

Thank you @Afterster!

**Comment by lachlan-00** [comment] 2019-03-18 01:50
I'm also using this opportunity to learn more about how the code works which has been really helpful whatever happens. I'm still also only one person and would rather keep ampache as is because it's been so important to me.

I agree that the drain is a big issue on an individual and can be really hard to manage. If i can simplify ampache to a point that makes sense i would rather make a pull here here and see where other people wanted to take it.

**Comment by lachlan-00** [comment] 2019-03-18 06:50
@Psy-Virus you are 100% correct in how we should be looking at this. I'll stay out of this discussion now and focus on making practical pulls, and stripping out a core system for myself.

I've made a pull and I think it's a good first step without being too drastic.
https://github.com/ampache/ampache/pull/1856

**Comment by lachlan-00** [comment] 2019-05-03 22:44
It's not dead it's resting ;)

**Comment by nearwood** [comment] 2019-05-07 18:52
@lachlan-00 wrote:
> html5 player needs an overhaul

I agree. I use Ampache a lot and on mobile I prefer the web player over any apps*. I have some experience with HTML5 Audio and I would love to see a responsive player.

I'll take a look at the web player code and see whether it's something I can do.

*I have developed and Android App that is basically the Google Audio Player example hooked up to Ampache, with an Android Auto interface, but it does not work well with large collections :( so I have not released it.

**Comment by lachlan-00** [comment] 2019-05-07 21:26
@nearwood is your app using the API? There are a few changes coming in the api/xml that should help with the large collection. I think a large problem with API apps is we haven't really given decent documentation or support to people who have made that effort.

Right now I think dsub is the best Ampache android app so it would be good to make API clients first class citizens.

We should work on the issues you have as well. If it's based on an example Google app it could make a good example app to include as a repo here.

There is also power Ampache by @antoniotari which I think would really benefit from better API code and support.

https://github.com/antoniotari/reactive-ampache

I'll be merging my core repo soon as I finish up a few more things and test the changes.

While I'm still merging changes from my original fork I don't recommend using it unless you want to look at current code.

https://github.com/lachlan-00/ampache/tree/core

My weakest area is in JS/Java/android so having another pair of eyes on the webplayer will really help.

**Comment by lachlan-00** [comment] 2019-06-20 05:35
Hi everyone,
I've just pushed my core branch into develop! This is the culmination of about 3 months work when you include my initial fork and the modernization project is essentially complete (https://github.com/ampache/ampache/projects/2)

I've really enjoyed being able to push ahead with this and I hope we can keep the momentum going.

**Comment by stebe** [comment] 2019-06-20 12:00
I just pulled the latest develop and so far nothing has broken. Great work @lachlan-00 for keeping the project alive and adding updating features.

**Comment by lachlan-00** [comment] 2019-06-20 12:59
I just about had a heart attack while doing it!

There are still lots of things to do like documentation and bugfixing but I don't have any more dramatic changes planned. 

I can't wait to have a drink this weekend to celebrate and take a break but I'm looking forward to the future.

**Comment by muellerj** [comment] 2019-06-21 06:41
Awesome! I upgraded yesterday and all went smoothly. Thanks for much for your effort.

**Comment by a7medo778** [comment] 2019-06-21 12:11
hey @lachlan-00 
so i am currently on 3.9.0, i just noticed that the upgrade download url from inside ampache leads to a dead URL
https://github.com/ampache/ampache/releases/download/4.0.0-pre-release/ampache-4.0.0-pre-release_all.zip

and that the new release is actually the long-awaited laravel branch, so question is, can I upgrade?
or does it have to be a fresh install?

**Comment by kuzi-moto** [comment] 2019-06-21 16:01
The Master branch, which is considered stable has yet to be updated. Develop has been updated to 4.0.0, but contains mostly bug fixes and such, which is separate from the V4 Laravel pre-release.

There hasn't been any development on Laravel, so focus has come back to normal Ampache. When Develop branch is considered ready for release, then Master will be updated and a new release... Well, released...

**Comment by a7medo778** [comment] 2019-06-21 18:36
@kuzi-moto oh ok, was a bit confusing since if you go to the releases page the last available one is "Ampache/Laravel"

ok if i may ask, how can upgrade from the stable to develop ?

**Comment by kuzi-moto** [comment] 2019-06-25 20:55
@a7medo778 I'm guessing you have already seen it, but Ampache will notify you on the home screen that there is a new update available. If it doesn't show up, you should be able to check for the latest version on the debug page.

**Comment by a7medo778** [comment] 2019-06-25 22:48
@kuzi-moto yeah i am seeing the version number, just waiting for the new build to test it :D

**Comment by lachlan-00** [comment] 2019-09-26 03:51
Hi everyone,
The last two pieces of the puzzle are almost done before the modernization project is completed

* Now that I've updated the api, I need to fully document 400001 in the code and on the wiki.
* Once #1957 has merged we will need to update translations to match these changes.

I'm really looking forward to getting this into master. The amount of bugfixes and code quality improvements is massive and Ampache has really started to shine again!

**Comment by kuzi-moto** [comment] 2019-09-26 04:59
Nice work @lachlan-00! I think there are a lot of great changes for Ampache that hopefully gets more like interested in the project again.

Ampache really is a special piece of software. I have done research on other audio streaming servers and apps, and there is no competitor to Ampache's features and functionality. Especially for free.

Of course there is still plenty of work to be done, and things are far from perfect. But I'm excited in the progress made so far and the direction things are going.

Your dedication and work has definitely inspired me to contribute, and I hope that will be true for others. I just hope you don't burn out and lose interest too quickly, with all the work you've been doing!

**Comment by lachlan-00** [comment] 2019-11-08 10:13
hi everyone.
I just want to say that i've completed all of my goals blocking the next release and the modernization project is finished!

The next release of Ampache is feature complete! (seriously!)

@Psy-Virus can we do another translation sync this weekend?
@kuzi-moto can you make those changes to your pull so they can go in?
@wagnered it's time i asked you how to release correctly without screwing up people on stable,
@vollmerk thank you for putting some faith in me to keep things going!

I know that we haven't done all the things that are needed but the current version of develop is in my mind, much better than stable and fixes a lot of issues people have had (including those security advisories that have been hanging over my head all year) without introducing new bugs

Now that the biggest challenges have been sorted we can start working on shorter release periods.

**Comment by kuzi-moto** [comment] 2019-11-08 12:29
Yep! I'll get that sorted out today. Can't wait to release!

**Comment by wagnered** [comment] 2019-11-08 20:59
I would like to suggest as part of the release procedure, a set of unit tests be developed that would be excersized to verify Ampache's features and functionality.  It could be based on server side JavaScript using node.js.  or an "owner" level permission in the web client allowing access to functionality testing and modification of certain parameters.

"Feature complete"?  Any new features not included in v3.9.0? Is the latest develop version backward compatable with earlier releases? If you haven't done so already, may I suggest that you read [semantic versioning](https://semver.org) or other reference to versioning.

As to releasing here's what I did:
1. Merge/squash develop branch with master.
2. Create a zip package named "ampache-*.*.*_all.zip and add the entire ampache directory tree.  From zhe zip file, I then removed all files that are used for installation/development and are not necessary for ampache to function.  I then unpacked the zip into a separate path, created a server pointing to that path and tested basic functionality. This might be where unit testing would be helpful.
3. When drafting a new release, set target to master branch. When publishing, github will add a reference to the two compressed packages (zip and tar.gz) which will need to be installed.
4. The "ampache-*.*.*_all.zip" drop-in package is then uploaded.
5. After setting version and title, it should be ready to publish.

If I forgot anything or any questions, let me know.

Because the Laravel branch appears to be at a dead end, I attempted to delete the 4.0.0 and 5.0.0 pre-releases but couldn't do it from my old android. They also conflict with your current versioning pattern.  Please remove them for me.  Thanks...

-------- Original message --------
Subject: Re: [ampache/ampache] Project still alive? (#1537)

**Comment by lachlan-00** [comment] 2019-11-09 01:45
Thanks @wagnered I think those are all important things to complete before a release can happen.

Any new features not included in v3.9.0?
Lots of new options and features compared to 3.9.0. I'll actually need to do a big write up on all of these changes and features.

Is the latest develop version backward compatable with earlier releases?
It is to a degree but there are a lot of things that are done differently that may break depending on the previous install. The biggest things off the top of my head are API handshakes are required, config settings like mail_enable and changes to password resets. So a few things are different enough to break.

It might be a good to write up a release.md in docs to document the release procedures too.

I'll keep the old branches in my fork and document things in a history page.

Unit testing! Yes, this should probably be part of a codestyle shell script to test each class. That would help a lot as things still break when they are done correctly.

**Comment by wagnered** [comment] 2019-11-09 04:28
Sorry, I couldn't edit the comment from my phone, but the questions were meant to be rhetorical to encourage you to give thought to your versioning considerations.  I labelled  the Laravel branch version 4 because @afterster declared a stop to processing PRs for new features and accepted only bug fixes.  In my opinion, if you made an existing feature more robust which I think is the case, that would be a revision(2nd digit).  Bug fixes would be a patch(3rd digit). If this is the case, then according to semantic versioning, the next release should be 3.10.0.  If after developing the new API,  features in a previous version stop working then the version (1st digit) should be incremented.

Way back when Digital Equipment Corporation was IBM'S primary competition(early 90's), I was an engineering tech for their printer group.  I worked very closely with both the hardware and software engineers so I have experience with the development process and the process flow.

Also, I noticed that the readme.md indicated that php 5.6 is the minimum version. Questions:(rhetorical)  Is this true?  What about with 7.33.11, the current version? On my Fedora system, I could very easily switch php versions and run basic tests for each php version.  5.6 is no longer supported and https://www.php.net/eol.php has the eol dates and pointers to guides for upgrading versions.

I'm excited about the "new and improved" upcoming Ampache.

-------- Original message --------
Subject: Re: [ampache/ampache] Project still alive? (#1537)

**Comment by lachlan-00** [comment] 2019-11-09 06:18
It is true but i haven't had a 5.6 box in a few years now. I think focus on supported versions of php is super important. 7.1 doesn't have much life left but i think i'll have a look around on which 7 versions are supported by various distros.

I say v4 but i haven't actually thought a lot about the versioning beyond the initial drive. Although dropping php 5.6 is actually a big jump from previous history as well.

**Comment by lachlan-00** [comment] 2019-11-09 06:42
i can see there might be some aged dependency issues from composer so will need to test more.

**Comment by lachlan-00** [comment] 2019-11-22 10:39
Hi all! Short of one more wiki doc i am going to release Ampache 4.0.0 this weekend!

I really want to thank @vollmerk for the chance to do this. it's taken me 7 months but we've finally gotten to the end of the tunnel.

I also want to heap extra thanks to @wagnered for being there to merge my first pull request almost 2 years ago today. /pull/1647 and still being here 2 years later to guide us to the next Ampache release! I can't thank you enough for that.

Thanks to all those who have contributed along the way. I'm really proud of what we've managed to do.

**Comment by lachlan-00** [comment] 2019-11-24 11:41
https://github.com/ampache/ampache/releases/tag/4.0.0

**Comment by stebe** [comment] 2019-11-24 12:56
Thank you @lachlan-00 for keeping the project moving forward with the new features, updates and bug fixes. Ampache is still the best music database and client that I've used.

**Comment by lachlan-00** [comment] 2019-11-24 23:40
Thanks @stebe you've picked up on quite a few bugs that i would have missed otherwise.

It also seems like we have between 6-12 fairly active people on the repo now which has been really exciting to see. I'm so glad that other people feel the same way about this project.

Expect releases to pick up steam again with a lot more minor and patch versions instead of gigantic releases that require 2 weeks of testing!

**Comment by AshotN** [comment] 2020-09-23 09:45
Going through old issues to try to clean up issue tracker.

I enjoyed reading this thread. Funny @Phyks had the same idea for a React UI decoupled from the core. 

Glad Ampache is alive.

**Closed by AshotN** 2020-09-23 09:45 UTC
Labels: Laravel, discussion
