### ISSUE TITLE
[Feature Request] Support for previous/next media keys

### ISSUE THREAD

**Issue by PsyZeus** [ampache/ampache#2812] opened 2021-03-07 11:06 UTC
Hello!

It would be so nice to have the previous/next media keys working.
Everything else is working fine e.g. mute, volume up/down, play/pause.

I know the hotkeys previous=[ next=] exists already but i guess it would be more useful to have working media keys since you can use them from anywhere and not only when in ampache tab.

**Comment by mitchray** [comment] 2023-01-09 22:21
Duplicate of #2424

**Closed by mitchray** 2023-01-09 22:21 UTC
