### ISSUE TITLE
Catalog update: multiple catalogs get updated when update of only one is requested

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#1244] opened 2016-06-09 06:20 UTC
# Environment
 
 * Ampache version: 3.2.8
 * Web server + version: Apache 2.4.18
 * Server operating system: Fedora 23

 # Description
I noticed a strange behavior when updating my catalogs.
I have multiple catalogs to divide up my collection, eg. "0-9", "A", "B"... etc.
And then I have one called "OST" for soundtracks only.
I update my catalogs from the shell using this command:
`php /var/www/htdocs/ampache/bin/catalog_update.inc T -c -v -a -g`
Every time I do this the updater not only updates the "T" catalog but the "OST" one as well.
The same thing happens when I update the "O" and the "S" catalogs respectively.
It seems quite clear whats happening here but I don't know why and how I could prevent that.
Any ideas?

Thanks
Arno

**Comment by Phyks** [comment] 2016-06-09 09:26
This is due to [this line](https://github.com/ampache/ampache/blob/develop/bin/catalog_update.inc#L77) which creates a MySQL where clause such as `WHERE name LIKE "%T%"` in your particular case, the `%` character matching anything (that is update anything which contains `T` in its name).

I can push a PR to fix it, basically dropping the `%` characters, but this may break things. Then, I'd like to wait for @Afterster advice on it. Other solution would be to add a `-e` flag which would stand for exact match and would remove the `%` characters.

In the meantime, feel free to drop the `%` on this line on your local installation, and it should solve the issue.

**Comment by arno1979** [comment] 2016-06-09 09:28
Great! Thanks for the quick reply, I'll try your solution.

**Comment by arno1979** [comment] 2016-06-10 06:33
I tried your suggestion replacing line 77 of catalog_update.inc with
`$where .= "name = '" . Dba::escape(preg_replace("/[^a-z0-9\. -]/i", "", $_SERVER['argv'][$x])) . "'";`
As you can see I also replaced the "LIKE" with an "=" so the update process is only executed with an exact match of the catalog name. I'm not sure a LIKE without the % would even work? Haven't tried it.
The update now works as I would expect it.
Thanks again!

**Comment by Phyks** [comment] 2016-06-13 10:27
Sure, a `LIKE` statement without the `%` joker does nothing much than a `WHERE` clause, AFAIK, and should be dropped by a `WHERE` statement (even it should work without the percent character I think).

Cool it fixed your issue. I think it might be worth it doing a fix for this, but I am not sure about the expected behaviour here, and it may break things. I think we should wait for @Afterster advice on it and then see for a fix.

**Comment by Afterster** [comment] 2016-06-14 05:16
This is old stuff and is not coming from my decision. I will tend to also prefer the exact name match.
I made the change, thanks for the issue/discussion.

**Closed by Afterster** 2016-06-14 05:16 UTC
