### ISSUE TITLE
Album art rescanned on every catalog 'add'

### ISSUE THREAD

**Issue by dengste** [ampache/ampache#1721] opened 2018-05-11 23:34 UTC
# Environment

 * Ampache version: current develop (ea5f14808b38e109610f54)
 * Web server + version: apache 2.4.25
 * Server operating system: Debian 9
 * Client operating system: Debian 9

# Settings

[ampache.cfg.php.gz](https://github.com/ampache/ampache/files/1997076/ampache.cfg.php.gz)

# Description

Lots of cover art is rescanned when I do an 'Add' for the catalog. I use 'beets' for retrieving cover art, which puts a file 'cover.jpg' into each folder. Ampache finds the file and it is also displayed fine in the web interface, but it seems it is not registered in the database somehow, since I see lots of "Image less than 5 chars, not inserting".

# Logs

Example for one album:

2018-05-12 01:21:49 [admin] (gather_art) -> Gathering art for album/1999... 
2018-05-12 01:21:49 [admin] (Art) -> Searching using:["db","tags","folder"] 
2018-05-12 01:21:49 [admin] (Art) -> Method used: gather_db 
2018-05-12 01:21:49 [admin] (Art) -> results:{"db":true} 
2018-05-12 01:21:49 [admin] (Art) -> Method used: gather_tags 
2018-05-12 01:21:49 [admin] (Art) -> results: 
2018-05-12 01:21:49 [admin] (Art) -> Method used: gather_folder 
2018-05-12 01:21:49 [admin] (folder_art) -> Opening /foo/bar and checking for Album Art 
2018-05-12 01:21:49 [admin] (folder_art) -> Found preferred image file: cover.jpg 
2018-05-12 01:21:49 [admin] (folder_art) -> Results: {"c4fbbb7d2aed8e945b75763893b1233c":{"file":"\/foo\/bar\/cover.jpg","mime":"image\/jpeg","title":"Folder"}} 
2018-05-12 01:21:49 [admin] (Art) -> results: 
2018-05-12 01:21:49 [admin] (gather_art) -> Image less than 5 chars, not inserting 

As I've written above: those 'cover.jpg' are perfectly fine jpegs and also displayed by Ampache when I call up that album.

**Comment by wagnered** [comment] 2018-05-12 01:07
@dengste 

What is the actual size of the jpg files in question?

What version of PHP?

What is your system architecture: 32 bit or 64 bit?

> Lots of cover art is rescanned when I do an 'Add'...

Just in case, I can't replicate, could you attach a file that isn't imported into the  db?

I'll try to replicate your issue and take a look at it.

**Comment by dengste** [comment] 2018-05-12 07:38
Size of the jpegs varies between 15k and 2M, but this issue affects pretty much all of them. Here's one example:

![cover](https://user-images.githubusercontent.com/1818708/39954921-e19a20b6-55c7-11e8-8795-b655a28c9808.jpg)

PHP version is 7.0.27 on a 64bit system.

I've also tried to switch to  album_art_store_disk='true' with a separate metadata directory, but his does not help.

**Comment by wagnered** [comment] 2018-05-13 21:51
@dengste 
Just to double check,  I removed "tags" from `art_order` and just left "db,folder". I then created a catalog on my main music directory of 22000+ files.  Not once was the entry "Image less than 5 chars, not inserting" found in the log.

Sorry...

**Comment by dengste** [comment] 2018-05-15 19:26
The image indeed does get inserted into the DB. The message "Image less than 5 chars" comes from the fact that the following result is returned by Art::gather:

     results:{"db":true,"0":{"file":"\/var\/www\/music\/David Bowie\/Lodger (1979)\/cover.jpg","mime":"image\/jpeg","title":"Folder"}}

Since you iterate over this in catalog.class.php via

         foreach ($results as $result) {

the first $result will simply be 'true', which leads to the error message that this image has less than 5 chars.

So the question remains why I get a complete art rescan on catalog 'add'. It seems to me this only happens when I do 'add' when there are actually no new files added in the system. I'll try to debug this further.

**Comment by wagnered** [comment] 2018-05-16 00:16
OK, sI just discovered that if the image table is empty, the error doesn't show up.  If an update or gather art is later done, the error does show up in the log.

> the first $result will simply be 'true', which leads to the error message that this image has less than 5 chars.

If $result = true, then it's already in the database and Ampache doesn't need to create a new image to store.  So the error message shows up if the image exists in the database or if the image is actually less than 5 char.  

This is by design, although the message is deceptive. I'll make a change to remove the confusion and push the changes to the develop branch.

Thanks for bringing it to my attention.

**Comment by lachlan-00** [comment] 2019-09-25 06:17
art is now checked in the DB before scanning/inserting so this shouldn't happen now.

**Closed by lachlan-00** 2019-09-25 06:17 UTC
