### ISSUE TITLE
Playing large smart playlists takes way too long (30 minutes)

### ISSUE THREAD

**Issue by LoveIsGrief** [ampache/ampache#3121] opened 2021-12-15 18:33 UTC
## Description

I have a music library of >20k items and make extensive use of smart playlists. After migrating from Quodlibet and syncing my ratings, about 10k songs are rated and I have a smart playlist with unrated songs as well as the existing "Song X* (System)" playlists.

### Describe the bug

Why trying to play any of the above playlists, it either never plays or starts playing minutes, sometimes tens of minutes later.

### To reproduce

1. Go to 'Smart playlists'
2. Click on 'Play' on "Song 5* (System)" playlist
![afbeelding](https://user-images.githubusercontent.com/2829538/146240067-0d9d7391-3711-4f26-b999-9a2e07396e22.png)

3. Wait...

### Expected behavior

The playlist should start playing within a second or two.

## Environment

* Ampache version: develop or 5.1.1
* Web server + version:
* Server operating system: docker
* Client operating system: OpenSuse 15.2 with Firefox 91.2.0esr

### Client type

* Web

## Settings

I didn't modify the settings manually.

Here's a diff of `ampache.cfg.php` (left) and `ampache.cfg.php.dist` (right)

```diff
53c53
< web_path = ""
---
> ;web_path = ""
73c73
< database_hostname = "localhost"
---
> database_hostname = localhost
77c77
< database_port = ""
---
> ;database_port = 3306
81c81
< database_name = "ampache"
---
> database_name = ampache
85c85
< database_username = "admin"
---
> database_username = username
91c91
< ;database_password = "REMOVED"
---
> database_password = password
116c116
< ;secret_key = "REMOVED"
---
> secret_key = "abcdefghijklmnoprqstuvwyz0123456"
121c121
< session_length = "3600"
---
> session_length = 3600
127c127
< stream_length = "7200"
---
> stream_length = 7200
134c134
< remember_length = "604800"
---
> remember_length = 604800
139c139
< session_name = "ampache"
---
> session_name = ampache
144c144
< session_cookielife = "0"
---
> session_cookielife = 0
149c149
< session_cookiesecure = "0"
---
> session_cookiesecure = 0
257c257
< additional_genre_delimiters = "[/]{2}|[/\|,;]"
---
> additional_genre_delimiters = "[/]{2}|[/\\\\|,;]"
505c505
< licensing = "false"
---
> ;licensing = "true"
707c707
< wanted = "false"
---
> ;wanted = "true"
734c734
< channel = "false"
---
> ;channel = "true"
821c821
< debug = "true"
---
> ;debug = "true"
833c833
< debug_level = "5"
---
> debug_level = 5
857c857
< site_charset = "UTF-8"
---
> site_charset = UTF-8
990c990
< allow_public_registration = "false"
---
> ;allow_public_registration = "true"
1029c1029
< cookie_disclaimer = "false"
---
> ;cookie_disclaimer = "true"
1098c1098
< transcode_mp3 = "allowed"
---
> transcode_mp3  = "allowed"
1344d1343
< 
```

And the entire config for completeness
[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/7721828/ampache.cfg.php.txt)

## Logs

The logs are 141 lines long, so I'll add the here as an upload ([ampache.log.txt](https://github.com/ampache/ampache/files/7721891/ampache.log.txt)) , but they show that from the call to `play_item` at `2021-12-15T17:48:16+00:00` and the actual `save_mediaplay` at `2021-12-15T18:18:57+00:00` it took **30 minutes** to play a playlist of 5734 songs.

**Comment by mitchray** [comment] 2021-12-17 02:49
Try setting a maximum limit on results, even a limit of 500 should be more than enough

**Comment by LoveIsGrief** [comment] 2021-12-17 10:33
Which setting is that?

**Comment by LoveIsGrief** [comment] 2021-12-17 11:54
Well I set it to max 500 items and it takes 1.15m to start playing the playlist and 5.8s for 50 items :slightly_frowning_face:

**Comment by lusum** [comment] 2021-12-17 15:41
The slow row should be 

```php
for ($urls as $url) {
  Dba::write( 'INSERT INTO `stream_playlist` ...);
}
```

Looking at a posssible solution it should be possible to insert multiple lines at one time ( at least 50, 500  or more ) using the sintax explained in this link: [MySQL Insert Multiple Rows](https://www.mysqltutorial.org/mysql-insert-multiple-rows/)

something like this:

```sql
INSERT INTO table_name (column_list)
VALUES
	(value_list_1),
	(value_list_2),
	...
	(value_list_n);
```

**Comment by mitchray** [comment] 2021-12-17 22:30
> Well I set it to max 500 items and it takes 1.15m to start playing the playlist and 5.8s for 50 items 🙁

I see, something strange is happening then as mine only takes 5 seconds for 500 items

**Comment by lusum** [comment] 2022-04-26 20:41
Duplicate of #2626

**Closed** 2022-04-27 11:42 UTC
