### ISSUE TITLE
catalog not adding songs

### ISSUE THREAD

**Issue by oliver-cfc** [ampache/ampache#2602] opened 2020-11-01 15:02 UTC
## Description
First time user in a docker container so it's possible (perhaps likely) I'm just not understanding something

### Describe the bug
I added my first catalog, pointed it to my directory and it sees the songs but doesn't add them

### To reproduce
catalog name: rock64
catalog type: local
filename pattern: %T_%t
folder pattern: %a/%A
gather art: check
build playlist: uncheck
catalog media type: music
path: /music

Taking one of the failed tracks as an example, I see this in the ampache log
```
2020-11-01T14:49:41+00:00 [admin] (local.catalog) -> Reading The Clash inside /music
2020-11-01T14:49:41+00:00 [admin] (local.catalog) -> Memory usage: 4 MB
2020-11-01T14:49:41+00:00 [admin] (vainfo.class) -> Checking /(.+?)\/(.+?)\/([0-9]+?)_(.+?)\..+$/ _ Array on The Clash/Stay Free Live in NYC 1979/01_safe_europ
2020-11-01T14:49:41+00:00 [admin] (vainfo.class) -> /(.+?)\/(.+?)\/([0-9]+?)_(.+?)\..+$/ matched The Clash/Stay Free Live in NYC 1979/01_safe_european_home_(li
2020-11-01T14:49:41+00:00 [admin] (vainfo.class) -> Cleaning id3v1
2020-11-01T14:49:41+00:00 [admin] (vainfo.class) -> Cleaning id3v2
2020-11-01T14:49:41+00:00 [admin] (dba.class) -> Error_query SQL: INSERT INTO `artist` (`name`, `prefix`, `mbid`) VALUES(?, ?, ?)
2020-11-01T14:49:41+00:00 [admin] (dba.class) -> Error_query MSG: ["22007",1366,"Incorrect string value: '\\xFF\\xFET\\x00h\\x00...' for column `ampache`.`arti
2020-11-01T14:49:41+00:00 [admin] (dba.class) -> Error_query MSG: ["23000",1048,"Column 'album' cannot be null"]
```

I don't know if it's normal that the log seems to have a max column length but the song itself is at:
 /music/The Clash/Stay Free Live in NYC 1979/01_safe_european_home_(live).mp3

id3 from the host box says
```
$ eyeD3 The\ Clash/Stay\ Free\ Live\ in\ NYC\ 1979/01_safe_european_home_\(live\).mp3
/opt/data/music/The Clash/Stay Free Live in NYC 1979/01_safe_european_home_(live).mp3                                                              [ 7.59 MB ]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 03:16     MPEG1, Layer III        [ 320 kb/s @ 44100 Hz - Joint stereo ]
---------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.3:
title: Safe European Home (live)
artist: The Clash
album: Stay Free Live in NYC 1979
album artist: The Clash
recording date: 2020-10-20
track: 1
disc: 1
```

## Environment
* Ampache version: 4.2.3-all
* Apache2 2.4.6
* PHP 7.3.24
* Server operating system: Alpine3
* Docker container

Any ideas where I've gone wrong?

**Comment by kuzi-moto** [comment] 2020-11-01 18:24
This seems super weird. Do you know if any songs are added successfully?

**Comment by wagnered** [comment] 2020-11-01 19:26
Hello @oliver-cfc 

Could you email me a copy of one of the offending mp3's?  I would like to determine if the problem is with the getID3 library, or Ampache. 

To get my email address, click on my icon above. It is on my info age.

Thanks...

**Comment by oliver-cfc** [comment] 2020-11-01 23:33
> This seems super weird. Do you know if any songs are added successfully?

No songs are added.  There are two artists, each with one album and 25 songs in total in /music within the docker container.

**Comment by oliver-cfc** [comment] 2020-11-01 23:39
> Could you email me a copy of one of the offending mp3's? I would like to determine if the problem is with the getID3 library, or Ampache.
Just sent it.  Thanks

**Comment by wagnered** [comment] 2020-11-02 00:07
At first glance it's as I suspected. UTF-16.  I'm guessing that these files were ragged on a older Windows system.

Now to look a little closer and find out why these files aren't being properly decided.

**Comment by wagnered** [comment] 2020-11-02 00:22
I think I was  "Asleep at the wheel.". There is nothing wrong with the files or Ampache.  

I think your php  is missing the mbstring extension.  When you installed Ampache, did it give you any kind of warning about mbstring or any other php extensions being missing?  if not, what version Ampache are you running?

Check your installation again and make sure you have installed the latest version.

**Comment by oliver-cfc** [comment] 2020-11-02 01:16
> I think I was "Asleep at the wheel.". There is nothing wrong with the files or Ampache.
> 
> I think your php is missing the mbstring extension. When you installed Ampache, did it give you any kind of warning about mbstring or any other php extensions being missing? if not, what version Ampache are you running?
> 
> Check your installation again and make sure you have installed the latest version.

Everything was green on the installation screens.  I just deleted everything and tried again and took screenshots.  [In this img gallery](https://postimg.cc/gallery/qn3hqvN) are 6 pics.  The first two are the php extensions.  The next two are the DB stuff (I'm setting up a user and password from scripts run when docker builds the image.  The 5th is the version and the 6th is from the picard options (the tagger I usually use) which defaults to UTF-16.
One of the php extensions is for mbstring.func_overload but returns OK even without mbstring installed.

In saying that, I didn't have php7-mbstring in my Dockerfile and it's not dragged in by any other dependency. 

So I added php7-mbstring to the Dockerfile, rebuilt the image and that has indeed fixed the issue.  Thanks!

**Comment by lachlan-00** [comment] 2020-11-02 03:37
is this part of the tag write merge? should i add mbstring into composer?

**Comment by wagnered** [comment] 2020-11-02 04:09
> is this part of the tag write merge? 

No.

> should i add mbstring into composer?

Yes.  I thought the initial install test checked for mbstring, but I guess not.

I think those files were tagged on an older version  of Windows.  UTF-16 was the standard encoding.

**Comment by oliver-cfc** [comment] 2020-11-02 15:10
Since my issue is resolved, do you want me to close this or leave it open to track addition of mbstring into composer?

**Comment by wagnered** [comment] 2020-11-02 15:18
If you are sure it's resolved it can be closed.  It can be reopened at a later time if you discover that new conditions result in the same issue.

I'll close it for you.

**Closed by wagnered** 2020-11-02 15:18 UTC
