### ISSUE TITLE
"clean" job not cleaning up deleted files from library

### ISSUE THREAD

**Issue by Deathcow** [ampache/ampache#3562] opened 2023-07-23 08:05 UTC
### Describe the bug
When using the webui or the cli, the clean job for a catalogue doesn't clean up the files from the database.

Running the cli with the -f flag, ampache correctly identifies all the missing files. -c just never seems to actually clean them.

### To reproduce

1. delete some files
2. run "bin/cli run:updateCatalog -c"
3. wait for finish
4. songs & album still show up, but can't be played

### Expected behavior
Entries should be removed from db

## Environment

* Ampache version: 6.0.0-preview2
* Web server + version: nginx 1.25.1, php 8.1
* Server operating system: Gentoo
* Client operating system: Gentoo

### Client type

* Web
* Ampache

**Comment by troycarpenter** [comment] 2023-08-01 14:56
This is a duplicate of #3554

**Comment by lachlan-00** [comment] 2023-08-02 06:57
set with 73e892d9e should be fine now

**Comment by mitchray** [comment] 2024-09-07 05:48
Seems to be fixed

**Closed by mitchray** 2024-09-07 05:48 UTC
