### ISSUE TITLE
Uploading sound file throws [object%20HTMLInputElement]  404 Not Found

### ISSUE THREAD

**Issue by ThomZenTury** [ampache/ampache#2690] opened 2021-01-11 13:06 UTC
Hello to all,

 I am new to the group and really appreciate the efforts that go itno this project.

### Describe the bug
I hope someone can help me with a problem I have when trying to upload a sound file (.mp3, .wav) to the desired catalog. Dropping file as well as browsing to the file via explorer was tested.
Chrome and Firefox throw me this error 
POST http://..../ampache/[object%20HTMLInputElement]  404 Not Found
The log file does not show any information at all about the upload.

### Expected behavior
Former experience tell me that the file upload section should not show the file name in red letters after choosing or dropping the file. The file is not uploaded to the catalog. Console error told me maybe there is something wrong with apache config .htaccess or similar.

#2442  Environment
I installed ampache under following conditions
-  Ubuntu20 server Virtual Machine running on Windows10 pro
-  apache2
-  Installed Ampache version: e6905a19ac575c5e0cb64fd5fa1cd7d0003eadeb
- installed php 7.4.3
- all prerequisites and recommendations "OK" when installing ampache
- max_upload_size 300MB, files in question way smaller than that (<5MB)

### Client type
* Web

## Settings
As of the ampache wiki / help I double checked:
-  catalog directory is not on a mounted drive 
-  open basedir is not set in php
-  read/write permissions of the catalog directory are set as needed
-  access to the catalog dir is given in apache2.cfg file
-  I tried both a directory on the root directory of the ampache installation and on root of the system, no luck

## Logs
Log does not throw error and does noteven  mention the upload process.

Any ideas what else  I could do about this issue?

Greetings
Thomas

**Comment by lachlan-00** [comment] 2021-01-12 02:42
it's possible that your php isn't allowed to upload to that directory, especially if it's not making any log info.

this is what i get when an upload fails (```tail -f /var/log/apache2/error.log```)
```
[Tue Jan 12 12:34:18.121048 2021] [proxy_fcgi:error] [pid 830460:tid 140337014761216] [client 192.168.1.9:56578] AH01071: Got error 'PHP message: PHP Warning:  error_log(): open_basedir restriction in effect.
File(/var/log/ampache/ampache-music.log) is not within the allowed path(s): (/mnt/files-music/upload/user/) in /var/www/music/lib/log.lib.php on line 54
PHP message: PHP Warning:  error_log(/var/log/ampache/ampache-music.log): failed to open stream: Operation not permitted in /var/www/music/lib/log.lib.php on line 54
PHP message: PHP Warning:  error_log(): open_basedir restriction in effect. File(/var/log/ampache/ampache-music.log) is not within the allowed path(s): (/mnt/files-music/upload/user/) in /var/www/music/lib/log.lib.php on line 54
PHP message: PHP Warning:  error_log(/var/log/ampache/ampache-music.log): failed to open stream: Operation not permitted in /var/www/music/lib/log.lib.php on line 54', referer: https://music.com.au/index.php
```

This is because the folder is outside the path the webserver is allowed to open. do you get something in your php error log?

**Comment by lachlan-00** [comment] 2021-01-26 22:18
it must be a setting in php 7.4 as all my servers on 7.4 can't upload either.

like in source changes i'll take out that base_dir restriction and see what's going on.

**Comment by ThomZenTury** [comment] 2021-01-27 17:40
Thanks a lot for still looking into that.
I had no luck whatever I tried.
Looking forward to any news!

**Comment by usox** [comment] 2021-01-28 22:07
Hi @ThomZenTury 

This should/could be fixed in the current develop-branch with commit a3bc15dd0aa8c6e9e4ce8fef19efb4aa0fc266ff

**Comment by ThomZenTury** [comment] 2021-02-03 08:17
And suddenly... working!
Thank you very much!

I know this does not belong here, but are there any examples for "post-upload scripts" somewhere? Or even a better, a place to ask for it?
All I want to do is letting ampache write new sub-/directories to the catalog according to the artist's name and album.

Again, thank you very much for the efforts!

**Comment by lachlan-00** [comment] 2021-02-03 09:09
you want to use this option to move/rename files
![image](https://user-images.githubusercontent.com/1305249/106723801-3906d580-6653-11eb-93bd-d2702e29d977.png)

which will rename according to your pattern
![image](https://user-images.githubusercontent.com/1305249/106723854-46bc5b00-6653-11eb-9c58-a5be322fbfdb.png)

**Comment by ThomZenTury** [comment] 2021-02-03 13:31
Ugh, one line further! Silly me!
Thank you for saving time!

It uploads and creates directories fine when created from file tags - which is totally fine in my case - but it throws 500 error (ampache/upload.php) when manually typing in "New Artist" / "NewAlbum".

Have a nice day!

**Comment by usox** [comment] 2021-02-03 13:49
@ThomZenTury Confirmed. Looks like there are two wrong conditions causing this error.
I think, I fixed it just now with 24bee3919df17ff1e3acc4382992663a9a053d2d

**Comment by ThomZenTury** [comment] 2021-02-03 14:58
I can not test version 5.0.0 at the moment but will in a few weeks.
Thanks!

**Comment by usox** [comment] 2021-02-03 15:09
Maybe @lachlan-00 backports this to 4.x - we'll see.

**Comment by lachlan-00** [comment] 2021-02-03 20:12
Working on 4.3.0 this week so it will be tested today

**Comment by lachlan-00** [comment] 2021-02-03 21:30
1a985b1bb for 4.3.0 and df9d52f23 for develop

i'm trying to complete 4.3.0 this week so we can move onto bigger things but it's shaping up to be a good release with all these fixes coming in.

**Closed by lachlan-00** 2021-02-03 21:30 UTC
Labels: bug
