### ISSUE TITLE
Composer package robloach/component-installer abandoned

### ISSUE THREAD

**Issue by SimonHova** [ampache/ampache#2500] opened 2020-08-12 14:34 UTC
This had come up in issue #2122 but it looks like it was forgotten about. I get an error when running composer, 

`Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead.`

**Comment by wagnered** [comment] 2020-08-12 15:14
hello @SimonHova 

Those messages are just **warnings**. They are caused by some required packages not being updated.  It concerns me to a degree because it implies that some required packages have been abandoned.  As long as Ampache's needs don't change, there should be no problem.

Thank you for being concerned: We appreciate being notified about warnings and error messages.  Ampache is so complex that we need your input.

**Comment by SimonHova** [comment] 2020-08-12 15:23
Thanks for your prompt reply. I agree with and appreciate your assessment, it's not at all critical, but I wanted to make sure that it was on the roadmap, even as a low priority item.

I'm not terribly familiar with Github. Is there a way to lower the priority of an issue? I don't want this to clog up the works, especially if there's a better place to leave it.

**Comment by wagnered** [comment] 2020-08-12 15:37
GitHub is not a bug tracking system, but if the issue appears involved, @lachlan-00  may tag it with a label declaring it's importance. Also, probably by remembering to close the issue when it is resolved helps.

**Comment by lachlan-00** [comment] 2020-08-12 20:47
@wagnered replaced all the dependants in Ampache but it's required by jPlayer which is very old and not part of the project.

```
composer why robloach/component-installer
happyworm/jplayer  2.9.2  requires  robloach/component-installer (*)
```

I think I made an issue with jPlayer so I'll add that here or create an issue and link back

**Comment by lachlan-00** [comment] 2020-08-12 21:08
https://github.com/jplayer/jPlayer/pull/425

**Comment by AshotN** [comment] 2020-09-23 09:30
That project is good as dead.. I would recommend just forking it.

**Comment by lachlan-00** [comment] 2020-09-23 10:56
Yeah, we actually might as well

**Comment by wagnered** [comment] 2020-09-23 17:15
As it is no longer an Ampache dependency, What's the purpose of forking it?  Because jplayer is the only package that uses it and it is also unmaintained, I suggest replacing jplayer instead.

**Comment by AshotN** [comment] 2020-09-23 18:34
Since the change is just one line, the fork wouldnt take much work. Just as a stop-gap until someone handles #2113

**Closed** 2022-09-21 12:42 UTC
Labels: composer
