### ISSUE TITLE
subsonic api: successfully connected but unable to play music

### ISSUE THREAD

**Issue by tristan-k** [ampache/ampache#974] opened 2015-09-26 02:38 UTC
I'm unable to play any music from the subsonic api but the clients (clementine, iSub, Dsub) connect just fine. There is even artwork displayed. When I click on the play button nothing happens. I made sure that the php curl module is installed as mentioned [here](https://github.com/ampache/ampache/wiki/FAQ#when-using-an-api-ampache-subsonic-upnp--i-can-browse-my-library-but-playback-doesnt-work-whereas-it-is-working-using-the-web-interface-how-to-make-it-work). Any suggestions?

**Comment by woodspire** [comment] 2015-09-26 23:37
My bet is that you are using SSL, right ? Try without ssl and my guess is that it will work.

version 3.7 was working with ssl and without but not version 3.8. That's what I am experiencing

**Comment by tristan-k** [comment] 2015-09-26 23:49
You are right. I just checked that and connect via http but the issue remains. I also disabled `Forces Http play regardless of port` in the System config as mentioned [here](https://github.com/ampache/ampache/issues/192) but I'm still unable to play music.

**Comment by woodspire** [comment] 2015-09-26 23:51
Strange. For me, http works perfectly with version 3.8 (I can even seek !). But with SSL, I can browse but not play any music.

With version 3.7, with both ssl and http, I can browse and play music, but seek does not work; the song always get restarted when I try to seek.

**Comment by tristan-k** [comment] 2015-09-26 23:53
Thanks. Maybe I try to downgrade 3.7 to verify your report.

**Comment by tristan-k** [comment] 2015-09-27 00:05
I just enabled logging according to the [wiki](https://github.com/ampache/ampache/wiki/Troubleshooting#ask-ampache-for-help) with `debug_level = 5` and monitored the log with `tail -f` but there are no connection signs.

**Comment by tristan-k** [comment] 2015-09-27 16:05
I downgrade to 3.7 and can confirm that the issue is related to 3.8. With Version 3.7 there is no such behaviour. I can play files flawlessly.

**Comment by Afterster** [comment] 2015-10-01 20:53
Could this be related to https://github.com/ampache/ampache/wiki/FAQ#when-using-an-api-ampache-subsonic-upnp--i-can-browse-my-library-but-playback-doesnt-work-whereas-it-is-working-using-the-web-interface-how-to-make-it-work?

**Comment by tristan-k** [comment] 2015-10-01 21:03
I checked that.  The server is listening on ipv4 and ipv6. The php curl module is installed and enabled.

**Comment by apastuszak** [comment] 2015-10-01 21:26
Mod_rewrite enabled?

**Comment by tristan-k** [comment] 2015-10-01 21:27
Yes, `mod_rewrite` is enabled.

**Comment by STDEin** [comment] 2015-10-13 17:03
Having (what I believe is) the same issue with my Ampache Subsonic API.  Nothing out of the ordinary in my Apache logs. In the Ampache logs (verbosity 5)  I get 

`2015-10-13 11:20:10 [meat] (subsonic) -> Stream proxy: http://[removed]:80/ampache/play/ssid/e5dca331cf330b6ff44cddff8faf269b/type/song/oid/2682/uid/4/client/android/noscrobble/1/player/api/name/Gusto%20-%20Lets%20All%20Chant.m4a`
That url (before censoring) works fine when pasted into a browser, so it doesn't seem to be a transcoding or pathing issue.
mod_rewrite is enabled, and the relevant .htaccess in play and rest are in place.
I've tested Madsonic (current), Subsonic 4.4 (current) and 4.3.1 with the same results.  Library browsing works perfectly, but when a track is streamed it sits for a second then goes onto the next in the playlist (showing it was downloaded).

Any other relevant log snippets or info that could help?

**Comment by Afterster** [comment] 2015-10-14 20:53
@STDEin I believe m4a is not supported by the device. You should first test with mp3 file and if it is working then try to enable transcoding for your m4a files.

**Comment by Afterster** [comment] 2015-11-23 07:31
Any new on this @tristan-k?

**Comment by tristan-k** [comment] 2015-11-23 10:56
I'm still using  3.7 in order to work around the issue.

**Comment by Afterster** [comment] 2015-12-26 21:29
@tristan-k, could you try with latest changes on develop?
Also, please provide Ampache/Apache logs even if you see nothing on it. Thank you.

**Comment by wouldsmina** [comment] 2016-01-17 00:34
same issue with develop. ampache logs : 
```
 "GET /server/xml.server.php?filter=2351&auth=2c9002612cb943a4593bfd9e7d1ea33b&limit=5000&action=song HTTP/1.1" 200 2123 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4;"
"GET / HTTP/1.0" 400 0 "-" "-"
 "GET /server/xml.server.php?timestamp=1452990117&version=350001&user=xxx&auth=3a7e3d7db8cc036135258331145c55bc6f3c9b15abdccaab10dbca11e6172e2f&action=handshake HTTP/1.1" 200 2246 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; )"
"GET /server/xml.server.php?filter=2351&auth=73a12e34a017351da88710324996136b&limit=5000&action=song HTTP/1.1" 200 2123 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4;)"
 "GET / HTTP/1.0" 400 0 "-" "-"
```
I'm using justplayer.

**Comment by Afterster** [comment] 2016-01-17 20:17
@wouldsmina this looks like another issue, justplayer is not using Subsonic api. Could you open another thread and also post Ampache logs. Thanks.

@tristan-k could you try with latest change on develop branch, doing a fresh new test installation to be sure htaccess files are correctly generated? Thanks.

**Comment by Afterster** [comment] 2016-02-27 19:43
Ping @wouldsmina @tristan-k?

**Comment by wouldsmina** [comment] 2016-02-27 21:02
I tested with Subsonic music streamer, same problem only with https. No apache log.

**Comment by Woodwarrior** [comment] 2016-03-26 03:54
I fixed my problem by installing a new git HEAD version of ampache 3.8.3

did a copy of my old database, point new ampache install to it and upgrade it from 3.7.35 to 3.8.10 version.

Still didn't work.

Flush and repopulate the following tables with ampache 3.8.3 vanilla data:

- access_list
- preference
- user (yep, only had 3, so not a problem to recreate admin + 2)
- user_vote
- user_preference
- user_flag
- user_activity


And ... tadam ! working in http & https now.

So problem fixed, but still don't know the problem.

But since that database has been updated from version 3.3 or something like that, well it was time to refresh it a little.

**Comment by DeWir3** [comment] 2016-03-26 14:33
I have the same issue as tristan-k. I can connect via DSub just fine and also browse my library, but playback doesn't work. It just says "Downloading - 0 B". When I set it up though, it worked perfectly. Then it stopped working suddenly without me changing anything.

I tried upgrading to develop, but then Subsonic API seemed to stop working at all, DSub just showed an error message, that the server cannot be found. I tried downgrading to 3.7, but then I got an error in DSub, that my account does not have the permission to access the server. I upgraded to 3.8.2 again and the permission error persisted. Solved that by adding Access Control to API, but now I'm pretty much where I started out. DSub connects and browses, but can't play.

Interestingly, ampache log shows an invalid authentication attempt to Subsonic API:
`(subsonic) -> Stream proxy: https://[link]`
`(Access Denied) -> Invalid authentication attempt to Subsonic API for user [admin]`

**Comment by krayon** [comment] 2016-05-21 15:12
FYI, on a 5.8.0 server, I  encounter this same issue (over both SSL and non-SSL connections) with DSub 5.0.3 however DSub 4.3.5 continues to function perfectly (over either SSL or non-SSL).

**Comment by Phyks** [comment] 2016-06-23 18:35
Looks like a duplicate of #1203. Is this solved for anyone? Else, I think we should continue the discussion there.

**Comment by woodspire** [comment] 2016-07-11 00:51
Fixed the problem by reinstalling ampache from scratch. Now http and https via subsonic can play and seek music.

**Comment by ckotil** [comment] 2016-07-14 07:07
Which version? HEAD?

**Comment by Niols** [comment] 2016-07-14 11:10
Hello @ckotil.
Please test on HEAD of the `develop` branch since fixes has been added to it after 3.8.2

**Comment by ckotil** [comment] 2016-07-15 06:40
I grabbed HEAD. Tho the last step before I could login was at update.php and I complied.
Same behavior.
https://192.168.1.1.1/ampache/rest/getAlbumList.view

192.168.1.1 - - [15/Jul/2016:02:37:52 -0400] "POST /ampache/rest/ping.view HTTP/1.1" 200 225
192.168.1.1 - - [15/Jul/2016:02:37:56 -0400] "POST /ampache/rest/getAlbumList.view HTTP/1.1" 200 225

Should I have skipped that last update step?

**Comment by Niols** [comment] 2016-07-15 08:12
Please provide informations about:
- Your subsonic client's (isub?) logs
- Your Ampache logs
I will try to reproduce (hope isub is free…)

**Comment by ckotil** [comment] 2016-07-26 05:26
Sorry, unfortunately Im no longer jailbroken, and cannot retrieve the iSub clients logs.

**Closed** 2016-07-26 09:18 UTC
Labels: waiting
