### ISSUE TITLE
MacOS music controls do not apply to ampache

### ISSUE THREAD

**Issue by SuperFola** [ampache/ampache#3448] opened 2023-01-09 10:32 UTC
### Describe the bug

The system controls can only pause / play the music but not go to next/previous song, while the web ui allows it.

### To reproduce

1. Create a playlist with at least 2 songs
2. Start it
3. Click on the Apple Music Player in the navbar
4. Next/previous buttons do not work

The buttons are greyed out and they cannot control the playlist.

### Expected behavior

The buttons should control the playlist.

### Screenshots

![controls](https://user-images.githubusercontent.com/10694085/211276769-e1f32196-5ea4-4336-ae3a-ac00fdde4ed8.png)
![playlist](https://user-images.githubusercontent.com/10694085/211276993-e184d2da-273b-4848-9d5f-5c10a24d4823.png)

## Environment

* Ampache version: 5.5.6
* Web server + version: nginx proxy manager 2.9.19
* Server operating system: debian 11
* Client operating system: MacOS Ventura 13.2

### Client type

* Web

## Settings

Using the default settings, forcing SSL.

**Comment by mitchray** [comment] 2023-01-09 22:01
Duplicate of #2812 

Definitely would be nice to have

**Closed by mitchray** 2023-01-09 22:01 UTC

**Comment by SuperFola** [comment] 2023-01-10 16:29
Thanks, I searched for something similar but couldn't find anything.
