### ISSUE TITLE
Persist temporary playlist and playback position to survive reloading/reopening tab

### ISSUE THREAD

**Issue by psy-q** [ampache/ampache#1671] opened 2018-02-11 13:13 UTC
# Environment

 * Ampache version: 3.8.5
 * Web server + version: Apache 2.4.25
 * Server operating system: Debian 9
 * Client operating system: Debian 9
 * Client type:
   - Web (Firefox 58.0.2)

# Settings

All defaults.

# Description

When reloading the page or opening Ampache in another tab, the temporary playlist is lost and playing position in the current song is lost. Sites like Bandcamp provide a side-wide memory of playlist and current position in a song, so it makes no difference whether the page is reloaded.

Couldn't the current play position as well as the playlist be stored in session storage so that reloading the page would have almost no effect?

**Comment by wagnered** [comment] 2018-02-11 16:53
@psy-q 

I agree with you and am marking this as an enhancement.  I have been considering this problem while developing the Ampache/Laravel next generation.

**Comment by lachlan-00** [comment] 2019-05-24 03:05
In the current Core branch the temp playlist is kept:
* When opening a new tab from a link
* Reloading
* ctrl+f5 reloading
* Going to the URL of your site in a new tab without opening a link. (pasting text)

The tmp playlist is kept in the database so restoring that is pretty simple.
BUT the webplayer still needs to be reloaded in all of these situations.

The way the webplayer works i don't think that would be easy to restore. There isn't anything kept for track/position in the database beyond that the file was played. The stream would be regenerated/transcoded and some formats like opus don't report length well.

Right now the best bet you have is to keep ajax loading on and you'll be warned when closing the player tab.

**Comment by mitchray** [comment] 2021-04-30 04:29
Duplicate of #1583

**Closed by mitchray** 2021-04-30 04:29 UTC
Labels: enhancement
