### ISSUE TITLE
Catalog actions return 500 Internal Server Error

### ISSUE THREAD

**Issue by erezschatz** [ampache/ampache#2744] opened 2021-02-10 12:45 UTC
### Describe the bug

I've updated my installation to commit 8be6258ff6a7036191a3033b04059b4a433b65e3, as of now, the catalog actions clean and update are returning 500 (I have not attempted any others). Debug is set to 5 but I don't see any actual errors in the log.

### To reproduce

1. Go to "Admin> Show catalogs"
2. Click on the dropdown menu for Actions and selct either clean or update

here's the curl from 

```curl 'http://equinemusic.com/ampache/admin/catalog.php?action=clean_catalog&catalogs[]=2' --globoff -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0' -H 'Accept: text/html, */*; q=0.01' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Referer: http://equinemusic.com/ampache/browse.php?action=album' -H 'Cookie: ampache_user=erez; ampache_lang=en_US; ampache_remember=...; PHPSESSID=...; ampache=...' -H 'DNT: 1' -H 'Sec-GPC: 1'```

the action returns 500

### Expected behavior
It should work :)

## Environment

* Ampache version:
* Web server + version: Apache/2.4.41 (Ubuntu)
* Server operating system: Ubuntu
* Client operating system: Arch

### Client type

* Web

## Logs

This is from the apache2 logs:

```[Wed Feb 10 13:01:32.669861 2021] [php7:error] [pid 181226] [client 77.139.127.135:33174] PHP Fatal error:  Uncaught Error: Call to a member function isReady() on null in /var/www/html/ampache/admin/catalog.php:41\nStack trace:\n#0 {main}\n  thrown in /var/www/html/ampache/admin/catalog.php on line 41, referer: http://equinemusic.com/ampache/admin/catalog.php?action=show_catalogs```

**Comment by usox** [comment] 2021-02-10 15:35
Hi

Two questions:
- Maybe a dump question but anyway: Are you sure, the catalog with internal id 2 exists?
- If the catalog exists, which type is it?

You stated, you don't see errors in the ampache log, so it looks like the catalog actually does not exist or it's type is unknown. The other errors should write a line in the logfile...

**Comment by erezschatz** [comment] 2021-02-10 15:44
There are no dump questions!

Here's the output from mysql:

```MariaDB [ampache]> select * from catalog;
+----+-------+--------------+-------------+------------+------------+---------+----------------+--------------+--------------+
| id | name  | catalog_type | last_update | last_clean | last_add   | enabled | rename_pattern | sort_pattern | gather_types |
+----+-------+--------------+-------------+------------+------------+---------+----------------+--------------+--------------+
|  7 | music | local        |  1612692207 | 1612692207 | 1612692463 |       1 | %T - %t        | %a/%A        | music        |
+----+-------+--------------+-------------+------------+------------+---------+----------------+--------------+--------------+
1 row in set (0.000 sec)

MariaDB [ampache]> select * from catalog_local;
+----+---------------------+------------+
| id | path                | catalog_id |
+----+---------------------+------------+
|  2 | /var/www/html/music |          7 |
```

**Comment by usox** [comment] 2021-02-10 16:00
@erezschatz Thanks, that helped. The cause for this issue is the same as in #2745, so I'm going to close this issue. There is already a PR (#2747) for this issue so I expect it to be resolved shortly

**Closed** 2021-02-10 16:03 UTC
Labels: bug, duplicate

**Comment by erezschatz** [comment] 2021-02-11 07:31
Yes, I pulled the latest commits now and it works. Thanks all
