### ISSUE TITLE
No Submit Button on Options Page

### ISSUE THREAD

**Issue by bergsalex** [ampache/ampache#1211] opened 2016-04-25 21:04 UTC
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Nginx version: nginx/1.8.1
 * Server operating system: ArchLinx, Version: 4.5.1-1
 * Client operating system: OSX 10.11.4
 * Client type:
   - [x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Chrome Version 50.0.2661.86 (64-bit)
 
# Settings
I tried to remove extraneous info, but it's a pretty big config file:
https://gist.github.com/bergsalex/328a46024d6a634da7c4e47906739ddb

# Description
The options page, under system config, does not render a submit button.
![screen shot 2016-04-25 at 4 31 43 pm](https://cloud.githubusercontent.com/assets/5498330/14798214/796669d8-0b04-11e6-959c-6e5bff312403.png)

# Logs
I'd love to attach a log file, but I can't for the life of me figure out where this error is logged.

The inspector in chrome logs this, but that's all the info I know how to squeeze out of it:
`http:/www.mysite.com/preferences.php?action=admin&tab=options 500 (Internal Server Error)`

My error.log and access.log don't seem to contain relevant info, and neither does ampache.[todays_date].log

**Comment by Afterster** [comment] 2016-05-01 11:56
If you don't get the submit button, this probably means you got a php error before the code reach this button rendering.
You should enable verbose logging, on Apache / PHP / Ampache to see if any more detailed error is logged (ok I believe you already did it).

Did you upgrade from a previous version? If so, could you try with a clean fresh version just for testing? If still failing, then with current develop branch? Thanks.

**Comment by Afterster** [comment] 2016-05-02 04:03
Someone on IRC reported the same issue (probably you with another username btw) and it was related to LastFM plugin. Before further investigation, could you try to disable it? Thanks.

**Comment by bergsalex** [comment] 2016-05-03 20:09
While that sounds like me, I don't remember doing that. I also tried disabling all my plugins with no luck.
I'll try increasing the log level in apache and nginx, but I'm pretty sure I already set Ampache to verbose logging.

Thanks for your help.

**Comment by Slushnas** [comment] 2016-05-05 23:05
What version of PHP are you using?  I had the same issue.  Under the admin account I was getting 500 errors on two pages: Modules -> Localplay Modules and like you: Server Config -> Options.  This seemed to be caused by the PHP script not outputting all of the HTML (the end was cut off).  I was also getting some very slow load times when accessing my server externally.

The fix for me was to downgrade from PHP 7 to PHP 5.6.  As soon as I did that all of the issues went away.  I think there are probably some lingering issues with PHP 7.  I am using the stable (master) version of 3.8.2.  This is on a server running Ubuntu 16.04 with Apache 2.4.18.

**Comment by ricksorensen** [comment] 2016-05-14 20:41
My Options do not show up at all - with no errors reported in ampache nor in apache2 logs.  All the other "Server Config" pages open and have a submit button, but the Option page is entirely blank for me now under both Firefox and Chrome and on both Windows and Ubuntu.

I haven't quite figured out how to get php errors logged .... 


Ampache version: 66ea7bc  (Mid April 2016)
Web server + version: Apache2 2.4.18 (default OS pkg) MySQL: 5.7.12 php: 7.0
Server operating system: Ubuntu 16.04 (upgraded from 15.10)
Client operating system: Windows
Client type:
[ x] Web

**Comment by Slushnas** [comment] 2016-05-14 21:46
@ricksorensen If you can, try using an older PHP version.  That fixed the issue for me.  There are a few guides out there on how to get PHP 5.6 working on Ubuntu 16.04 including the accepted answer here: http://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04

**Comment by ricksorensen** [comment] 2016-05-15 21:52
I'll add notes to github- but the admin/server settings/option page showed
after switching to 5.6 (eventualy!)  Thanks for the process links.

Rick

On Sat, May 14, 2016 at 4:47 PM, Slushnas <notifications@github.com> wrote:

> @ricksorensen <https://github.com/ricksorensen> If you can, try using an
> older PHP version. That fixed the issue for me. There are a few guides out
> there on how to get PHP 5.6 working on Ubuntu 16.04 including the accepted
> answer here:
> http://askubuntu.com/questions/761713/how-can-i-downgrade-from-php-7-to-php-5-6-on-ubuntu-16-04
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ampache/ampache/issues/1211#issuecomment-219253342>
>



-- 
Rick Sorensen
rick.sorensen@gmail.com
651-470-5511

**Comment by Phyks** [comment] 2016-06-08 10:21
@bergsalex 

I highly suspect this is due to https://github.com/ampache/ampache/issues/1232.

Could you try to use the latest commit on `develop` branch, and manually apply the associated PR (just delete the `modules/localplay/xbmc` folder), see if it fixes the issue.

Else, I need more logging to investigate. Especially, PHP logs (ensure to enable PHP error logging, eventually display errors, etc).

I am running an Ampache server with PHP7 without major issues besides the above mentionned one.

**Comment by confusedlinuxgirl** [comment] 2016-07-06 21:45
I have this error as well. Both streaming page and options page.  https://ptpb.pw/h-ej logs.

**Comment by wagnered** [comment] 2016-07-06 23:45
@confusedlinuxgirl,
From your log file, it looks like gettext is not installed on your system or the gettext module isn't being loaded by php.  the error `Call to undefined function _()` on /lib/preferences:247 seems to indicate so.  The _() is a shortcut for gettext() as indicated by the note on [http://php.net/manual/en/gettext](url).

Ernie D

**Comment by confusedlinuxgirl** [comment] 2016-07-07 02:39
I ended up adding a T to _() to make T_() and it was happy. It seems there is a typo in the ampache/lib/preferences.php file.

**Comment by wagnered** [comment] 2016-07-07 06:35
Yea, it does look like a typo.  But  it should be `T_()`.

I haven't had to fix the typo:  I do not have the problem with the
options page that you indicate. So I'm thinking that fixing that typo,
might be hiding another problem, which may crop up later.

@Lucas,

The i18n function on Line 247 in lib/preferences appears as `_('Web
Player')` and should be  `T_('Web Player')`.  I think that most of us do
not have the same problem because gettext is installed and the gettext
php module is loaded.  php.net indicates that _() is an alternate call
to gettext().

I would like your thoughts about this, and request that you might add
the change during one of your commits. 

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by Phyks** [comment] 2016-07-07 08:41
So, from the first image on the page (in the first comment), it is definitely coming from https://github.com/ampache/ampache/issues/1232, as the render breaks just after the "localplay type" list. You have a different issue than this one.

This is indeed an issue with Gettext, which was already partly fixed in a [previous PR](https://github.com/ampache/ampache/pull/1239).

My upcoming PR will fix it.

**Closed** 2016-07-08 05:19 UTC
Labels: waiting

**Comment by Afterster** [comment] 2016-07-08 05:21
Nice catch everybody :+1:
