### ISSUE TITLE
lib/components non-existent until *after* initial install

### ISSUE THREAD

**Issue by GottemHams** [ampache/ampache#2339] opened 2020-03-30 17:42 UTC
### Describe the bug
When cloning the `develop` branch and running [the composer command mentioned in the wiki](https://github.com/ampache/ampache/wiki/Installation#composer), the `lib/component` directory is non-existent until you've finished the initial install. This could mean some UI elements don't quite work and you can't actually properly finish the install, in my case I applied a workaround before attempting to continue to make sure I wasn't left with a half install. The workaround being symlinking `lib/vendor/components/{bootstrap,jquery,jqueryui}` into `lib/components`. The latter directory now contains 98 symlinks.

I did find some related issues on here but they were all resolved by rerunning the composer command or even running it in the first place.

Even though everything seems to work properly after applying the initial workaround, I have no idea if the original cause was perhaps a conflict somewhere. This may cause certain aspects to not work correctly. Which is the reason why I'm creating this report.

### To reproduce
Not quite sure of the exact steps as pretty much everything I did was mentioned on the above wiki page:
1. Log in as a non-root user to the webserver
2. `git clone -b develop https://github.com/ampache/ampache.git /some/dir`
3. `cd /some/dir`
4. `composer install --prefer-source --no-interaction`
5. Watch the output for any errors (should be none)
6. Navigate to the installation page
7. Be presented with a broken UI and a lot of errors in the browser's developer console

### Expected behavior
Bootstrap and jquery-ui should've been properly symlinked so the interface works okay.

### Screenshots
These were taken after running the steps to reproduce again, but in another directory so it wouldn't mess with my current install.
![Web interface](https://user-images.githubusercontent.com/20195269/77942776-6d379a00-72bc-11ea-9236-bd17f4ac037b.png)

![Browser console](https://user-images.githubusercontent.com/20195269/77942997-ce5f6d80-72bc-11ea-851b-0a03dbeed345.png)

## Environment
* Ampache version: 4.2.0-develop
* Web server + version: nginx 1.10.3
* Server operating system: Openmediavault 4 (Debian Stretch based mediacenter distro)
* Client operating system: Mac OS X El Capitan
* Composer version: 1.10.1 2020-03-13 20:34:27

### Client type
* Web: ampache

## Settings
Shouldn't be relevant here I think?

## Logs
Ditto, although I already posted a screenshot of the browser console log. I also have nginx access logs stating the same so that just seems redundant.

**Comment by lachlan-00** [comment] 2020-03-31 06:12
i'll run up an install and see if i can do that.

I'm installing something at least once a month and just use 'composer install' without any visual issues.

**Comment by Afterster** [comment] 2020-03-31 06:27
I was able to reproduce on my side but didn't found the reason yet... I'm a bit rusty concerning composer tricks :).

**Comment by lachlan-00** [comment] 2020-03-31 07:01
it will be when i did this.
https://github.com/ampache/ampache/commit/a4b4c881c5c8af65d4066d0e2f1be9778ed55f00

**Comment by lachlan-00** [comment] 2020-03-31 07:07
my test had already installed the lib so i've missed that this isn't a drop in replacement. reverted for now and i'll look at the config.

**Comment by lachlan-00** [comment] 2020-03-31 07:07
fixed by reverting https://github.com/ampache/ampache/commit/a4b4c881c5c8af65d4066d0e2f1be9778ed55f00

**Closed by lachlan-00** 2020-03-31 07:07 UTC
Labels: bug

**Comment by GottemHams** [comment] 2020-03-31 15:03
@lachlan-00 Thanks for the fix. :> Should I rerun the composer command or am I good already?
