### ISSUE TITLE
Webplayer - Chrome-based browsers do not move to next song

### ISSUE THREAD

**Issue by HedAurabesh** [ampache/ampache#1675] opened 2018-02-18 19:06 UTC
# Environment

 * Ampache version: 3.8.5 & develop branch (18.02.2018 20:00 MET)
 * Web server + version: Apache 2.4.18-2ubuntu3.5
 * PHP Runtime: 7.0.25-0ubuntu0.16.04.1
 * Server operating system: Ubuntu 16.04.3 LTS
 * Client operating system: Windows 10

 * Client type:
   - Web

# Settings and Logs
Redacted Log File: [ampache.20180218.log](https://github.com/ampache/ampache/files/1735004/ampache.20180218.log)
Redacted Config: [ampache.cfg.php.txt](https://github.com/ampache/ampache/files/1735006/ampache.cfg.php.txt)

# Description

Since upgrading from Ampache 3.8.3 to 3.8.5 the Webplayer does not work correctly in Chrome-based browsers (Chrome, Opera, Vivaldi).

When you start playing from a list, the first song plays normally, but the player stops (goes to pause) at the end of the first song. To get the next song to play, one has to manually click the "next" button.

In Firefox, the songs play correctly and are moved automatically to the next song. Streaming from a m3u playlist file also works correctly.

This was replicated on three separate Windows 10 computers, all running the latest versions of all browsers involved. I also upgraded the server to the "develop" branch, but that has the same results.

**Comment by s3ned** [comment] 2018-02-28 20:53
I have the same issue with Ampache 3.8,2 with ubuntu 14.04 apache 2,14 php 7 on the server and windows 10 and chrome Version 64.0.3282.186 (Officiële build) (64-bits)

It works for one or two tracks and then stops playing

**Comment by saue0** [comment] 2018-03-02 16:52
Same problem with Chrome.
Using IE on Windows 10 is OK (Same computer)

**Comment by HedAurabesh** [comment] 2018-03-06 11:04
Hi everyone.

A small update: I down-graded the server from 3.8.5 to 3.8.3 by restoring the DB dump and restoring the correct composer dependencies.

This has **not** solved the issue, unfortunately. Now, even with 3.8.3, the songs just stop on Chrome-based browsers. :-(

**Comment by toptnc** [comment] 2018-03-12 11:20
Same issue here.
Ubuntu 16.04
Ampache 3.8.6-release
apache 2.4.18-2ubuntu3.5
PHP 7.0.25

Client:
Chrome stable: 65

**Comment by wagnered** [comment] 2018-03-12 21:44
@HedAurabesh  and all...

Sorry to take so long to get back to you.

Can I assume everyone is using Windows 10?

@saue0 indicates it's not a problem with IE. 

There is another issue (#1677) which indicates a similar issue with Firefox, but the Windows version is not revealed.

I booted my Windows 8.1 virtual machine and tried it with Chrome 63 with no problems,  I then installed Chrome 65 and again had no problems,  A playlist with about 10 songs automatically started playing and continued playing through all ten songs without clicking the play button on the player.

As I do not have Windows 10, I cannot reproduce the environment exactly. but it looks like it might be the way Chrome and Firefox are interacting with Win 10. Or something with Win 10 that is causing a break in the connection between the server and the Browser and not Ampache.

**Comment by HedAurabesh** [comment] 2018-03-12 22:59
Hi @wagnered.

Thanks for looking into this. Yes I was using Windows 10 on all the test hosts. But out of a lark, I just tried it on an Android smartphone and tablet with the Chrome there, and they show the same issue.

I then looked at the Vivaldi Browser closer (which also uses the Blink engine) and I must retract my earlier statement. All files work fine in both in versions 1.11.917.43 (UA says Chrome/60.0.3112.105) as well as 1.14.1077.55 (UA says Chrome/64.0.3282.189).


By now, I suspect that it is an issue with MP3 files whose file-size is not exactly like Ampache expects it.

Recently, I have re-tagged (via mp3tag) and normalized (via mp3gain) most of my audio collection. All files work perfectly fine when streamed for Firefox, Internet Explorer or Vivaldi, but almost all of the edited files show the "stopping" issue in Chrome and Opera. Almost as if Ampache's WebPlayer stumbles over the last few bytes of the file that have been added by the tagging in those browsers.

I suspect that, because freshly downloaded & added files do not show this issue. They play fine in all browsers.

I already tried a full update of all catalogs, but that did not help. I would continue with trying to purge & rescan my entire catalog, but I do not want to destroy the way to replicate this issue.

If it would help you, I can send you more log-files, example audio files or even give you a login to my Ampache so that you can check it out yourself.

**Comment by wagnered** [comment] 2018-03-13 02:51
@HedAurabesh 

I just accessed my Ampache server from Chrome v65 on my Android 7.1 phone.  It's been playing constantly with no intervention on my part.

I also noticed that you were having trouble with mp3 files which weren't being transcoded.  I was playing flac files which were, so I changed the playlist to mp3 files to remove another "variable"
Still no problem. If I can only replicate your issue with one of your files, then it must be your files. :smile:  

Looking closely at the Ampache log you refer to in your original post, the last song was sent to the client in it's entirety. Then the client requested the last part of the song again. This implies that something interrupted the stream and the buffer "ran dry" causing the web player to request the remainder of the song.

> Almost as if Ampache's WebPlayer stumbles over the last few bytes of the file that have been added by the tagging in those browsers.

I'm not sure what you mean by that statement.  ID3V2.* tags are usually inserted at the beginning of the file.  They can be entered at the end of the file, but that's not usual practice because that's where ID3V1 tags are added and would cause problems with reading them.

Also, because you also stated that:

> All files work perfectly fine when streamed for Firefox, Internet Explorer or Vivaldi,

Because there is no problem with other browsers, I am not convinced that the problem is with Ampache.

> I would continue with trying to purge & rescan my entire catalog, but I do not want to destroy the way to replicate this issue.

You might as well, as I cannot replicate the issue.  One suggestion though, try removing mp3gain from the files and see what happens in Chrome.

**Comment by narigondelsiglo** [comment] 2018-03-13 11:26
I'm having this problem with this UA: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
I have Ubuntu on server and desktop.
I use Firefox to listen now, with FF it works well. Chrome stops after one or two songs.

**Comment by wagnered** [comment] 2018-03-13 16:37
@narigondelsiglo 

Thanks for the info. I had been using Chromium V. 63 thinking it was the Linux version of Chrome.  So I downloaded Chrome V.  65 and installed it on my Fedora Linux system.

It also has been playing continuously for the last 15 minutes.

I opened the "About Chrome" dialog and found:
> Google Chrome is made possible by the Chromium open source project and other open source software.

 I then opened the development version of Chromium and found the Chrome binary. :smile:

**Comment by HedAurabesh** [comment] 2018-03-13 23:24
> Looking closely at the Ampache log you refer to in your original post, the last song was sent to the client in it's entirety. Then the client requested the last part of the song again. This implies that something interrupted the stream and the buffer "ran dry" causing the web player to request the remainder of the song.

That is because I started playing the song and then skipped to near the end. That is the interruption you see. The same behaviour (the stoppage) also occurs when I play the file from beginning to end -- I just have to wait longer.

> I'm not sure what you mean by that statement. ID3V2.* tags are usually inserted at the beginning of the file. 

Yes, but I was adding both ID3v1 as well as ID3v2 tags. That inserts data both at the beginning and end of the files. Also, even if I just added ID3v2 tags, it would still change the size of the file from what Ampache expects. :-)

>> I would continue with trying to purge & rescan my entire catalog, but I do not want to destroy the way to replicate this issue.
>>
>You might as well, as I cannot replicate the issue.

I did so and after the rescan, the same issue appeared on the same files.


Here is a test file (in a ZIP container to placate GitHub) whose original can be freely downloaded from OCRemix. It stops at the end at 02:28 and refuses to go to the next item in the playlist:
[CarboHydroM_-_Rising_Sun.zip](https://github.com/ampache/ampache/files/1809023/CarboHydroM_-_Rising_Sun.zip)

**Comment by wagnered** [comment] 2018-03-14 03:26
@HedAurabesh 

I guess I got sidetracked and failed to explain:  Ampache uses the mp3 header to calculate the duration of the song.  Tags are ignored. I checked the song duration with several different tools and got approximately 2:38. 

The song always played to the end (2.38) never stopping in the middle of the song.
In Chrome, the song did play in its entirety, but it did refuse to continue on to the next track. 

In Firefox, it did continue on to the next track.

So yes, Chrome has a strange reaction to that particular song. Looking at it with the getID3 library there was a warning: MP3gainTrackGain value in APEtag appears invalid: "-0.090000 dB"

Don't know if that is the problem, but the file plays ok in other web browsers, so It doesn't look like a problem with Ampache.

**Comment by HedAurabesh** [comment] 2018-03-14 09:46
Hi @wagnered 

It's great that we finally found a way for you to be able to replicate the issue. I do agree that it is frustrating that it only happens in Chrome and that there might be little that can be done about it from Ampache's side.

But still, the point is that you can't really ignore that behaviour of Chrome. According to recent web stats, Chrome has a market-share of 65%. At that point, such a bug stops being an issue that you can safely ignore from Ampache's side, because it affects a large swath of your users.

Look at it like that: ~65% of the users of Ampache will use it with Chrome, while considerably less than 1% of the Chrome users use Ampache. Google is unlikely to fix that issue, if it basically only affects Ampache.

I would argue that this is reason enough to see what can be done about it from Ampache's side. :-)


I will try to strip all mp3gain tags from my files and check if that "solves" the issue. If it does, then at least we have a possible "in" to maybe workaround the bug from Ampache's side. 😋


Thanks again, for looking into this!

**Comment by wagnered** [comment] 2018-03-14 21:40
OK, Some progress.

BTW, mp3gain, on Linux, doesn't remove the APE tag(s).  To remove the APE tag(s) I had to use an app called Audacity to export the song to another  file name.  I added that file to the catalog and playlist.

The Song continues on now, and still doesn't stop intermittently.

Evidently mp3gain removed the information but not the APE tag.  It seems to be the APE tag that is confusing Chrome.

To test, I added replaygain to a song on the playlist using APE tags and it also failed after adding the replaygain..  

Replacing the file and adding the replaygain using mp3 tags, the file continued to next song as it should.

**Comment by HedAurabesh** [comment] 2018-03-15 19:58
Hi.

I have now removed all APEv2 tags from my files, using "mp3tag" via:
- Extras -> Options
- Remove -> Only select APE 
- Select all files
- File -> Remove Tags

Afterwards, I created a random playlist in Chrome.

The good news: About 90% of the files now play correctly.
The bad news: About 10% still fail. Even after stripping out the APEv2 tags and telling mp3gain to strip its tags in both formats (if any left).

@wagnered : Since the only files that I could find that are still affected are non-free files, would you mind if I sent you a new test file to your comcast mail address?


Thanks again for looking into this!

P.S.: I did not use Audacity, since Audacity re-compresses the file when exporting to MP3, which probably defeats the purpose of this test. :D

**Comment by wagnered** [comment] 2018-03-15 20:28
How did you verify that the APE (wrapper) is actually gone from the suspect file?

I used lib/vendor/james-heinrich/getid3/demos/demo.browser.php to view the information in the suspect files.  It's necessary to comment/remove the first line in demp.browse.php to get it to work.

As I indicated previously, It didn't remove the APE wrapper only the information.  I use the word "wrapper" because the browser had shown that the APE wrapper extended across the entire ID3 layer.

> P.S.: I did not use Audacity, since Audacity re-compresses the file when exporting to MP3, which probably defeats the purpose of this test.

Yes, But what is the purpose of the test?  you could create a copy of the suspect file. I think that would be adequate.

I try have most of my music in .flac containers which are misnamed "Lossless", but at a much higher sample rate compared to MP3's they are nearly "lossless".

OK, send me the file.  I'll take a look at it.

**Comment by HedAurabesh** [comment] 2018-03-30 12:14
Hi @wagnered.

Sorry for the long delay, but the past 2 weeks were quite busy for me. I have sent you the test-file for the issue today.

Regarding your question about looking for the APE wrapper, I scanned the file for the presence of the APE tag header ("APETAGEX") with a hex editor and could not find any trace of it in the file. Only the ID3 tags are present and visible. I removed the tag via the "MP3Tag" program for Windows.


The reason why I think that re-encoding the file would defeat the purpose of this test is because it would alter the entire structure of the file and might thus hide the issue by removing the problematic data sequences.

After all, I know now that **most** files work fine, only **some** files are problematic. By re-encoding, I could of course make the problematic files work fine -- but that just avoids the issue, instead of fixing it. :-D

**Comment by wagnered** [comment] 2018-03-30 21:26
@HedAurabesh 

Update:

I tried playing the sample song directly in Chrome and got the same results as playing it via Ampache's HTML player.

I submitted an Issue to Google Chrome concerning this problem.  I don't know if or when I'll get a response.

You might give [Chromium](https://chromium.woolyss.com/download/en/) a try.  Google Chrome is Forked from Chromium and there seems to be very little difference.

**Comment by wagnered** [comment] 2018-04-08 17:51
Bug has been submitted ( Issue 830263) to the chromium bug database.

**Comment by wagnered** [comment] 2018-04-09 06:15
Latest message from Chromium developers:

M66 Beta to be released in two to three weeks.  Doesn't appear to have problem.

From Chromium developers:

> @Reporter: Please check the issue on latest beta and let us know if the issue is fixed there. You can download beta build from https://www.chromium.org/getting-involved/dev-channel.

**Comment by wagnered** [comment] 2018-04-09 06:25
66 Beta does work.

**Comment by michaelcadilhac** [comment] 2018-04-10 09:13
66 worked for some time, but then exhibits the same problem.   Certainly an improvement, but still quite worse than 63.

**Comment by dalecurtis** [comment] 2018-04-10 17:27
Can you try 67? 66 contains the bulk of the fixes, but 67 straight up discards anything invalid for mp3 containers.

**Comment by wagnered** [comment] 2018-04-10 19:46
@dalecurtis 

I only have one problem mp3 that I know of.  I'll put it in a playlist and loop on the playlist.

@michaelcadilhac 

You probably have more problem files than I, Could you test 67 and give us a report?

Thanks...

**Comment by wagnered** [comment] 2018-04-18 13:48
I think this can finally be closed :laughing:

**Closed by wagnered** 2018-04-18 13:48 UTC

**Comment by HedAurabesh** [comment] 2018-04-23 15:58
Hi everyone.

I also tried my catalog with v67 and v68 (Canary) and I indeed get no problems anymore.

Curiously: v66 did not have the "stop at end of song" issue, but rather an even nastier "Stop somewhere in the middle of the song" issue. 😵 

But anyway, I agree (post fact) that the ticket can indeed be considered closed, given that v67 is going to be released soon. 😀
