### ISSUE TITLE
Abandoned composer dependency

### ISSUE THREAD

**Issue by KaeTuuN** [ampache/ampache#2644] opened 2020-12-08 12:44 UTC
### Describe the bug

1. Download 4.2.5.zip
2. unzip && cd ampache
3. sudo -u www-data composer install --prefer-source --no-interaction
4. Output: _Package robloach/component-installer is abandoned, you should avoid using it. Use oomphinc/composer-installers-extender instead._

**Comment by lachlan-00** [comment] 2020-12-08 22:03
dupe of #2500 it's part of jplayer which needs to be updated

**Closed by lachlan-00** 2020-12-08 22:03 UTC
Labels: composer, duplicate
