### ISSUE TITLE
Cover.jpg files are not added

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#3126] opened 2021-12-20 22:36 UTC
### Describe the bug
I have a lot of cover.jpg files in the albums and I do not see them being added. I tried update and gather all art without luck

Here is an image that shows the cover state and the cover folder

![explorer_u8uUKgOTn3](https://user-images.githubusercontent.com/8519469/146841896-c6eb411d-320a-46f4-80da-ea134a7fa366.jpg)

### To reproduce
Add cover.jpg
Rescan folders

### Expected behavior
It should add all the cover.jpg files as 

## Environment

* Ampache version: 5.2
* Web server + version: Apache 2.4
* Server operating system: Debian Testing
* Client operating system: Windows

### Client type

* Web

## Settings
```
; Album Art Preferred Filename
; Specify a filename to look for if you always give the same filename
; i.e. "folder.jpg" Ampache currently only supports jpg/gif and png
; Especially useful if you have a front and a back image in a folder
; comment out if Ampache should search for any jpg, gif or png
; DEFAULT: folder.jpg
album_art_preferred_filename = "cover.jpg"

; Album Art Store on Disk
; This defines if arts should be stored on disk instead of database.
; DEFAULT: false
;album_art_store_disk = "false"
```

## Logs
The logs are insanely long and there are alot of personal stuff there. Let me know what I am looking for so I can paste that portion.

**Comment by mitchray** [comment] 2021-12-20 22:51
If you try to upload a local image directly to an album do you see that fail too?

**Comment by gerroon** [comment] 2021-12-20 23:13
Yeah it seems to add fine.

**Comment by JoeDat** [comment] 2021-12-21 13:26
Do you have artist art, and does that gather?  What's your art gather order?  If you left it default, try setting 'folder' first.  Example:

```
Art Gather Order
; Simply arrange the following in the order you would like
; Ampache to search. If you want to disable one of the search
; methods simply leave it out. DB should be left as the first
; method unless you want it to overwrite what's already in the
; database
; POSSIBLE VALUES (builtins): db tags folder lastfm musicbrainz google
; POSSIBLE VALUES (plugins): Amazon,TheAudioDb,Tmdb,Omdb,Flickr
; DEFAULT: db,tags,folder,spotify,musicbrainz,lastfm,google
art_order = "folder,tags,db"
```

**Comment by PsyZeus** [comment] 2021-12-29 16:43
@gerroon did you manage to solve it finally?

@JoeDat i checked my back up config from 5.1.1 and has the same order as 5.2.0 config(since i don't need to do any customs to config i start in every update with the new default config, only import db credentials) so this doesn't seem to be the cause.

**Comment by gerroon** [comment] 2021-12-29 18:29
Hi

I was not able to solve it, actually I am also missing a lot of artists and albums:( I have an Airsonic Advanced running on the same system, scanning the same exact music folders and I realized that Ampache has been missing a lot of albums and music compared to Subsonic :( Not sure if these issues are related.

I even deleted my whole catalogs and did a scan from total scratch, still not finding all the musc and some stuff still misses covers whereas Airsonic has all the albums with proper covers.

thanks

**Comment by JoeDat** [comment] 2021-12-29 21:08
What do you see if you enable debug logging and tail as its scanning?  Do you possibly have SELinux enabled on your instance?  If so, try disabling that and rescanning.  It's likely that Airsonic would be running under a different account, so it's possible you might have a permissions issue with your apache user?   The debug logs would show that.

**Comment by gerroon** [comment] 2021-12-29 22:23
Hi

I do not think it is the permissions, I did 777 on every folder and  file in that folder. Also I have over 1TB of music stuff there not sure how I can debug this through logs :(

**Comment by lachlan-00** [comment] 2022-01-04 04:48
just changed my config to cover.jpg and rand an art check successfully

```
2022-01-04T14:45:22+10:00 [user] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Found preferred image file: cover.jpg
```

Permissions would be a likely culprit 

In debian you can su to the web server user and check the perms for the folder
```
sudo su - www-data -s /bin/bash
```

Then you can stat a file you konw exists. if you can't get the path due to permissions yoiu'll get an error like this 
```
www-data@steam:~$ stat /root/bin
stat: cannot statx '/root/bin': Permission denied
```

**Comment by PsyZeus** [comment] 2022-01-06 11:32
@lachlan-00  i changed this line in config
from
;album_art_preferred_filename = "folder.jpg"
to
album_art_preferred_filename = "cover.jpg"
and i still dont get covers when i add new music from /catalog.php?action=show_catalogs with the "add" option from drop down folder menu
but i get the covers once i do "gather art"  from /catalog.php?action=show_catalogs drop down folder menu

**Comment by mitchray** [comment] 2022-01-06 13:05
@PsyZeus I'm seeing the same thing here, as well as not being able to replace existing images; the old image remains

**Comment by PsyZeus** [comment] 2022-01-06 13:34
@mitchray i tested with something new i added and i can change the image,

steps i made
added the new release --> no image detected
gather art --> cover was set
change the cover --> new image appears
change the cover again --> new image appears again

i didn't tested tho with older releases..

fwiw i'm on ampache-5.2.0_all_php8.0

**Comment by PsyZeus** [comment] 2022-01-06 13:42
@mitchray i tested with something new i added and i can change the image,

steps i made
added the new release --> no image detected
gather art --> cover was set
change the cover --> new image appears
change the cover again --> new image appears again
i didn't tested tho with older images..

fwiw i'm on ampache-5.2.0_all_php8.0
php 8.0.14
mariadb 10.5.12

**Comment by gerroon** [comment] 2022-01-06 16:43
> www-data@steam:~$ stat /root/bin
> stat: cannot statx '/root/bin': Permission denied

I tested all the file with it, no error reported.

**Comment by lachlan-00** [comment] 2022-01-07 00:53
the worker was setting false when the default is to gather art for add. set with 7f42acff3

**Comment by PsyZeus** [comment] 2022-01-09 18:11
@lachlan-00 sorry for the late reply
today i had the time and added fresh music, i updated the CatalogActionMethod.php & Catalog.php with the fixes but unfortunately the same issue persists.

@mitchray did you had the chance to test the fixes?

**Comment by lusum** [comment] 2022-01-10 19:37
Maybe looking for errors and/or look for cover.jpg in logs and purging personal data before posting should help

**Comment by mitchray** [comment] 2022-01-11 04:32
It doesn't appear to be working with that patch for me either, I'm guessing its something else which has been changed roughly around the 5.1.1 release I'm estimating

**Comment by PsyZeus** [comment] 2022-01-29 17:02
@lachlan-00  @mitchray  @gerroon @lusum 
so i had some time and played around it and found some errors, i also found that for some reason newer versions of ampache doesn't seem to gather all the album arts even when you do a gather art from /catalog.php?action=show_catalogs as mentioned above as a dirty fix.

for the first and known issue in this thread below is the errors from log, seems like the errors are
"image less than 5 chars, not inserting" - for the albums art
"gather_art_item artist: {10256} blocked" - for the artists art

for the second issue, i was experimenting and deleted all rows from image table and then regather art, i found that ampache 5.2.0 missed a lot covers(maybe around 200 of a total ~3500 albums) while 3.9.0 which was the version i first created the db had found all of them.

[ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-01-29T18:27:29+02:00 [ampachetest] (Ampache\Module\System\Session) -> h175i3ae3uhnhfkph2gf68pod9 has been extended to Sat, 29 Jan 2022 19:27:29 +0200 extension length 3600
2022-01-29T18:27:29+02:00 [ampachetest] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Admin\Catalog\AddCatalogAction" for action "add_catalog"
2022-01-29T18:27:29+02:00 [ampachetest] (Ampache\Module\System\Session) -> Session created: 60f6199c1d9dc09266ae291080bf4aa9
2022-01-29T18:27:29+02:00 [ampachetest] (Ampache\Module\System\Core) -> Verified SID d14cdfc0f53e0e6540dea7132c6069fa for post form add_catalog
2022-01-29T18:27:29+02:00 [ampachetest] (Ampache\Module\System\Core) -> Registered post form confirmation with SID 148e8800f1935463252027e22dbd5182 and expiration 1643477249 (3600 seconds from now)
2022-01-29T18:27:29+02:00 [ampachetest] (Ampache\Module\System\Session) -> Writing to h175i3ae3uhnhfkph2gf68pod9 with expiration 1643477249
2022-01-29T18:27:30+02:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\System\Session) -> h175i3ae3uhnhfkph2gf68pod9 has been extended to Sat, 29 Jan 2022 19:27:30 +0200 extension length 3600
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\System\Session) -> Writing to h175i3ae3uhnhfkph2gf68pod9 with expiration 1643477250
2022-01-29T18:27:30+02:00 [ampachetest] (local.catalog) -> Reading 2 inside g
2022-01-29T18:27:30+02:00 [ampachetest] (local.catalog) -> Memory usage: 2 MB
2022-01-29T18:27:30+02:00 [ampachetest] (local.catalog) -> Found song file to import: g
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: musicbrainz is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: theaudiodb is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Album) -> check album: created {6517}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map album: {6517}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map song: {34079}
2022-01-29T18:27:30+02:00 [ampachetest] (local.catalog) -> Found song file to import: g
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: musicbrainz is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: theaudiodb is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Artist) -> check artist: created {10587}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map artist: {10587}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Album) -> check album: created {6518}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map album: {6518}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map song: {34080}
2022-01-29T18:27:30+02:00 [ampachetest] (local.catalog) -> Found song file to import: g
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: musicbrainz is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: theaudiodb is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map song: {34081}
2022-01-29T18:27:30+02:00 [ampachetest] (local.catalog) -> Found song file to import: g
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: musicbrainz is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Util\VaInfo) -> _get_plugin_tags: theaudiodb is not a valid metadata_order plugin
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> update_map song: {34082}
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art found 3 items missing art
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art_item artist: {10256} searching
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Searching using:["db","spotify","TheAudioDb","musicbrainz","lastfm","tags","folder"]
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: db
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: spotify
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\SpotifyCollectorModule) -> gather_spotify: Missing Spotify credentials, check your config
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> TheAudioDb not defined
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: musicbrainz
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: lastfm
2022-01-29T18:27:30+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: tags
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\MetaTagCollectorModule) -> Skipping picture id 3 for artist search
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\MetaTagCollectorModule) -> Skipping picture id 3 for artist search
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: folder
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening g and checking for artist Art
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening g and checking for artist Art
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening g and checking for artist Art
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening g and checking for artist Art
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art_item album: {6517} searching
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Searching using:["db","spotify","TheAudioDb","musicbrainz","lastfm","tags","folder"]
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: db
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: spotify
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\SpotifyCollectorModule) -> gather_spotify: Missing Spotify credentials, check your config
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> TheAudioDb not defined
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: musicbrainz
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: lastfm
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\LastFm\LastFmQuery) -> search url : http://ws.audioscrobbler.com/2.0/?method=album.getInfo&artist=g&album=g&api_key=g
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:31+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:31+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:31+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:31+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:31+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> results:[{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"}]
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art_item artist: {10587} searching
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Searching using:["db","spotify","TheAudioDb","musicbrainz","lastfm","tags","folder"]
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: db
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: spotify
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\SpotifyCollectorModule) -> gather_spotify: Missing Spotify credentials, check your config
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> TheAudioDb not defined
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: musicbrainz
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: lastfm
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: tags
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\MetaTagCollectorModule) -> Skipping picture id 3 for artist search
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\MetaTagCollectorModule) -> Skipping picture id 3 for artist search
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\MetaTagCollectorModule) -> Skipping picture id 3 for artist search
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: folder
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening g and checking for artist Art
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\FolderCollectorModule) -> gather_folder: Opening g and checking for artist Art
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art_item album: {6518} searching
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Searching using:["db","spotify","TheAudioDb","musicbrainz","lastfm","tags","folder"]
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: db
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: spotify
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\SpotifyCollectorModule) -> gather_spotify: Missing Spotify credentials, check your config
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> TheAudioDb not defined
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: musicbrainz
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> Method used: lastfm
2022-01-29T18:27:31+02:00 [ampachetest] (Ampache\Module\LastFm\LastFmQuery) -> search url : http://ws.audioscrobbler.com/2.0/?method=album.getInfo&artist=g&album=g&api_key=g
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:32+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:32+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:32+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:32+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Module\Art\Collector\LastFmCollectorModule) -> LastFM: found image 
2022-01-29T18:27:32+02:00 [ampache] (log.lib) -> [Runtime Error] Undefined array key "extension" in file /var/www/html/ampachetest/src/Module/Art/Collector/LastFmCollectorModule.php(119)
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Module\Art\Collector\ArtCollector) -> results:[{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"},{"url":"","mime":"image\/","title":"LastFM"}]
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Image less than 5 chars, not inserting
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art_item artist: {10256} blocked
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> gather_art_item artist: {10587} blocked
2022-01-29T18:27:32+02:00 [ampachetest] (Ampache\Repository\Model\Catalog) -> Run Garbage collection

**Comment by PsyZeus** [comment] 2022-02-04 19:25
any news anyone?! :)

**Comment by PsyZeus** [comment] 2022-02-05 11:58
seems i found just a part of what changed in recent ampache and messes up the gather art but i have a serious issue nevertheless...

In newer config version  art gather order doesn't follow the default anymore but the uncommented line.(see at the end of the comment)
Somehow the new uncommented line leads to errors and doesn't feel neither the album art or artist art.
Now if you just comment the line again default doesn't work and you get the error "art_order not set, self::gather_art aborting"
So if you just edit the line from
art_order = "db,spotify,TheAudioDb,musicbrainz,lastfm,tags,folder
to
art_order = "db,tags,folder,spotify,musicbrainz,lastfm,google
you get back on the works the album art but here is the big issue that artist art is also the cover(album art) which leads to a huge db in GB's.
In previous versions artist art was gathered from google and album art from folder somehow.
For the record i deleted all rows from image table and regathered art, from a db of 1,5GB with album art from folders and artist art from google it went to 6GB with album art from folders and artist art from folder too.

new config

; Art Gather Order
; DEFAULT: db,tags,folder,spotify,musicbrainz,lastfm,google
art_order = "db,spotify,TheAudioDb,musicbrainz,lastfm,tags,folder"

old configs are

; Art Gather Order
; DEFAULT: db,tags,folder,spotify,musicbrainz,lastfm,google
;art_order = "db,tags,folder,spotify,musicbrainz,lastfm,google"

**Comment by mitchray** [comment] 2022-02-05 12:05
This is just a hunch but I think it was after this PR that this started happening

#3099

**Comment by PsyZeus** [comment] 2022-02-11 19:03
still not fixed with 5.2.1 :'(

**Comment by gerroon** [comment] 2022-04-01 04:09
Hi Is this fixed at all?

**Comment by PsyZeus** [comment] 2022-04-03 14:40
this issue made me realize how unnecessary big my db was, so im grateful that this came up lol 

@gerroon 
change this line to

art_order = "db,tags,folder"

unfortunately artists art is gathered from there as well but if you don't mind about artist art like me you can run a db cleanup before every backup
the below script deletes all artist art and converted images from db.

`#!/bin/bash
echo 12345 | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where object_type = 'artist';"
echo 12345 | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '768x768';"
echo 12345 | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '200x200';"
echo 12345 | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '160x160';"
echo 12345 | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '128x128';"
echo 12345 | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '48x48';"`

**Comment by PsyZeus** [comment] 2022-04-03 14:44
this issue made me realize how unnecessary big my db was, so im grateful that this came up lol

@gerroon
change this line to

art_order = "db,tags,folder"

unfortunately artists art is gathered from there as well but if you don't mind about artist art like me you can run a db cleanup before every backup
the below script deletes all artist art and converted images from db.

#!/bin/bash
echo sudopassword | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where object_type = 'artist';"
echo sudopassword | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '768x768';"
echo sudopassword | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '200x200';"
echo sudopassword | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '160x160';"
echo sudopassword | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '128x128';"
echo sudopassword | sudo -S mysql -u user -ppassword -e "USE databasename;delete from image where size = '48x48';"

**Comment by gerroon** [comment] 2022-04-03 18:10
@PsyZeus 

Does this fix the cover art issue though? My issue was not about the artists.

**Comment by PsyZeus** [comment] 2022-04-03 18:32
@gerroon 
changing the art_order fixes the cover art gather, yes

**Comment by troycarpenter** [comment] 2022-04-08 15:41
I think a big takeaway here is that handling for album art and artist art should be separated and each have their own set of configuration values.  I've not been having a problem with album art, but artist art has been a pain in my side and slowed my adoption of Ampache for my users.

**Comment by gerroon** [comment] 2022-04-25 05:48
> @gerroon changing the art_order fixes the cover art gather, yes

Ok I did that , some albums have covers now but majority of them are still missing covers after I did "gather art" :(

**Comment by lusum** [comment] 2022-04-25 10:45
> (log.lib) -> [Runtime Error] Invalid argument supplied for foreach() in file /media/var/www/ampache/src/Repository/Model/Album.php(600)

This is not important, i have lot of these errors and they are not related.

**Comment by PsyZeus** [comment] 2022-04-25 10:55
try to change the default upload size

; Maximal upload size
; Specify the maximal allowed upload size for images, in bytes.
; DEFAULT: 1048576
;max_upload_size = 1048576

**Comment by gerroon** [comment] 2022-04-25 18:42
> try to change the default upload size
> 
> ; Maximal upload size ; Specify the maximal allowed upload size for images, in bytes. ; DEFAULT: 1048576 ;max_upload_size = 1048576

Thanks, that seems to help, added couple more covers but majority of my albums are still missing covers :(

**Comment by gerroon** [comment] 2022-04-25 20:47
Here is another example, as you can see there are cover art there, but no cover art in Ampache for this particular album


![chrome_Buk95XkMjk](https://user-images.githubusercontent.com/8519469/165172124-62d689a3-147e-46fa-b8c0-04a0bf4e348d.jpg)

**Comment by mitchray** [comment] 2022-04-26 00:10
Can you post the PHP Settings and Current Configuration from the Ampache Debug page? (/admin/system.php?action=show_debug)

**Comment by lusum** [comment] 2022-04-26 16:18
Ok, i have done a lot of debug.
I have found a problem. The art_order matters cause lastfm plugin return 6 ( for me mostly empty ) images, but 

https://github.com/ampache/ampache/blob/fa7a516f2cc1e2e9e1daf8f5be54d54a8d79905a/src/Module/Art/Collector/ArtCollector.php#L42

the limit is 5, so after the fifth image, the remaining are discarded. So one possible test is to raise this limit. Putting folder first is important cause it is the first image in the array

**Comment by lusum** [comment] 2022-04-26 16:28
> > (log.lib) -> [Runtime Error] Invalid argument supplied for foreach() in file /media/var/www/ampache/src/Repository/Model/Album.php(600)
> 
> This is not important, i have lot of these errors and they are not related.

Btw i have a possible fix for this problem:

https://github.com/ampache/ampache/blob/fa7a516f2cc1e2e9e1daf8f5be54d54a8d79905a/src/Repository/Model/Album.php#L600-L602


>             if(!empty($data)) {
>                       foreach ($data as $key => $value) {
>                               $this->$key = $value;
>                       }
>               }

**Comment by mitchray** [comment] 2022-05-01 02:44
Good find @lusum, good for a temporary fix until the root last.fm issue is addressed, which I'm going to look into when I get a moment

https://github.com/ampache/ampache/issues/2268

**Closed** 2022-05-02 10:36 UTC
