### ISSUE TITLE
3.8.5 Subsonic Catalog does throws errors

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1666] opened 2018-02-06 19:41 UTC
Hi

I had a previous similar bug so I am going to copy paste some of that here since everything about the past setup is exactly the same

3.8.5 does not work for me meaning that it throws some errors, it grabs some albums but they neither playable nor any album art is displayed.

I add the subsonic catalog and use http://192.168.2.116:8080 as the url and enter my creds. The Ampache server and the Airsonic server are on the same local network.

2018-02-06 13:11:56 [ampache] (PHP) -> [Runtime Error] opendir(http://192.168.2.116:8080/rest): failed to open dir: not implemented in file /var/www/ampache-3.8.5/lib/class/art.class.php(1310)
2018-02-06 13:11:56 [xxxxx] (folder_art) -> Error: Unable to open http://192.168.2.116:8080/rest for album art read

I have no albums listed (if I wait long enough it adds couple albums), songs, and it also throws reconnection errors in the interface , not in the logs.
"ERROR: Error: Unable to open http://192.168.2.116:8080/rest"

And this
(Art) -> Error getting art: cURL error 6: name lookup timed out

When I press "update" it says "Catalog verify done 0 f 0 updated"

Paste from previous bug (with system details etc) https://github.com/ampache/ampache/issues/1621
```

""Server sent events connection error. Re-connection"

Airsonic is running on http://127.0.0.1:8080/airsonic so this is the url I put in the field along with my airsonic creds.

There is nothing printing in the log at all regarding the issue, in fact no lines had been printed since adding the remote repo

I am not sure if there is an issue with api or a hiding bug.

I am using
ampache 3.8.5 develop
Debian 7.1 x32
ffmpeg 1.0.10
Apache 2.2.22
Php 5.6.31
Mysql 14.14

My url is
http://xx.xx.xx.xx/ampache-dev

Airsonic
http://192.168.2.116:8080

CONFIG
https://paste.debian.net/hidden/ec5a8be2/

PHP
https://paste.debian.net/hidden/08861a8e/

AIRSONIC
https://github.com/airsonic/airsonic"

```

**Comment by wagnered** [comment] 2018-02-06 20:04
@gerroon 

Airsonic is a Subsonic type music streamer. It is not a catalog. Ampache can access a Subsonic (remote) catalog. It can also simulate the Subsonic music streamer with it's Subsonic API.  Ampache's Subsonic API cannot access another Subsonic music streamer.

To use ampache as a Subsonic type Music/Video streamer, it is necessary to create a **local** catalog on the Ampache server.

**Comment by gerroon** [comment] 2018-02-06 20:08
I think I am not expressing myself well. I am not talking about emulating a Subsonic server. I am talking about adding Subsonic catalog as a catalog in Ampache.

**Comment by wagnered** [comment] 2018-02-06 20:32
@gerroon 

> THe reason I call it catalog because that is where I add the Subsonic catalog, under "add catalog"

So let me try to get a better understanding of your issue:

So are you telling me that you created a "local" type catalog and named it "Subsonic"?  Or did you enable the Subsonic (remote) catalog on the Modules->Modules->Catalog Modules page then select Catalog Type of "Subsonic" when the catalog was created?

Because you are confusing the issue by mentioning the Airsonic Media server which has nothing to do with catalogs on Ampache, Subsonic remote or local. what I need to ask is: Exactly what are you trying to do?

If you are trying to access the Airsonic Media server through an IOS or Android client, VIA Ampache's Subsonic API, it cannot be done. It would also be pointless as the Airsonic Media server can be accessed directly with Subsonic clients.

**Comment by gerroon** [comment] 2018-02-06 20:54
:)

I am adding Subsonic (remote) catalog under "add catalog". I am not adding "local" catalog.

Here is the path  follow.

Catalogs->Add Catalog -> Subsonic  (remote catalog subsonic enabled in the catalog modules)

By doing so I am wanting to make my Subsonic database accessible by the Ampache server. No different adding my local music files except this is a subsonic url. 

The reason I mention Airsonic because Airsonic is a Subsonic fork therefore Api compatible (mostly). And the url I endter in the catalog url is the Airsonic'sinstallation url.


Please forget about accessing subsonic airsonic etc.

**Comment by wagnered** [comment] 2018-02-06 21:54
@gerroon 

I started my Subsonic media server to see if I can create a Subsonic  remote  catalog for it. It looks like there is a problem with the logic. Evidently, the Subsonic catalog is very old and needs updating.

I think you are the first user of the Subsonic remote catalog in a long time. Thank you for bringing it to my attention.

**Comment by gerroon** [comment] 2018-02-06 22:36
@wagnered 

Thanks for your patience and taking a look at it.

cheers

**Comment by wagnered** [comment] 2018-02-07 00:53
@gerroon 

OK I just commited (#232c5b) the changes to update the Subsonic catalog module. The fix appears in version 3.8.6-develop. Not sure when it will be released.

I do remember working on the Subsonic catalog awhile back because someone wanted to have the artist info added to the catalog.  It was an easy enhancement and the catalog did work back then.

**Comment by gerroon** [comment] 2018-02-07 01:01
@wagnered 

Thanks for the fix.  I will try the dev version when I can

**Comment by gerroon** [comment] 2018-02-21 21:16
@wagnered 

Do you have any plans to make a release soonish?

thanks

**Comment by wagnered** [comment] 2018-02-22 05:57
@gerroon 

Sorry to say, I decided to recheck the Subsonic catalog and discovered some problems.

Not sure how long it will take to fix the problem{s};

The Ampache's art class wasn't designed to use a "URL" as a folder path, so the cover-art cannot not be retrieved from the Soundcloud database. The artwork will have to be searched for from lastFM, google, or other which can be set in ampache.cfg.php.

**Comment by gerroon** [comment] 2018-02-22 17:17
@wagnered 

Thanks for the update. It is what it is I guess. :)

cheers

**Comment by wagnered** [comment] 2018-02-28 20:21
@gerroon 

Ampache-3.8.6 has just been released.  Please follow the directions for upgrading from release in the Ampache Wiki.

**Comment by gerroon** [comment] 2018-02-28 22:01
Hi

Thanks for the update. Does it mean that it has the Subsonic fix or?

**Comment by wagnered** [comment] 2018-02-28 22:16
I think so. Go to The [Ampache Release page](https://github.com/ampache/ampache/releases) to see the major fixes. There were also a lot of small fixes that I didn't keep track of.

**Comment by gerroon** [comment] 2018-02-28 22:29
Ok I just upgraded and added my Airsonic but nothing is showing up, no songs, no images etc.

Did the url changed? 

This is my airsonic url that I put in the subsonic url : http://192.168.2.116:8080

**Comment by wagnered** [comment] 2018-02-28 22:54
The zip package is built from the functioning Ampache-develop. I will check the zip to see if anything is missing., but if you got far enough to set up a Subsonic remote catalog, I think the package is intact.

Also, what is your directory structure? I have the folder structure /Music->Artist->albums.  When I imported them into the Subsonic Server, I set the Folder to /Music.

I also pulled the release until I find out what's going on.

**Comment by gerroon** [comment] 2018-02-28 23:01
My folder structure is generally like yours but I also have unorganized stuff so it is a bit of mixed. 

Bear in mind that my library works and plays fine (including images) in Airsonic.

In added couple of lines of log after my reply.  Please see those if you have not yet. 

Also what kind of subsonic url do you provide in Ampache? I just want to make sure I am using the same thing.

**Comment by wagnered** [comment] 2018-03-01 00:59
The zip package is built from the functioning Ampache-develop. I will check the zip to see if anything is missing., but if you got far enough to set up a Subsonic remote catalog, I think the package is intact.

Also, what is your directory structure? I have the folder structure /Music->Artist->albums.  When I imported them into the Subsonic Server, I set the Folder to /Music.

I also pulled the release until I find out what's going on.

**Comment by wagnered** [comment] 2018-03-01 06:20
It seems to be working now....

Subsonic advises that it expects the folder pattern to be "artist/album/song".  I've tested it to "artist/album/disk#/song".

To quote Subsonic:
> It does, however, also read the tags for presentation and search purposes.)

**Comment by gerroon** [comment] 2018-03-01 20:06
@wagnered 
It still does not work for me :( I do not want to waste your time but I have no idea. This used to work before exceptt that we had no covers. Now it does not even grab anything from the subsonic instance.
```

2018-03-01 14:02:44 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:24 -0600 extension length 10000 
2018-03-01 14:02:44 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:02:45 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:25 -0600 extension length 10000 
2018-03-01 14:02:45 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:02:45 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:02:45 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:02:51 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:31 -0600 extension length 10000 
2018-03-01 14:02:51 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:31 -0600 extension length 10000 
2018-03-01 14:02:51 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:02:51 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:02:51 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:02:51 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:02:55 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:35 -0600 extension length 10000 
2018-03-01 14:02:55 [MYUSER] (ajax.server.php) -> Called for page: {index} 
2018-03-01 14:03:02 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:42 -0600 extension length 10000 
2018-03-01 14:03:02 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:02 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:42 -0600 extension length 10000 
2018-03-01 14:03:02 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:03:02 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:03:02 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:13 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:53 -0600 extension length 10000 
2018-03-01 14:03:13 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:13 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:49:53 -0600 extension length 10000 
2018-03-01 14:03:13 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:03:13 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:03:13 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:24 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:50:04 -0600 extension length 10000 
2018-03-01 14:03:24 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:24 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:50:04 -0600 extension length 10000 
2018-03-01 14:03:24 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:03:24 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:03:24 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:35 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:50:15 -0600 extension length 10000 
2018-03-01 14:03:35 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:35 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:50:15 -0600 extension length 10000 
2018-03-01 14:03:35 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:03:35 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:03:35 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:46 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:50:26 -0600 extension length 10000 
2018-03-01 14:03:46 [MYUSER] (subsonic_catalog) -> Updating remote catalog... 
2018-03-01 14:03:46 [MYUSER] (session) -> man91jvcj1tft004ahcnojnbl7 has been extended to Thu, 01 Mar 2018 16:50:26 -0600 extension length 10000 
2018-03-01 14:03:46 [MYUSER] (clean) -> Starting on Airsonic_BOX 
2018-03-01 14:03:46 [MYUSER] (clean) -> clean finished, 0 removed from Airsonic_BOX 
2018-03-01 14:03:46 [MYUSER] (subsonic_catalog) -> Updating remote catalog..

```

**Comment by wagnered** [comment] 2018-03-01 20:39
I just checked the code I used to package and upload the zip file and it still works.

Lets go back to the beginning..
in the first comment above you wrote (from #1621 ):
>Airsonic is running on http://127.0.0.1:8080/airsonic so this is the url I put in the field

Also in the first comment  you wrote:

> I add the subsonic catalog and use http://192.168.2.116:8080 as the url and enter my creds.

I'm confused because 127.0.0.1 (localhost) cannot be contacted by a network ip address. It is a completely separate interface isolated from the network/internet.  Please clarify.

**Comment by gerroon** [comment] 2018-03-01 21:12
Hi

I am not using those anymore. I changed that stuff a bit.

My subsonic runs on  (I put this url in Ampache foir Subsonic catalog)
http://192.168.2.106:8080

The ampache runs on
http://192.168.2.107


Airsonic_BOX	http://192.168.2.106:8080	Never	Never	01/03/2018

**Comment by wagnered** [comment] 2018-03-02 01:59
@gerroon 

I decided to install Airsonic and I've come to the conclusion that Artronics doesn't and cannot conform to Subsonic specs because of the license requirement.  I could not add any files.

I'll take a look and see if it is compatible enough to Subsonic to adapt the code.  The problem is Madsonic may be different from Airsonic and any other Subsonic fork.

No promises though.

**Comment by wagnered** [comment] 2018-03-02 03:01
Airsonic is returning an empty album list.

I submitted an issue with Airsonic questioning them on the problem.

**Comment by gerroon** [comment] 2018-03-02 05:02
@wagnered 

You are a wonderful being. I am literally sorry for all these troubles!  Thanks for all the efforts, not sure what else I can spare here to make it easier for you

thanks again.

**Comment by wagnered** [comment] 2018-03-02 06:42
Bad news :smiling_imp: 

I changed the folder path and added a few (7) albums to that path in Airsonic.  After scanning the folder path, It displayed the Artists on the sidebar.  The first path with 1,374 albums didn't do that.

Anyway, I was able to successfully create a Subsonic remote catalog on the Airsonic server with those 7 albums.

I think I also improved the efficiency of the update function for the subsonic catalog.  I uploaded a new zip package to the release page.  So if you also have a large number of albums, I suggest trying it on a path with a small sample as I did.

**Comment by gerroon** [comment] 2018-03-02 16:11
Thanks I will give it a try

**Comment by gerroon** [comment] 2018-03-02 23:39
@wagnered 

Ok, it works! At least there is some progress. 

I used the urls I provided above. I am not using some test Airsonic database, it is my actual lib. 

It connected and grabbed some albums but it grabbed only 11 albums out of thousands and it does not seem to want to grab more from AS lib.


"Update", "Add" etc does not seem to change that. It only does 11 albums at the moment and it acually streams to the web player. So this is quite a progress to me :)

**Comment by wagnered** [comment] 2018-03-03 01:06
OK, I think I need a vacation :frowning_face:  Although It's good to know that I'm making some progress.

> Did you put a hard limit for testing?

 Yes, I had problems just populating the Airsonic server with a large number of songs. I had to try with a small number to see what the problem was.  Now I'm populating the Airsonic database by adding a dozen artists at a time. So far it is successful with a  total of 15,061 songs

Hopefully, your albums page shows artwork.

I may have to revert the catalog update function to get all the albums.

**Comment by gerroon** [comment] 2018-03-03 01:27
Yeah I forgot to mention that it actually grabs album art too. Sorry about that . So we had multiple progresses.

I am sorry that this issue has been sucking life out of you!

**Comment by wagnered** [comment] 2018-03-03 03:04
@gerroon 

Sorry, I didn't mean to point fingers at you. There are at lease three other issues I have been working on.

I enjoy solving problems.  By saying I need a vacation I just meant that I would like to get back to doing some more development work.

**Comment by gerroon** [comment] 2018-03-03 03:07
Well I am glad that we have you as the Ampache dev. You have been bringing this project back to life, that is for sure. Thanks again

**Comment by wagnered** [comment] 2018-03-04 03:35
OK, give the latest zip package another try.  The Ampache Subsonic  catalog shows 23 pages of albums. The artist/album/song count in the Subsonic server  and the Ampache Subsonic remote catalog do not agree. Maybe it's a php-timeout problem. 

If you try the latest, please let me know if your results are different.

I have to check to see if what's going on.

**Comment by gerroon** [comment] 2018-03-04 04:30
Thanks for the update. I started the process, it looks like it will take a while until i know what the situation is. It started adding the albums, it was 11 originally now I see 50.

I will update this bug

thanks

**Comment by gerroon** [comment] 2018-03-04 05:30
It got stuck at 74 albums. I will retry it.

These are the only lines I see at the end of the log, not sure if it is relevant


2018-03-03 22:31:47 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24211-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:31:47 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24211-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:31:49 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24212-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:31:49 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24212-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:31:49 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24212-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:31:49 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24212-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:32:00 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24225-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:32:00 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24225-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:32:00 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24225-artist-0-2250' for key 'unique_tag_map'"] 
2018-03-03 22:32:00 [XXXX] (Dba) -> Error: ["23000",1062,"Duplicate entry '24225-artist-0-2250' for key 'unique_tag_map'"]

**Comment by gerroon** [comment] 2018-03-04 05:36
Here is another error when I tried to add a new subsonic catalog

ERROR: AmpacheApi::parse_response was unable to parse XML document. Error 23 line 25: EntityRef: expecting ';'

**Comment by gerroon** [comment] 2018-03-04 05:40
another curious thing,

I dop not have beets enabled

 (autoload) -> 'Beets\Catalog' not found!**

Not sure if it effects the outcome, but it seems to print this everytime I add and update

**Comment by gerroon** [comment] 2018-03-04 05:44
Ok finally I am at complete lost here :(

I deleted the airsonic catalog that I reported that it got stuck at 74 albums (which was created in the version from yesterday) and cleaned all and recreated the exact same subsonic catalog. I see no albums whatsoever.

This behaves just randomly :(

**Comment by gerroon** [comment] 2018-03-04 05:51
On top of it, my airsonic library had 0 albums :( NO idea what is going on here. Would external database request wipe the Airsonic database? it should not, 

Anayw I am at loss here. I am going to recreate the Airsonic lib and recreate the Ampache access. Lets see how that goes.

**Comment by wagnered** [comment] 2018-03-04 06:18
> On top of it, my airsonic library had 0 albums

I had that problem until I added a few artists/albums at a time to the Airsonic folder path as described earlier.  I was discussing this with @jooola on Airsonic/Airsonic.  I closed the issued because I was able to slowly populate the Airsonic database and get a list of artists on the sidebar.
I reopened it: #706 on the airsonic issues list if you want to pursue it.

I had problems getting a large list of artists on an android client until I doubled the php.ini switch "default_socket_timeout".   I just remembered that Airsonic is built on Java.

**Comment by wagnered** [comment] 2018-03-04 18:33
@gerroon 

After several retries of removing/reinstalling Airsonic, it finally automatically scanned/inserted all the artists/albums into its database.

> Would external database request wipe the Airsonic database? it should not,

Right, it won't.  Remember that Airsonic was forked from a "pre-proprietory" version of Subsonic.  I'm sure Subsonic has gone through many improvements with their Java engine that Airsonic could no longer duplicate.

Sorry  but it appears that the problem you are having is a problem with Airsonic. I suggest you consult  @jooola on Airsonic/Airsonic to work out the problem with your Airsonic streaming server. I will continue working on the Ampache Subsonic Remote catalog problem with the Subsonic server as that was the primary intent of incorporating the catalog and I have no problems with it

By the way, do you really need to have a Subsonic type server to hold your collection of albums? .

Now I have to determine what artists/albums are missing from the Ampache Subsonic catalog that are in the long list on the Subsonic server.  :confused:

**Comment by gerroon** [comment] 2018-03-04 23:43
Ok I recreated it all and  I have the same conclusion as yours. The album numbers do not match, not even close. It has stopped at 8424 albums so I assume that was what it could get. And it is missing about 1500 albums.


Airsonic : 9910 albums
Ampache: 8424 albums

@wagnered the reason I like the subsonic option because then I can have only main server to worry about especially when dealing with likes, startter albums, orgabizing etc. I was managing both servers  at the same time but it gets tedious to be honest :( to repeat the same things for the both servers. 

The main reason I use Airsonic is because it is java and runs without a web server, I like Ampache because it impersonates subsonic server butr my favorite feature is local Mpd server support. Mpd is by far the best way to listen music in my view but it byself does not have much "library" features, but as a player and a streamer I find it to be splendid. 

So I am hoping that the subsonic catalog actually creates this bridge between Subsonic and ampache but if it all fail, I say Ampache would be my choice of server from now on given that I can use it with Dsub. The only thing I personally miss from Subsonic api support is folders in clients, so we do not see any folders in the clients.

Also Subsonic clones support more mobile clients, unfortunately AMpache clients are a bit primitive, but again Subsonic api support eases that pain a bit.

**Comment by gerroon** [comment] 2018-03-05 03:17
Here is another twist in the saga.

I added and removed some albums from Airsonic, now I have 9918 albums on Airsonic (vs 9910) and I added and updated Ampache 's Subsonic catalog. After a while it still shows (8424).

**Comment by gerroon** [comment] 2018-03-05 04:31
I also lost album while trying to replace the cover. Because it was missing vover (but not in Airsonic)< It disappeared from Ampache. I believe this is related


[ampache] (PHP) -> [Runtime Error] implode(): Invalid arguments passed in file /var/www/ampache-3.8.6/lib/class/catalog.class.php(1661)

**Comment by wagnered** [comment] 2018-03-05 04:39
@gerroon,

The log should tell you when there is a problem importing an image and why.

Set "album_art_max_width" and "album_art_max_height" to a larger value in ampache.cfg.php.  And maybe "max_upload_size" should be increased.

**Comment by wagnered** [comment] 2018-03-05 05:22
I'm becoming more convinced that the problem is with php timing out.  Not fully there yet but doing some experiments to try to learn more.

**Comment by gerroon** [comment] 2018-03-05 16:16
I set both of those options to 4096

**Comment by wagnered** [comment] 2018-03-05 18:05
I also keep increasing two php.ini switches: max_input_time and max_execution_time to 300 at which the subsonic catalog creation reached a limit.

There is still a difference between what Subsonic server is reporting and what Ampache shows in the statics.  I am going to set up the Subsonic server to use Mysql. Hopefully I'll be able to make a comparison between them.  The Subsonic server's default database uses a different collation which makes the contents more difficult to compare.

**Comment by gerroon** [comment] 2018-03-05 18:47
thanks for the update. I am fiddling wiht here here as well.

**Comment by wagnered** [comment] 2018-03-05 20:11
Well, the directions for connecting Subsonic server to MySQL don't work or arer nadequate. I have to wait until someone in the forum  can assist.

**Comment by gerroon** [comment] 2018-03-05 20:31
Anything here?
https://airsonic.github.io/docs/database/

**Comment by wagnered** [comment] 2018-03-05 22:11
Nope nothing on MySQL driver.

**Comment by wagnered** [comment] 2018-03-05 23:57
As long as max_input_time and max_execution_time in php.ini are set high enough for the script to finish, It should get all the songs/albums that the Subsonic API has available.

I just tested the Subsonic remote catalog on a folder path with only 22 artists.

Subsonic server index page indicates 22 artists,   Ampache shows 24
Subsonic "About" page shows 27 artists.

Subsonic server "About" page shows 74 albums, Ampache shows 74.

Subsonic server "About" page shows 886 songs, Ampache shows 886.

So, I think that any discrepancies between your airsonic server and the Ampache catalog is probably the fault of the Airsonic server, or maybe the metadata in your music files.  :relieved:

> The main reason I use Airsonic is because it is java and runs without a web server,

By the way, even the stand-alone version has a built-in Tomcat server. At an any rate, The Subsonic server stand-alone does. :smile: 

If you have any requests for enhancements, please start a new  issue for each one.

Thanks...

**Comment by gerroon** [comment] 2018-03-06 01:46
Thanks for looking into this and investigating it. I will retry with those settings.

**Comment by mitchray** [comment] 2021-04-30 04:21
Closing due to inactivity, reopen if this is still an issue in latest version

**Closed by mitchray** 2021-04-30 04:21 UTC
Labels: subsonic
