### ISSUE TITLE
Crazy high cpu usage with web play

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#542] opened 2014-10-29 05:27 UTC
Hi

I love the new work on this. Thanks for the hard work.

When I try to play on my laptop using web play, I see that both iceweasel and chromium go nuts with the cpu usage so that is probably a not so sexy for the laptop users. I am wondering if this is a Linux thing, or ampache thing or something else?

thanks

**Comment by Afterster** [comment] 2015-01-22 07:54
Is this a real issue? I cannot reproduce it.
Are you sure Visualizer is not enabled? Could you try any other jPlayer example http://jplayer.org/latest/demos/) to see if it is jPlayer related?

**Comment by ainola** [comment] 2015-01-23 09:27
Hm, I seem to have mixed this bug report with another one. Or I've been delusional and thought this was concerning something else. In any case, I don't have a high CPU usage: If you view the linked video it shows that it's quite acceptable usage, especially since these are .flac files that I'm playing. Do note that idle, Iceweasel is currently using ~10% CPU so subtracting that value from the monitor would probably be more realistic. 

http://ainola.sdf.org/usage.webm

My issues come from the pretty badly broken playback - this behavior only affects .flac files (Aurora?). All the lossy filetypes play fine for me. This occurs on FF/Chromium/Epiphany on Debian 8/Ubuntu 14.04/Arch so I'd be inclined to believe that it's a buggy .js library. So this is probably likely to be an upstream issue... although it's very bizarre that it's apparently completely breaking playback after some basic computer usage. That's a new one for me.

I think I had attributed this issue to the fact that it did use to spike up in CPU with .flac decoding for me and I attributed the choppy playback to that. It appears that this isn't the case.

I'm not entirely sure what to pinpoint and attribute to upstream and what to report as a bug. As it stands, this bug report doesn't appear to have any real focus, just a generalization that there's apparently a problem (is high CPU usage still a problem, @gerroon?)

**Comment by ainola** [comment] 2015-01-23 09:35
I forgot to mention, the demo page you linked works just fine - However, this demo page for .flac has the same behavior as in my video:

http://audiocogs.org/codecs/flac/ as linked as demos from https://github.com/audiocogs/aurora.js

**Comment by Afterster** [comment] 2015-01-23 11:09
About your issue @ainola, it's indeed an Aurora problem that I noticed on my side too. Let's hope for a fix ;)

**Comment by ainola** [comment] 2015-01-23 19:13
Ah, the reason I couldn't find the Ampache bug report is because it wasn't in Ampache - here's the bug for Auroroa:

**Comment by Afterster** [comment] 2015-01-23 21:26
Yes let's watch Aurora project evolution then :)
I'm going to close this as I believe the original cpu issue is not a real one.
Anyone feel free to comment with a note to reproduce it to reopen this issue.

**Closed by Afterster** 2015-01-23 21:26 UTC
Labels: bug

**Comment by sideeffffect** [comment] 2015-08-20 02:37
Hi, my Ampache installation is probably suffering from the same issue as @gerroon describes: high CPU usage even for mp3 playback
is there a way to know which backend (html5, flash, aurora.js) I am actually using? and maybe even why the ones with higher priority failed?
(using chrome 44)

**Comment by sideeffffect** [comment] 2015-08-20 02:43
oh, quick research results:
high cpu usage happens only with mp3 files when the tab is in focus. things seem to be ok when the tab is in background or when a radio station is played.
the difference seems to be *the blue playbar at the bottom being displayed* -- could that be the case of a stupidly high cpu usage?
