### ISSUE TITLE
After refreshing the page, web player will never show again

### ISSUE THREAD

**Issue by Tea23** [ampache/ampache#1238] opened 2016-06-05 21:01 UTC
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version:  nginx-mainline 1.11.1
 * Server operating system: Arch Linux
 * Client operating system: Arch Linux
 * Client type:
   - [x] Web
   - [ ] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
# Settings
Default ampache config immediately after installation.

# Description
After successfully playing a FLAC file and then refreshing the page or opening it again in another tab (after closing the original), the web player will never reappear. Also happens in latest git. Logging out, logging back in, clearing cookies, changing session key etc does not help. Clicking the play button briefly displays 'loading' in the corner, but nothing happens.

Deleting the config file and dropping the database and subsequently reinstalling Ampache is seemingly the only remedy.

# Logs
Log after attempting to replay media when the web player won't return:

```
2016-06-05 21:00:34 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:34 +0000 extension length 3600 
2016-06-05 21:00:34 [admin] (session) -> Session created: 11a95c0e433adac22d5ce21104d7b050 
2016-06-05 21:00:34 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:34 +0000 extension length 3600 
2016-06-05 21:00:34 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:34 +0000 extension length 3600 
2016-06-05 21:00:34 [admin] (ajax.server.php) -> Called for page: {index} 
2016-06-05 21:00:34 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:34 +0000 extension length 3600 
2016-06-05 21:00:34 [admin] (ajax.server.php) -> Called for page: {index} 
2016-06-05 21:00:36 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:36 +0000 extension length 3600 
2016-06-05 21:00:36 [admin] (ajax.server.php) -> Called for page: {stream} 
2016-06-05 21:00:36 [admin] (stream.ajax.php) -> Called for action {directplay} 
2016-06-05 21:00:36 [admin] (stream.ajax.php) -> Play type {} 
2016-06-05 21:00:36 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:36 +0000 extension length 3600 
2016-06-05 21:00:36 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:36 +0000 extension length 3600 
2016-06-05 21:00:36 [admin] (stream.php) -> Asked for {play_item}. 
2016-06-05 21:00:36 [admin] (stream.php) -> Stream Type: web_player Media IDs: [{"object_type":"song","object_id":"1"}] 
2016-06-05 21:00:36 [admin] (session) -> Session created: ce8394834ac0289b958884e9c88187dd 
2016-06-05 21:00:36 [admin] (stream_playlist.class.php) -> Adding url {{"properties":["url","title","author","time","info_url","image_url","album","type","codec","track_num"]}}... 
2016-06-05 21:00:36 [admin] (stream_playlist) -> Generating a {web_player} object... 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Types {{"real":"flac","player":"flac"}} 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Return get_media_js_param {{"title":"Prologue \/ I Know Where You Live","artist":"Alice Cooper","artist_id":"1","album_id":"1","replaygain_track_gain":"0.000000","replaygain_track_peak":"0.000000","replaygain_album_gain":"0.000000","replaygain_album_peak":"0.000000","media_id":"1","media_type":"song","filetype":"flac","url":"https:\/\/media.warhaggis.com:443\/play\/index.php?ssid=ce8394834ac0289b958884e9c88187dd&type=song&oid=1&uid=1&name=Alice%20Cooper%20-%20Prologue%20-%20I%20Know%20Where%20You%20Live.flac","poster":"https:\/\/media.warhaggis.com\/image.php?object_id=1&object_type=album&auth=ce8394834ac0289b958884e9c88187dd&thumb=3&name=art.png"}} 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Types {{"real":"flac","player":"flac"}} 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Return get_media_js_param {{"title":"Prologue \/ I Know Where You Live","artist":"Alice Cooper","artist_id":"1","album_id":"1","replaygain_track_gain":"0.000000","replaygain_track_peak":"0.000000","replaygain_album_gain":"0.000000","replaygain_album_peak":"0.000000","media_id":"1","media_type":"song","filetype":"flac","url":"https:\/\/media.warhaggis.com:443\/play\/index.php?ssid=ce8394834ac0289b958884e9c88187dd&type=song&oid=1&uid=1&name=Alice%20Cooper%20-%20Prologue%20-%20I%20Know%20Where%20You%20Live.flac","poster":"https:\/\/media.warhaggis.com\/image.php?object_id=1&object_type=album&auth=ce8394834ac0289b958884e9c88187dd&thumb=3&name=art.png"}} 
2016-06-05 21:00:36 [admin] (session) -> 2jvt8dlbeot88v20d7otrntjd6 has been extended to Sun, 05 Jun 2016 22:00:36 +0000 extension length 3600 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Types {{"real":"flac","player":"flac"}} 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Types {{"real":"flac","player":"flac"}} 
2016-06-05 21:00:36 [admin] (webplayer.class.php) -> Return get_media_js_param {{"title":"Prologue \/ I Know Where You Live","artist":"Alice Cooper","artist_id":"1","album_id":"1","replaygain_track_gain":"0.000000","replaygain_track_peak":"0.000000","replaygain_album_gain":"0.000000","replaygain_album_peak":"0.000000","media_id":"1","media_type":"song","filetype":"flac","url":"https:\/\/media.warhaggis.com:443\/play\/index.php?ssid=ce8394834ac0289b958884e9c88187dd&type=song&oid=1&uid=1&name=Alice%20Cooper%20-%20Prologue%20-%20I%20Know%20Where%20You%20Live.flac","poster":"https:\/\/media.warhaggis.com\/image.php?object_id=1&object_type=album&auth=ce8394834ac0289b958884e9c88187dd&thumb=3&name=art.png"}} 
```

**Comment by Tea23** [comment] 2016-06-05 21:21
Done a bit more probing. After a reinstall, I can open the web player as much as I want so long as I click the little tiny X on the player, however it still only applies to that session. As soon as I log out and log back in, the player will be hidden forever again and I have to reinstall.

**Comment by Phyks** [comment] 2016-06-06 14:13
Do you have any error in the web console of your browser? There does not seem to be any error in the log file you provided.

**Comment by Tea23** [comment] 2016-06-06 18:32
No, there's no error in the web console. And you're correct there's none in the log. As far as everything is concerned, nothing is going wrong.

**Comment by Phyks** [comment] 2016-06-07 09:37
Really difficult to help you debug without errors :/

Did you confirm it is not coming from an addon of your browser (test with a browser without any extension) or your browser / configuration on client side?

**Comment by Tea23** [comment] 2016-06-07 19:18
Yeah, I tested with a freshly installed Chrome - no plugins, no settings changed from default. Exactly the same behaviour.

**Comment by Phyks** [comment] 2016-06-07 22:32
Erf… Do you think it might be possible to give a temporary access to your instance (with a limited account that could replicate the issue), in PM, so that I could see if I can find any extra idea?

**Comment by mh00h** [comment] 2016-06-13 01:04
I am also having issues with this. If you toggle Preferences > Interface > Ajax Page Load > Disable, then it appears to work appropriately (but with a popup window). Enabling ajax page loading causes the issue to reappear. Phyks- if you wanted to work together on this I would be willing to collaborate on debugging this further.

**Comment by Phyks** [comment] 2016-06-13 06:13
@mh00h sure, and even more since you managed to reproduce it.

Could you double check the above checks (still here without any extensions enabled, no errors in the web console, etc)?

Also, I do not know how familiar you are with web development, but could you check in the network tab that the subsequent calls to ajax.server.php, stream.php and web_player_embedded.php are successful (200) with an actual content?

Do you have this issue with panels other than the webplayer?

**Comment by Phyks** [comment] 2016-06-22 23:15
After having a look at his issue with @mh00h, this appears to be due to a 500 error in the "recently played" section of the index page.

When not using the AJAX loading, this does not have any impact on webplayer.

When using the AJAX loading, every page is loaded from index.php, which is truncated due to this 500 error.

I am waiting for more logs to state where the error comes from.


By the way, @Tea23 do you have any news on your issue? Could it be the same thing happening?

**Comment by mh00h** [comment] 2016-06-22 23:17
This issue appears in Firefox, but not in Chrome.

**Comment by Phyks** [comment] 2016-06-22 23:20
@mh00h on the account you set up for me, I have this exact same issue (and 500 internal server error) in Firefox and in Chromium, which is expected due to the nature of the error (server side).

If you see a different behavior between Firefox and Chrome, I do not know why. Maybe cache is in play, or you don't access the exact same URL from both of them. Of course, if you go to `/browse.php?action=song` (and bypass AJAX loading) you are not affected by this server error, and you can play music.

**Comment by Phyks** [comment] 2016-06-27 06:44
It does seem a lot to be coming from [this bug](https://github.com/ampache/ampache/issue/123) which was [fixed in this PR](https://github.com/ampache/ampache/pull/1239). Waiting for confirmation from @mh00h and I think this issue can be safely closed afterwards.

**Comment by mh00h** [comment] 2016-06-30 04:23
Special thanks to Phyks for helping to debug this. I'm closing this in confirmation.

**Comment by Niols** [comment] 2016-06-30 07:15
Great!
Thanks a lot @mh00h and @Tea23 for all the informations provided!

**Closed by Niols** 2016-06-30 07:15 UTC
Labels: waiting
