### ISSUE TITLE
Docker White screen

### ISSUE THREAD

**Issue by danbuntu** [ampache/ampache#3348] opened 2022-09-11 10:30 UTC
### Describe the bug
When I upgraded to the latest version of ampache:latest (08-09-2022) I got a white screen
I deleted the contianer and I then get the install screens. After the install is complete if takes me to a white screen.

### To reproduce

Create container using the :lastest branch

## Environment

Docker

**Comment by lachlan-00** [comment] 2022-09-12 06:27
I've just installed a new container on latest without issue. Are there logs from the container or something that you can see? if you've had it set up before is there a logfile you can read or error in the apache logs?

**Comment by JRB-Prod** [comment] 2022-09-12 21:30
I have the same problem on the same version (ampache:latest). No errors from the container. I don't have any more info at the moment.

**Comment by TimoHocker** [comment] 2022-09-13 15:02
Having the same issue here, tho I can't find any logs with errors. It asked for the database update first, after completing that the site is just an empty html.
I'm using nginx as reverse proxy and it seems like the proxy doesn't forward the site properly anymore. Running curl on the ampache container directly seems to return a valid site.

**Comment by JRB-Prod** [comment] 2022-09-14 14:32
I'm in the exact same situation as @TimoHocker and curl request to the default page (without /login.php) does indeed return data, but the browsers (Chrome & Firefox) get a 302 to /login.php. This page is empty.

PS For anyone who wants to see the logs: You must first open a bash shell inside the Ampache docker. Then you will find the logs here: /var/log/ampache/ampache.<current_date>.log

**Comment by TimoHocker** [comment] 2022-09-14 15:00
> PS For anyone who wants to see the logs: You must first open a bash shell inside the Ampache docker. Then you will find the logs here: /var/log/ampache/ampache.<current_date>.log

And enable debugging, my instance didn't write any logs without `debug = "true"` in the ampache.cfg.php.

I still can't find the error you mentioned although it complains about not being able to read a value.
Debugging enabled with level 5
```
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Index\ShowAction" for action "show"
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Session) -> Session created: 8e4e456d782ba4d085946a8bc68542ea
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Session) -> Unable to read value from key 0kkn6tplvqvao6cif5nru6ipeh no data found
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Session) -> Writing to 0kkn6tplvqvao6cif5nru6ipeh with expiration 1663170800
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Login\DefaultAction" for action "default"
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Session) -> Unable to read value from key 7mc68ocgj325519b8vnr5a1ma1 no data found
2022-09-14T14:53:20+00:00 [ampache] (/var/www/src/Module/System/Core.php:143) -> filter_has_var(): Argument #1 ($input_type) must be of type int, string given
2022-09-14T14:53:20+00:00 [ampache] (Ampache\Module\System\Session) -> Writing to 7mc68ocgj325519b8vnr5a1ma1 with expiration 1663170800
2022-09-14T14:53:22+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T14:53:22+00:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T14:53:22+00:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Login\DefaultAction" for action "default"
2022-09-14T14:53:22+00:00 [ampache] (Ampache\Module\System\Session) -> Unable to read value from key 7mc68ocgj325519b8vnr5a1ma1 no data found
2022-09-14T14:53:22+00:00 [ampache] (/var/www/src/Module/System/Core.php:143) -> filter_has_var(): Argument #1 ($input_type) must be of type int, string given
2022-09-14T14:53:22+00:00 [ampache] (Ampache\Module\System\Session) -> Writing to 7mc68ocgj325519b8vnr5a1ma1 with expiration 1663170802
```

**Comment by danbuntu** [comment] 2022-09-14 17:31
I'm the same as @TimoHocker in that i'm also behind an Nginx reverse proxy

I'm also seeing the same in the error log:

`2022-09-14T18:29:04+01:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T18:29:04+01:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2022-09-14T18:29:04+01:00 [ampache] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Login\DefaultAction" for action "default"
2022-09-14T18:29:04+01:00 [ampache] (Ampache\Module\System\Session) -> Unable to read value from key ptrfhtq6v1ijlm90hk3l7rinjl no data found
2022-09-14T18:29:04+01:00 [ampache] (/var/www/src/Module/System/Core.php:143) -> filter_has_var(): Argument #1 ($input_type) must be of type int, string given
2022-09-14T18:29:04+01:00 [ampache] (Ampache\Module\System\Session) -> Writing to ptrfhtq6v1ijlm90hk3l7rinjl with expiration 1663180144`

**Comment by linucksrox** [comment] 2022-09-14 23:29
@lachlan-00 You mentioned you can get this running with a new container. I believe the issue here is after upgrading, possibly relating to the schema change. I came from 5.4.1 to 5.5.1 and am experiencing this exact issue as well. Can you please install 5.4.1 and then perform the upgrade to 5.5.1 to test?

**Comment by linucksrox** [comment] 2022-09-14 23:45
This seems to be the culprit: https://github.com/ampache/ampache/commit/d5f7783db50c8be5e36b7ad0839be988001a4696

Sure enough, reverting that line in version 5.5.1 works (albeit temporarily). I haven't tried diving into what the code is trying to accomplish, but I'm happy to send a PR if I can some clarification on what we're trying to do here.

**Comment by lachlan-00** [comment] 2022-09-15 03:37
i'm going to do a new release tonight/tomorrow and this will be included in master/latest docker images

**Comment by manuelfonseca71** [comment] 2022-09-16 08:07
The update did not fix the issue on my side.
Now instead of a blank login.php page, I get a 500 error.
Only have an entry on the ampache log about the database, not an error.
The apache error log shows the following message:
Fri Sep 16 08:02:45.922824 2022] [php:error] [pid 20] [client 192.168.1.63:54934] PHP Parse error:  syntax error, unexpected token "<<", expecting "function" or "const" in /var/www/src/Config/Init/InitializationHandlerConfig.php on line 35

test.php runs fine and reports no errors. There were no configuration changes, other than activating the logs.

Any clue on what might be happening here?

**Comment by TimoHocker** [comment] 2022-09-16 08:36
Mine works again.

**Comment by manuelfonseca71** [comment] 2022-09-16 08:53
Hum... Something might have gone wrong while cooking the docker image.
I get these lines under file mentioned on the error log:
"
final class InitializationHandlerConfig implements InitializationHandlerInterface
{
<<<<<<< HEAD
    private const VERSION        = '5.5.1-develop';
=======
    private const VERSION        = '5.5.1-release';
>>>>>>> f916c4cbe11385ac08d88d8e3a4f62c9a2e10e46
"

**Comment by TimoHocker** [comment] 2022-09-16 09:06
you should try to pull again, my container has that file in a valid form with version 5.5.2-release
```php
final class InitializationHandlerConfig implements InitializationHandlerInterface
{
    private const VERSION        = '5.5.2-release';
    private const CONFIG_VERSION = '62';

```

Image hash 6fec3487eb3
I'm running with tag :5, but latest has the same image

**Comment by manuelfonseca71** [comment] 2022-09-16 09:10
I'm retrieving the image under ampache/ampache:nosql tag, tried it again it has remained the same.
So, perhaps this one was not updated properly.

**Comment by TimoHocker** [comment] 2022-09-16 09:19
can confirm, the nosql image is broken.
In the meantime you could replace that part of the file with the one I sent, assuming there are no other merge conflicts in other files.

**Comment by manuelfonseca71** [comment] 2022-09-16 09:22
No rush, I'm happy to wait for an updated image.
Just wanted to share the findings on my side, it is the only way I have to help a bit.

**Comment by lachlan-00** [comment] 2022-09-21 05:17
sorry, i thought it was just the latest tag. rebuilding nosql now

**Comment by manuelfonseca71** [comment] 2022-09-21 12:14
Image updated, and I can now confirm that the problem is fixed under ampache/ampache:nosql as well.

Thank you!

**Comment by lachlan-00** [comment] 2022-09-22 03:15
sorry for taking so long to notice the error

**Comment by mitchray** [comment] 2023-01-11 09:23
Closing as it appears to be resolved, reopen if its still relevant

**Closed by mitchray** 2023-01-11 09:23 UTC
