### ISSUE TITLE
[BUG] Podcasts catalog update, duplicate entries.

### ISSUE THREAD

**Issue by xekon** [ampache/ampache#2833] opened 2021-03-18 23:17 UTC
### Describe the bug
When the Podcasts catalog is updated, it adds a duplicate entry, I have seen this happen several times now, wanted to make sure it was not a weird one time occurrence.

When it happens there is no way to delete a duplicate in the GUI, so I have been doing it manually via SQL:

```
mysql
use ampache;
select * FROM podcast_episode ORDER BY id DESC LIMIT 1;
DELETE FROM podcast_episode ORDER BY id DESC LIMIT 1;
quit
```

### To reproduce

I have two subscribed Podcasts:
https://feeds.megaphone.fm/darknetdiaries
https://2.5admins.com/feed/podcast

I update the podcasts using a cron job, just like I added to the wiki page here: "Automatic Podcast Catalog Updates" https://github.com/ampache/ampache/wiki/Podcasts

to add it here as well, here is the file:

`cat /etc/cron.d/ampache`

```
#.---------------- minute (0 - 59)
#| .------------- hour (0 - 23)
#| |  .---------- day of month (1 - 31)
#| |  | .------- month (1 - 12) OR jan,feb,mar,apr ...
#| |  | | .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
#| |  | | |
#* *  * * *  user      command
0 1   * * *  www-data  php /var/www/ampache/bin/catalog_update.inc -n podcasts -a -g -i >/dev/null 2>&1
```

### Expected behavior

I expect it to only create one entry for the new episode, but every time it creates two entries for a new episode.

### Screenshots

![2021-03-18_16-04](https://user-images.githubusercontent.com/106644/111708785-b6516880-8803-11eb-8e16-40c4b482ebc4.png)

## Environment

* Ampache version: Ampache 4.4.0-release
* Web server + version: nginx latest
* Server operating system: Ubuntu 20.04.4
* Client operating system: Ubuntu 20.04.4 (Firefox latest)

### Client type

* Web

## Settings

`diff -u /var/www/ampache/config/ampache.cfg.php.dist /var/www/ampache/config/ampache.cfg.php | grep -E "^\+" | grep -v "host" | grep -v "secret" | cut -c 2-`

```
config_version = 46
http_port = "443"
web_path = ""
database_port = ""
database_name = "ampache"
database_username = "www-data"
database_password = ""
database_charset = "utf8mb4"
database_collation = "utf8mb4_unicode_ci"
session_length = "3600"
stream_length = "7200"
remember_length = "604800"
session_name = "ampache"
session_cookielife = "0"
session_cookiesecure = "0"
getid3_tag_order = "id3v2,id3v1,vorbiscomment,quicktime,matroska,ape,asf,avi,mpeg,riff"
additional_genre_delimiters = "[/]{2}|[/|\\|\|,|;]"
licensing = "false"
simple_user_mode = "true"
artist_art_preferred_filename = "artist.jpg"
album_art_min_width = "190"
album_art_min_height = "190"
art_order = "db,folder"
wanted = "false"
channel = "false"
live_stream = "false"
podcast = "true"
debug = "true"
debug_level = "5"
log_filename = "%name.log"
site_charset = "UTF-8"
allow_public_registration = "false"
cookie_disclaimer = "false"
transcode_mp3 = "allowed"
```

## Logs

```
2021-03-16T18:00:03-07:00 [ampache] (Podcast) -> Adding new episode to podcast 13... 
2021-03-16T18:00:03-07:00 [ampache] (Podcast) -> Episode published before 1615856404 (1504267200), skipped 
2021-03-16T18:00:03-07:00 [ampache] (Podcast_Episode) -> Downloading https://www.podtrac.com/pts/redirect.mp3/traffic.megaphone.fm/ADV7707100402.mp3?updated=1615430939 to /media/podcasts/Darknet Diaries/1615878000-87: Guild of the Grumpy Old Hackers-ADV7707100402.mp3 ... 
2021-03-16T18:00:24-07:00 [ampache] (Podcast_Episode) -> Download completed. 
2021-03-16T18:00:24-07:00 [ampache] (vainfo) -> Cleaning id3v2 
2021-03-16T18:00:24-07:00 [ampache] (Podcast_Episode) -> Download completed. 
2021-03-16T18:00:24-07:00 [ampache] (vainfo) -> Cleaning id3v2 
2021-03-16T18:00:24-07:00 [ampache] (Podcast_Episode) -> Downloading https://www.podtrac.com/pts/redirect.mp3/traffic.megaphone.fm/ADV7707100402.mp3?updated=1615430939 to /media/podcasts/Darknet Diaries/1615878000-87: Guild of the Grumpy Old Hackers-ADV7707100402.mp3 ... 
2021-03-16T18:00:35-07:00 [ampache] (Podcast_Episode) -> Download completed. 
2021-03-16T18:00:35-07:00 [ampache] (vainfo) -> Cleaning id3v2
```

**Comment by lachlan-00** [comment] 2021-03-19 03:55
Each new episode and only for these specific podcasts?

One thing we don't do is check against urls, just published dates so there does need to be better episode checking before insert.

When I'm free again I will be able to work on this it should be simple enough. The logic now just assumes a lot without checking.

**Comment by xekon** [comment] 2021-03-19 09:41
so far each and every new episodes. I am not subscribed to any other podcasts, so I am unsure if any other podcasts would do it. I will look for some more tech podcasts to subscribe to in the morning.

Thanks @lachlan-00

**Comment by lachlan-00** [comment] 2021-03-19 12:21
Okay new episodes. That will help. I can set the date back/manually create that event.

I haven't seen it regularly in my subscriptions but I'll make sure to check the logic on adding new episodes asap next week.

**Comment by usox** [comment] 2021-03-21 14:52
Happened to me, too - but after several rounds of refactoring the complete podcast update/retrieval process, I was not able to trigger the bug again. I don't know if this is really urgent issue for @xekon - so maybe, we can defer that to 5.1 which will include a structurcal overhaul of the podcast functions...

**Comment by xekon** [comment] 2021-03-22 17:06
It is certainly an inconvenience because I have to make sure to check daily if there are new episodes and delete the duplicates. I do not know the complications of trying to push a fix now because I am not a developer of Ampache. If there is no sensible way to push a fix now because it would cause problems then there really is no helping it I suppose. Thank you for taking a look into the issue, I really appreciate it.

**Comment by lachlan-00** [comment] 2021-03-23 07:37
still couldn't dupe it, i wonder if there's a setting that i've got that is skipping this. i use 0 for all the download settings do you?
![image](https://user-images.githubusercontent.com/1305249/112110309-6fe27c00-8bfe-11eb-9e4c-5fa2e96f5f9e.png)

Simplest approach is add a function like Podcast::has_episode searching for the episode source

and if podcasts doesn't have the episode continue to add
![image](https://user-images.githubusercontent.com/1305249/112110107-2e51d100-8bfe-11eb-85ef-839fa3b9512c.png)

**Comment by xekon** [comment] 2021-03-23 07:54
I have mine set to 9999:

![2021-03-23_00-53](https://user-images.githubusercontent.com/106644/112112028-39f7b600-8b72-11eb-9e3d-2c24c63f8890.png)

I did it this way so that when I add a new podcast stream, all episodes would be downloaded.

**Comment by lachlan-00** [comment] 2021-03-23 08:25
Ahh, if you set # episodes to download to 0 that should actually do the same thing and might actually solve this.

Keep number is the limit to start removing older episodes which I don't think would change this.

**Comment by xekon** [comment] 2021-03-23 08:27
will try setting both to 0

**Comment by lachlan-00** [comment] 2021-03-23 09:30
I'm hopeful it will because I wasn't able to make dupes so if that resolves the dupes we still need to: (in 5.1: podcast boogaloo)

* stop duplicate source url inserts anyway.
* Double check the default values (I always set them to 0 myself so why haven't I done that yet?)
* Possibly reword the setting language based on the default values
* Look for more bugs!

**Comment by usox** [comment] 2021-03-23 10:46
> * Look for more bugs!

There will be plenty of it - promised!

**Comment by xekon** [comment] 2021-04-09 14:59
> Ahh, if you set # episodes to download to 0 that should actually do the same thing and might actually solve this.
> 
> Keep number is the limit to start removing older episodes which I don't think would change this.

I set both to 0 and forgot to check ever since because I have been so busy lately. Unfortunately the problem still exists:

![2021-04-09_07-56](https://user-images.githubusercontent.com/106644/114199743-6ef16000-9909-11eb-8381-e157c77eecae.png)

![2021-04-09_07-57](https://user-images.githubusercontent.com/106644/114199770-74e74100-9909-11eb-8ecc-40f928715bd1.png)

![2021-04-09_07-57_1](https://user-images.githubusercontent.com/106644/114199795-787ac800-9909-11eb-9fcb-516c2a946ced.png)

**Comment by usox** [comment] 2021-04-14 13:24
@xekon ok I was able to reproduce this in develop.
I forced a race condition between multiple update-runs of the cli command which ended up adding the same episode multiple times at once.

Is it possible that your cronjob runs multiple times? Maybe because there's a backup-file, vim-swap file or something alike in your /etc/cron.d folder?

**Comment by xekon** [comment] 2021-04-14 16:07
GENIUS! yes there are two entries in the folder for the cron job. I would have never guessed to check this, so thank you so much. I have deleted the duplicate cron job just now.

**Comment by usox** [comment] 2021-04-14 17:59
Excellent. Race conditions are hard to prevent and I don't see it getting fixed within the next months, years. So I'm closing this for now...

**Closed by usox** 2021-04-14 17:59 UTC

**Comment by lachlan-00** [comment] 2021-04-14 22:07
I wonder if we can put a check in config to 'lock' the catalogs when being updated. it would save a lot of issues that would require complicated code.

* start process and set 1 on the catalog 'lock' column
* finish and set 0/null
* Provide an option on updateCatalog to clear locks

**Comment by usox** [comment] 2021-04-15 06:19
A locking mechanism may help but brings some problems itself. We should discuss that when we're rebuilding the catalog processes :)
