### ISSUE TITLE
Installation prevented because of missing database tables

### ISSUE THREAD

**Issue by ProfessorSalty** [ampache/ampache#2369] opened 2020-04-30 19:54 UTC
## Description
I'm trying to create a new Docker container for Ampache that will better fit with my current setup. The installer says that there is an error reaching the database, but the debug page just says there's an issue with reading some tables and that it can reach the database just fine. The logs don't give me anything to go on, either.

### To reproduce

Try out my container using the included `docker-compose.yml`
https://github.com/ProfessorSalty/ampache-fpm-docker

### Expected behavior
I'm expecting to either proceed in the installation to the point where I can create the tables, or get an error that better describes what I need to fix.

### Screenshots
<img width="1213" alt="Screen Shot 2020-04-30 at 3 40 58 PM" src="https://user-images.githubusercontent.com/6478756/80752712-f8918e80-8af9-11ea-99dc-a90803f5929f.png">

## Settings

https://github.com/ProfessorSalty/ampache-fpm-docker/blob/master/ampache.cfg.php.template

**Comment by lachlan-00** [comment] 2020-05-01 07:02
it's more likely that the database connection isn't working or the config isn't correct rather than the db missing tables.

that error message isn't very clear

**Comment by ProfessorSalty** [comment] 2020-05-01 12:18
According to the test page, Ampache can connect to the db and the config file is readable. 

<img width="1210" alt="Screen Shot 2020-05-01 at 7 56 21 AM" src="https://user-images.githubusercontent.com/6478756/80803767-47363b80-8b81-11ea-980f-cbb3a0a596e5.png">

I can ping the database container from the fpm and I can connect to the database, so I know that the credentials are good, the db works, and the containers can communicate.

Have I got something wrong with the format of the configuration? Do these fields need quotes or something?

```
;#########################################################
; Database                                               #
;#########################################################
; Hostname of your database
; For socket authentication, set the path to socket file (e.g. /var/run/mysqld/my
sqld.sock)
; DEFAULT: localhost
database_hostname = ampache-db
; Port to use when connecting to your database
; DEFAULT: none
database_port = 3306
; Name of your Ampache database
; DEFAULT: ampache
database_name = ampache
; Username for your Ampache database
; DEFAULT: ""
database_username = ampache
; Password for your Ampache database, this can not be blank
; this is a 'forced' security precaution, the default value
; will not work (except if using socket authentication)
; DEFAULT: ""
database_password = some_test_password
```

**Comment by wagnered** [comment] 2020-05-01 16:29
@lachlan-00,

Mysql DESCRIBE is a synonym for 'show COLUMNS. This query  implies that the mysql engine knows what database to use. Not sure what is the problem with @ProfessorSalty's setup, but I'm guessing that the default database hasn't been set.

I suggest that the database be included when setting up the dsn in Dba::_connect(except for the connection test of course ; ' > ).

**Comment by ProfessorSalty** [comment] 2020-05-01 16:53
> Not sure what is the problem with @ProfessorSalty's setup, but I'm guessing that the default database hasn't been set.

Is this separate from the `database_name` field in the config file? Or do I need to populate the db somehow before the app is usable?

**Comment by arnaudbey** [comment] 2020-05-01 17:16
I got the same pb recently. The problem was an existing ampache.cfg.php in my config dir (I copied it here a bit too early).

**Comment by wagnered** [comment] 2020-05-01 17:39
Yes it is.  

My suggestion to @lachlan-00, although not exactly a bug fix, will more likely assure the database test will pass under any condition.  

Because I'm not familiar with docker setup and don't have the means of testing your repo, @lachlan-00 (given the time) may be able to set up your repo and debug exactly what the problem is.

**Comment by ProfessorSalty** [comment] 2020-05-01 17:49
Ok, I'm available for any help or input needed.

**Comment by lachlan-00** [comment] 2020-05-03 02:30
i can build your file and work out what it is, there've been a few bugs fixed by doing a bit of digging like this so i'll be sure to investigate.

next week i'll be pushing on with a lot of api work but the installation process needs some work before we can do another rrelease so this is important to follow up.

**Comment by kuzi-moto** [comment] 2020-05-13 15:25
I haven't looked at the docker image in question, but I did create my own minimal Ampache docker image that seems to be working fine with a separate db: https://github.com/kuzi-moto/ampache-docker-kuzi

**Comment by kuzi-moto** [comment] 2020-05-13 22:06
I have determined the source of the issue. In your Dockerfile, you have several lines that appear to put the Ampache configuration file into the config directory. The problem is that the database and related tables are created before the configuration file exists, so when the config file is created preemptively Ampache is trying to connect to the database but cannot since none of the correct tables exist.

I believe there are two options to fix this. First, change your `Dockerfile` from this:

```bash
CMD envsubst "`env | awk -F = '{printf \" $$%s\", $$1}'`" \
        < /var/templates/ampache.cfg.php.template \
        > /var/www/html/ampache/config/ampache.cfg.php \
        && cat /var/www/html/ampache/config/ampache.cfg.php \
        && php-fpm
```

to this:

```bash
CMD envsubst "`env | awk -F = '{printf \" $$%s\", $$1}'`" \
        && php-fpm
```

Which will stop populating the config file ahead of time. But this also will render your environment options useless. Second option is to populate the database with the `./sql/ampache.sql` file on the first run.

**Comment by mitchray** [comment] 2021-05-14 09:39
Solution seems to have been provided by kuzi, going to close this but reopen if you feel otherwise

**Closed by mitchray** 2021-05-14 09:39 UTC
Labels: database
