### ISSUE TITLE
Impossible to play other discs than albums types

### ISSUE THREAD

**Issue by Jucgshu** [ampache/ampache#903] opened 2015-07-16 17:55 UTC
Hey guys,

I have a strange problem.

On artists page, I can play albums from pushing the little play icon without any issue.

But, when I try live types, or EP or compilation types, nothing happens. I mean nothing is shown even with level 5/6 debug on logs.

But, if I go into the EP, compilation or live disc page, I can play the discs from using the play option there.

Is it just me ?

Tried with a bunch of files/discs with latest pull from github.

**Comment by Phyks** [comment] 2016-07-19 10:04
Wow, I completely missed this issue :/

This is actually a duplicate of https://github.com/ampache/ampache/issues/1334. There was some ongoing discussion on this one, so I think we can close this one as a dup and move the discussion to #1334.

**Closed by Phyks** 2016-07-19 10:04 UTC
Labels: bug
