### ISSUE TITLE
Artist view: Buttons "Play", "Play last", "Play next" not working for medium type that is not "Album"

### ISSUE THREAD

**Issue by arno1979** [ampache/ampache#1334] opened 2016-07-15 08:46 UTC
# Environment
- Ampache version: 3.8.2
- Web server + version: Apache 2.4.18
- Server operating system: Fedora 23
- Client operating system: OS X 10.11.5

- Client type:
  - Web
# Description

This is simple to reproduce, I think, and has been this way for a long time:
When in an artist view `(e.g.: index.php#artists.php?action=show&artist=3791)` below the general artist information we get the artists albums, eps, compilations etc.
As mentioned in the topic the buttons "Play", "Play last" and "Play next" displayed to the left of the artwork when hovering over the artwork with the mouse don't have any effect when trying to use them for a medium of the type "EP". They work just fine for the albums displayed just above!
The only way to get the web player to play an EP is to click on the artwork, get the detailed view for the EP and then use on of the buttons there.

EDIT: I just double checked: The afore mentioned problem also occurs for medium types "Album/soundtrack" and "Album/compilation/dj-mix/remix". It seems to me that the buttons might only be working for "Albums" and none of the other types.
I tested this accross different browsers: Firefox, Chrome, Safari under OS X and Internet Explorer 11 under Windows 8.1.

**Comment by Niols** [comment] 2016-07-15 08:58
Hi.
Indeed, I can reproduce at HEAD on the develop branch.
I will try to have a look at it, but I can't at the moment

**Comment by arno1979** [comment] 2016-07-15 09:22
Ok, great!

**Comment by Niols** [comment] 2016-07-15 09:31
Note that you can right-clic to have a detailled "play" menu. That's maybe a quicker workaround than to load the album view

**Comment by arno1979** [comment] 2016-07-15 09:34
A right-click? Where? On the artwork? In Firefox I only get the standard right-click context menu...

**Comment by Niols** [comment] 2016-07-15 11:04
This may not be possible in 3.8.2, I don't know

**Comment by Phyks** [comment] 2016-07-15 11:57
Yes, right-click on the album/EP/… artwork should give you a special menu.

**Comment by Phyks** [comment] 2016-07-15 12:02
Got it, the bug is in https://github.com/ampache/ampache/blob/ad270da63210f9870df0358d90d4480819ea7358/templates/show_album_row.inc.php#L28-L34.

We should not pass `object_type=album` but put something like `object_type=' . get_class($libitem) . '` or something like this (note that `get_class` will returned a namespaced strings, so maybe we should take only the part after the last `\\`.

Sorry, I cannot fix it easily at the moment. If anyone can push a PR for this, you are welcome, else it may wait for a few days.

**Comment by arno1979** [comment] 2016-07-15 12:19
@Phyks no special menu for me, no matter where i click...

**Comment by Phyks** [comment] 2016-07-15 12:22
Ok, not sure about it. Either a 3.8.2 issue (was introduced later) or a browser specific thing. Anyways, this menu is not very good and we already have considered replacing it.

**Comment by arno1979** [comment] 2016-07-15 12:28
@Phyks Ok, seems to not be present in 3.8.2, I checked in other browsers as well...
Thanks!

**Comment by Phyks** [comment] 2016-07-18 15:27
https://github.com/ampache/ampache/issues/1334#issuecomment-232934507 is totally wrong. Sorry. =((

Actually, it is much more subtle than this. If we go using the `artists.php` page, it works perfectly fine.

If we go using Ajax page loading (then URL in `#artists.php` page), it works for albums but not for other types. The event handler on click event should be attached but is not. I have no idea why it is the case and am trying to figure it out at the moment.

**Comment by Phyks** [comment] 2016-07-18 16:03
I just cannot figure out what is wrong with it.

The (real) bug is that as soon as one has two `.MediatTable` (typically one for albums and one for EPs), the JS in `<script>` tags in the second one is simply not executed.

I tried putting a `console.log` just before the function call to bind a click event on `#play_album_X` and after, to check the bound events. Typical result is:
```
play_album_6
VM3695:1 [a#play_album_6, context: document, selector: "#play_album_6"]
VM3695:1 Object {click: Array[1]}
VM3695:1 {"click":[{"type":"click","origType":"click","guid":124,"namespace":""}]}
VM3704:1 play_album_17
VM3704:1 [a#play_album_17, context: document, selector: "#play_album_17"]
VM3704:1 Object {click: Array[1]}
VM3704:1 {"click":[{"type":"click","origType":"click","guid":133,"namespace":""}]}
VM3713:1 play_album_8
VM3713:1 [a#play_album_8, context: document, selector: "#play_album_8"]
VM3713:1 Object {click: Array[1]}
VM3713:1 {"click":[{"type":"click","origType":"click","guid":142,"namespace":""}]}
VM3722:1 play_album_5
VM3722:1 [a#play_album_5, context: document, selector: "#play_album_5"]
VM3722:1 Object {click: Array[1]}
VM3722:1 {"click":[{"type":"click","origType":"click","guid":151,"namespace":""}]}
VM3731:1 play_album_10
VM3731:1 [a#play_album_10, context: document, selector: "#play_album_10"]
VM3731:1 Object {click: Array[1]}
VM3731:1 {"click":[{"type":"click","origType":"click","guid":160,"namespace":""}]}
VM3740:1 play_album_9
VM3740:1 [a#play_album_9, context: document, selector: "#play_album_9"]
VM3740:1 Object {click: Array[1]}
VM3740:1 {"click":[{"type":"click","origType":"click","guid":169,"namespace":""}]}
VM3769:1 play_album_17
VM3769:1 [a#play_album_17, context: document, selector: "#play_album_17"]
VM3769:1 Object {click: Array[1]}
VM3769:1 {"click":[{"type":"click","origType":"click","guid":196,"namespace":""}]}
```

First albums are on the index page and not displayed in the current view. I have two albums on my view, an album (id 17) which works and an EP (id 16) which is simply never seen, although it is displayed.

**Comment by Jucgshu** [comment] 2016-07-19 18:32
Small comment as it works with the right clic menu.

@arno1979 the menu can only be seen in "non-grid" album view.

**Comment by kuzi-moto** [comment] 2019-05-31 15:42
@lachlan-00 any chance you'll be able to take a look at this for the 4.0 release? I know it's a pretty minor issue since there is a workaround, but I think having this working will be a better user experience for those that are new to Ampache.

**Comment by lachlan-00** [comment] 2019-05-31 21:27
I have never come across this error before. 
But it's a long term issue so let's see if I can reproduce it and then fix it.

**Comment by kuzi-moto** [comment] 2019-05-31 21:48
Awesome, thanks for looking into it!

**Comment by kuzi-moto** [comment] 2019-07-03 14:30
I'd like to add, that there are also issues in sorting the tables for all non "Album" releases. Clicking the "Album", "Artist", or "Year" labels in the table headings do not apply any sorting.

**Comment by lachlan-00** [comment] 2019-07-03 22:14
Phyks was right. The JS doesn't seem to do anything when separated into multiple tables.

It's an annoying issue because visually I like that over the default but I haven't worked out why yet

**Comment by lachlan-00** [comment] 2019-07-04 04:51
This looks like the culprit
![image](https://user-images.githubusercontent.com/1305249/60640602-418d9d80-9e6b-11e9-8cb0-12dd19956162.png)

**Comment by lachlan-00** [comment] 2019-07-04 05:38
@kuzi-moto and anyone else interested.

Deleting the mediatable js/css from the header will fix this.
I can't tell what is broken by taking it out yet but nothing seems broken on the surface...
![image](https://user-images.githubusercontent.com/1305249/60641977-89afbe80-9e71-11e9-883c-2130dff165b2.png)

**Comment by lachlan-00** [comment] 2019-10-17 00:30
I'm currently testing the removal of jquery.mediatable.

This has fixed playback buttons for me. but will need further testing

**Comment by kuzi-moto** [comment] 2019-10-17 01:09
Nice! I think mediatable was basically a version of media queries specifically for tables. When you realize the browser page, it automatically changes the CSS classes for the table based on the width of the page. As it gets smaller it will hide certain columns. I'm also not sure if it's what allows table sorting or not.

**Comment by lachlan-00** [comment] 2019-10-17 01:23
For me in testing sorting is still broken as it always puts the results into the first table when grouped.

I think that would be separate to this issue and mediaTable but not 100% sure

Maybe put the sorting in a separate issue as the original issue will be resolved before sorting

**Comment by lachlan-00** [comment] 2019-10-17 03:26
Closing fixed.
In develop the play buttons work without issue no matter the object type

**Closed by lachlan-00** 2019-10-17 03:26 UTC
Labels: UI, bug, help wanted
