### ISSUE TITLE
Ampache javasript error

### ISSUE THREAD

**Issue by gyula21** [ampache/ampache#1246] opened 2016-06-10 06:56 UTC
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache 2 - Newest
 * Server operating system: Raspbian Jessie 
 * Client operating system: Win7
 * Client type:
   - [x] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: Newest Chrome
 
# Settings
Describe your settings or attach ampache.cfg.php after removing sensitive information (server host, database connection...)
Fresh install, MySQL DB, Apache2 Webserver on a Raspberry Pi 2

# Description
Here the bug/feature description and how to reproduce/integrate it.
After fresh install the icons on the left (admin, plugins, etc...) point to javascript:void(0);
![ampache](https://cloud.githubusercontent.com/assets/3487559/15956453/ed2ea986-2ee8-11e6-810f-87b76530e39c.PNG)
EDIT: tested in Firefox and Internet Explorer, too with the same result

# Logs
[Ampache logs](https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging) and web server access/error logs in attached files. Please also add client application logs if appropriate.

**Comment by Phyks** [comment] 2016-06-10 17:00
I don't see the issue here. This is working as intended, they should have target `javascript: void(0)`. This does not prevent in any case these buttons from working.

What is your exact issue?

**Comment by Phyks** [comment] 2016-06-22 21:28
Closing as this is not an issue. Reopen with extra info if you have an issue.

**Closed by Phyks** 2016-06-22 21:28 UTC
Labels: waiting
