### ISSUE TITLE
UltraSonic client stopped working (on some views) before update and continues failing after it

### ISSUE THREAD

**Issue by iglosiggio** [ampache/ampache#1651] opened 2017-12-26 14:12 UTC
# Environment

 * Ampache version: `3.8.4 (4fd3ff5b1)` _(last commit in the master branch)_
 * Web server + version:
```cmdline
$ apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
```
 * Server operating system: Ubuntu 16.04.3 LTS
 * Client operating system: Android 6.0 (Moto G3 LATAM)
 * Client type:
   - SubSonic _(UltraSonic 2.0.0)_

# Logs

Neither the apache_error nor Ampache log anything when requested a view that fails (such as the artists view).

Apache access logged lines on failed artists view:
```
10.0.2.2 - - [26/Dec/2017:10:47:13 -0300] "GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 710 "-" "okhttp/3.9.0"
```

The following views work:

* [MUSIC] Albums view
* [MUSIC] Genres view
* [SONGS] Random view
* [ALBUMS] Recently added
* [ALBUMS] Recently played
* [ALBUMS] Most played
* [ALBUMS] Best scored
* [ALBUMS] Random
* [ALBUMS] By name

_Note: the titles may be a bit off, i'm retranslating them from the spanish translation of ultrasonic_

The following views **doesn't work**:

* [MUSIC] Artists
* [SONGS] Liked (this may not work because i don't used the like function)
* [ALBUMS] Liked (this may not work becase i don't used the like function)
* [ALBUMS] By artist
* [VIDEOS] Videos (this may not work because i don't have any videos)
* Playlists

**On search i can access the artist profile and album list**

#### [ALBUMS] By artist
`GET //rest/getAlbumList.view?type=alphabeticalByArtist&size=20&offset=0&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1`
```json
{
  "subsonic-response": {
    "type": "ampache",
    "version": "1.11.0",
    "status": "ok",
    "albumList": [
      
    ]
  }
}
```

#### [MUSIC] Artists
_**Note:** ¿Is it possible that the client is doing something wrong here?_
`GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1`
```json
{
  "subsonic-response": {
    "type": "ampache",
    "version": "1.11.0",
    "status": "ok",
    "musicFolders": {
      "musicFolder": {
        "id": 7,
        "name": "COMUNISMO"
      }
    }
  }
}
```

My collection is medium sized i think

| Albums | Artists | Songs | Size            |
| --------- | -------- | -------- | -------------- |
| 685      | 333     | 7628    | 153.65 GB |

**Comment by wagnered** [comment] 2017-12-26 19:17
@iglosiggio, Thanks for the info. 

It looks like Ultrasonic is requesting the response of the getArtists command to respond with the json file format.  DSub requests an xml response and gives no error.  I will take a look at the ampache subsonic api and try to determine what file format is being used for the response to that request.

**Comment by iglosiggio** [comment] 2017-12-26 20:55
Thanks for the response, i think that Ultra Sonic changed from XML to JSON
recently. Can it be the reason?

**Comment by wagnered** [comment] 2017-12-26 23:09
Not sure, Ampache does respond in kind to json requests.  I added a debug event to try to see what the response actually is.  It recorded an sql error.  I searched online for the mysql error statement and issued a possible fix to the mysql server:  `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`.  I don't get an error on Albums by Artist  anymore, but It gives me a list of 6 entries which are empty of artist names.  There are only 6 artists in my test catalog.

Music->artists seems to work.

**Comment by palto42** [comment] 2017-12-27 10:52
I have the issues.  First thought it's related to the new Ampache release, but then I found that a downgrade on an older backup didn't help. Since I mainly use the playlists, I didn't immediately recognise the issue after UltraSonic update.
My Amapache is running on a RasperryPi Raspbian Jessie and the app on Samsung S8 with Android 7.0.

**Comment by iglosiggio** [comment] 2017-12-27 18:22
As i thought UltraSonic has updated it's API needs to include JSON support and at least Subsonic 1.7.0 (source: https://github.com/ultrasonic/ultrasonic/issues/109). What's the supported API version of ampache?

**Comment by wagnered** [comment] 2017-12-27 20:06
I just fired up my subsonic server and Ultrasonic seems to function perfectly on the problems you referred to earlier.  Of the 4 or 5 clients I tried, Ultrasonic seems to be the only app that currently uses json.

This also indicates that the Ampache json functions appear not to be functioning correctly.

Ampache doesn't check the clients requested API version as the original developer claimed that many of the clients send bogus API versions anyway.  Ampache responds to a subset of subsonic commands listed on the [Subsonic API](http://www.subsonic.org/pages/api.jsp#getIndexes)  page.

**Comment by wagnered** [comment] 2017-12-28 18:35
@iglosiggio and @palto42,

I just pushed a commit to the develop branch that allows Subsonic to get Music->Artist list and Albums->By Artist.

**BUT** there is another problem with getting the albums from some artists from the Music->Artists list.  Some artists show the albums and some give me an error.

I made the changes available because I'm not yet sure that this is yet another Ampache problem or my music is tagged with faulty data.

**Comment by wagnered** [comment] 2017-12-28 22:49
@iglosiggio, @palto42 

The problem isn't bad tag data. 😈 

I'm not sure if the problem lies with the php json functions or Ultrasonics. After the Last commit, Ultrasonic now gets a list of all artists, but gets errors when accessing artists with only one album.  I've submitted a query to the Ultrasonic developer about the json problem.

**Comment by iglosiggio** [comment] 2017-12-29 03:26
Well, that didn't worked i'm attaching my access log for the test (the error log didn't get any line)

```
10.0.2.2 - - [29/Dec/2017:00:09:11 -0300] "GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.7.0&p=enc:REDACTED HTTP/1.1" 200 3743 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:09:11 -0300] "GET //rest/getRandomSongs.view?size=50&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.7.0&p=enc:REDACTED HTTP/1.1" 200 55026 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:09:16 -0300] "GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 557 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:32 -0300] "GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 710 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:36 -0300] "GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 557 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:39 -0300] "GET //rest/getAlbumList.view?type=frequent&size=20&offset=0&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 3500 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:39 -0300] "GET //rest/getLicense.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 595 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:40 -0300] "GET //rest/getCoverArt.view?id=al-200000487&size=133&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 11460 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:40 -0300] "GET //rest/getCoverArt.view?id=al-200004906&size=133&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 7162 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:40 -0300] "GET //rest/getCoverArt.view?id=al-200000489&size=133&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 3206 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:40 -0300] "GET //rest/getCoverArt.view?id=al-200000442&size=133&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 6673 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:40 -0300] "GET //rest/getCoverArt.view?id=al-200000441&size=133&u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 5000 "-" "okhttp/3.9.0"
10.0.2.2 - - [29/Dec/2017:00:10:41 -0300] "GET //rest/getMusicFolders.view?u=iglosiggio&c=UltraSonic%2520for%2520Android&f=json&v=1.11.0&p=enc:REDACTED HTTP/1.1" 200 557 "-" "okhttp/3.9.0"
```

The `coverArt` requests correspond to a "is this still alive" test that i ran browsing the recently/frequently played albums.

On the ampache logs i did get this line that might be related repeated multiple times:
```
2017-12-29 01:13:05 [iglosiggio] (Dba) -> Error: ["42000",1055,"Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'ampache.artist.name' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"]
```

**Comment by wagnered** [comment] 2017-12-29 05:10
@iglosiggio 
An earlier comment of mine suggests that sql error can be fixed by issuing SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));'. It is a work-around.

I got sidetracked and forgot about it:  I  will modify the SQL statement that caused the error.

**Comment by wagnered** [comment] 2017-12-29 05:39
Did some further investigation and they increased the restrictions by default on verssion 5.7.  Issuing that SQL statement reverts the server to mimick earlier versions of the server.  It now is necessary.  It's either that or don't sort the the albums by artist name.

**Comment by ogarcia** [comment] 2017-12-29 11:13
@iglosiggio You are wrong in `[MUSIC] Artists` Utrasonic make two requests: 
```
GET /rest/getMusicFolders.view?u=USER&c=UltraSonic%2520for%2520Android&f=json&v=1.8.0&p=enc:PASS 
GET /rest/getIndexes.view?u=USER&c=UltraSonic%2520for%2520Android&f=json&v=1.8.0&p=enc:PASS
```

The first one is for know what folders there is available and the second for get the artist list of these folders. Take note that Utrasonic have a cache, if the list of folders are the same that the last visit the second request is not made because the cache is used. You need to pull down the list for force an update.

The first request returns some like this
```
{
 "subsonic-response": {
  "musicFolders": {
   "musicFolder": [
    {
     "id": "1b2a156d-56da-4705-8f1c-fb68752cbb91",
     "name": "Music"
    }
   ]
  },
  "status": "ok",
  "version": "1.8.0"
 }
```
As I can see in your example the returned for server is OK.

The second request is explained in [Utrasonic bug](https://github.com/ultrasonic/ultrasonic/issues/109#issuecomment-354431245).

**Comment by iglosiggio** [comment] 2017-12-29 11:22
@ogarcia i know that UltraSonic it's supposed to make more than the `getMusicFolders` requests. It's just failing before it does it.

**Comment by iglosiggio** [comment] 2017-12-29 11:35
Hi, i think i found the problem, in the JSON that @ogarcia pasted `musicFolder` is an array and `musicFolders` an object. In the JSON that ampache sends both `musicFolder` and `musicFolders` are objects (`musicFolder` being the one that that contains the object).

I will try to patch this on my ampache instance.

**Comment by ogarcia** [comment] 2017-12-29 11:47
Oh, @iglosiggio you are right, I had not noticed the error. But you may have more of one music folder, because of this `musicFolder` must be an array.

**Comment by iglosiggio** [comment] 2017-12-29 11:53
Yes, this is a problem with the defaults of `alwaysArray` in the function `xml2json` (lib/class/subsonic_api.class.php:208). Now UltraSonic still reports errors but it makes the second request.

**Comment by iglosiggio** [comment] 2017-12-29 11:59
I think that `getIndexes` doesn't work because i have an index called "X-Z" instead of X, W and Z

**Comment by iglosiggio** [comment] 2017-12-29 12:09
I MADE IT WORK (this is a workaround patch, not nice code)

```patch
From c8b0ee9c0bf3226f1df6295e2f3a4284efb9d618 Mon Sep 17 00:00:00 2001
From: Ignacio Losiggio <iglosiggio@gmail.com>
Date: Fri, 29 Dec 2017 09:08:14 -0300
Subject: [PATCH] Working Music->Artists in UltraSonic

---
 lib/class/subsonic_api.class.php      | 2 +-
 lib/class/subsonic_xml_data.class.php | 1 -
 2 files changed, 1 insertion(+), 2 deletions(-)

diff --git a/lib/class/subsonic_api.class.php b/lib/class/subsonic_api.class.php
index c5953a2..e1052c1 100644
--- a/lib/class/subsonic_api.class.php
+++ b/lib/class/subsonic_api.class.php
@@ -205,7 +205,7 @@ class Subsonic_Api
         $defaults = array(
             'namespaceSeparator' => ':',//you may want this to be something other than a colon
             'attributePrefix' => '',   //to distinguish between attributes and nodes with the same name
-            'alwaysArray' => array(),   //array of xml tag names which should always become arrays
+            'alwaysArray' => array('musicFolder', 'artist'),   //array of xml tag names which should always become arrays
             'autoArray' => true,        //only create arrays for tags which appear more than once
             'textContent' => 'value',       //key used for the text content of elements
             'autoText' => true,         //skip textContent key if node has no attributes or child nodes
diff --git a/lib/class/subsonic_xml_data.class.php b/lib/class/subsonic_xml_data.class.php
index 90b05ac..27411d4 100644
--- a/lib/class/subsonic_xml_data.class.php
+++ b/lib/class/subsonic_xml_data.class.php
@@ -314,7 +314,6 @@ class Subsonic_XML_Data
             if (strlen($artist->name) > 0) {
                 $letter = strtoupper($artist->name[0]);
                 if ($letter == "X" || $letter == "Y" || $letter == "Z") {
-                    $letter = "X-Z";
                 } else {
                     if (!preg_match("/^[A-W]$/", $letter)) {
                         $sharpartists[] = $artist;
--
2.7.4
```

**Comment by iglosiggio** [comment] 2017-12-29 13:05
I think that the most sensible fix is to have an `options` array for each API endpoint that is passed (if it exists) to xml2json (xml2json already merges the options array with the API-wide defaults if provided one).

Btw, thanks for all the help on pinning down this bug!

**Comment by wagnered** [comment] 2017-12-29 19:18
@iglosiggio.

I also had to add 'child' to the 'alwaysArray' array to get a single album from Music->Artist menu. it also fixed the Albums->By Name access to the albums.
 
Also, could you please explain why the need to remove   `$letter = "X-Z";` at "@@ -314,7 +314,6 @@ class Subsonic_XML_Data" in the patch you suggested earlier?  

I am a "late arrival" to the Ampache developement team and the only one who has any time to work on existing issues, so it is hectic trying to get an understanding of the entire project and at the same time develop the "Ampache/Laravel version that @Afterster began awhile back.

Thank you very much for your help: It is much appreciated.

**Comment by iglosiggio** [comment] 2017-12-29 19:24
I think that that removal was unnecesary, i did it based on my initial suspect that having an index with more than one letter was causing errors.

I will revert that line in my instance and edit this comment ASAP

**Comment by wagnered** [comment] 2017-12-29 22:03
@iglosiggio,

What should the reponse be if the (generic) client request  results and no data to return?

Originally Ampache returned:
>{
    "subsonic-response": {
        "type": "ampache",
        "version": "1.11.0",
        "status": "ok",
        "videos": []
    }
}

Ultrasonic saw it as an error. So I changed the response to be an error:

>{
    "subsonic-response": {
        "type": "ampache",
        "version": "1.11.0",
        "status": "failed",
        "error": {
            "code": 70,
            "message": "Videos not found."
        }
    }
}

And Ultrasonic also interpreted it as an error.

Thanks...

**Comment by Tapchicoma** [comment] 2017-12-30 09:01
@wagnered the first json should be following:

```
{
    "subsonic-response": {
        "type": "ampache",
        "version": "1.11.0",
        "status": "ok",
        "videos": {
           "video" : []
        }
     }
}
```

**Comment by wagnered** [comment] 2017-12-30 18:15
@Tapchicoma 

Thank you, but that example does not show an empty list.

I thought that the Subsonic API Error Response  "70 The requested data was not found." described at: http://www.subsonic.org/pages/api.jsp  could also apply.

I will leave the code as it is.

**Comment by ogarcia** [comment] 2018-01-02 13:23
Take note about new related issue https://github.com/ultrasonic/ultrasonic/issues/118

The problem is that in search, the empty result must be `"searchResult2": {}` instead of `"searchResult2": []`.

API `rest/search2.view`.

Empty Good result:
```
{
 "subsonic-response": {
  "status": "ok",
  "searchResult2": {},
  "version": "1.8.0"
 }
}
```

Empty bad result (current ampache result):
```
{
    "subsonic-response": {
        "type": "ampache",
        "version": "1.11.0",
        "status": "ok",
        "searchResult2": []
    }
}
```

This is because `searchResult2` is an object that can have arrays inside:
```
  "searchResult2": {
    "album": [
      {
        "isDir": true,
        "album": "Always Outnumbered, Never Outgunned",
        "parent": "65128739-d4c8-4624-ab0d-1a2290650a2f",
        "created": "2017-07-01T13:42:54",
        "coverArt": "7aac534f-aa57-472e-b270-530fede415b6",
        "title": "Always Outnumbered, Never Outgunned",
        "artist": "The Prodigy",
        "id": "7aac534f-aa57-472e-b270-530fede415b6"
      }
    ],
    "song": [
      {
        "suffix": "mp3",
        "isVideo": false,
        "artistId": "257bf503-a291-4822-abbf-70076cb679bc",
        "year": 2005,
        "duration": 223,
        "id": "0d946ca4-4cb0-4ba8-94c5-8d6b3dbded67",
        "size": 5414229,
        "album": "Kingdom of Heaven: Original Motion Picture Soundtrack",
        "title": "Wall Breached",
        "discNumber": 1,
        "type": "music",
        "isDir": false,
        "contentType": "audio/mpeg",
        "parent": "c1a85ae6-6676-46b8-a7c9-04400c19df8a",
        "track": 15,
        "albumId": "da990496-7004-40f8-bf7c-1adf4244a7a5",
        "genre": "Classical",
        "path": "Harry Gregson‐Williams/Kingdom of Heaven_ Original Motion Picture Soundtrack/15 Wall Breached.mp3",
        "artist": "Harry Gregson‐Williams",
        "coverArt": "c1a85ae6-6676-46b8-a7c9-04400c19df8a",
        "bitRate": 192,
        "created": "2017-07-01T13:42:26"
      }
    ],
    "artist": [
      {
        "id": "57a262a6-dd34-4a33-bb6c-ad227be1f252",
        "name": "Creedence Clearwater Revival"
      }
    ]
  }
```

**Comment by wagnered** [comment] 2018-01-04 07:02
All function, except Chat, no work  on the Ultrasonic client.  The Chat function is not implemented in the Ampache Subsonic API.

**Closed by wagnered** 2018-01-04 07:02 UTC
