### ISSUE TITLE
FR: Dsub download friendliness

### ISSUE THREAD

**Issue by gerroon** [ampache/ampache#1684] opened 2018-03-05 03:06 UTC
Hi

At the moment the Dsub connection over the Subsonic api seems to work fine, except one thing wich is about how Dsub ends downloading the files.

Normally Dsub downloads the songs  (when connected to a real Subsonic server) to a properly organized folder, basically it replicates where the subsonic server scanned those files which generally ends up organized on the mobile device as long as the original folders on the desktop is well organized.

This is great because once downloaded finding and listening those songs is great, also that works with the cover.jpg files since they are in their respective folders.

The issue is that Dsub downloads all files under a folder called "rest" when connected to Ampache and all album art is called album art so it just overrides. The only ok thing happens here that at least the file names have a reasonable filename thou it lacks, album or the artist indication.

I realize this might be just an api limitation considering that Ampache does not store the folder paths however I am wondering if it is posssible trick Dsub so that at least files are saved under their own albums? Or maybe the files can be nmed like %artist%-%album%-%title%-%track% etc kind of pattern?

**Comment by gerroon** [comment] 2018-03-06 01:47
Because all the album art when downloaded called album art, Dsub always shows the wrong album for a given song (after download) :(  

The album arts are shown properly when browsing the server btw.

**Comment by wagnered** [comment] 2018-03-06 18:54
@gerroon 

Started looking at it.  Seems rather random, only one album out of 84 showed this problem with DSub, didn't matter whether catalog is local or Subsonic remote.

Thanks

**Comment by gerroon** [comment] 2018-03-06 19:03
Interesting. So the other 83 albusm downloaded into their own foldersby Dsub  when connected to Ampache subsonic api?

**Comment by wagnered** [comment] 2018-03-06 19:44
> downloaded into their own foldersby

I don't understand what that means. I don't see any way to set "folders" in DSub.

Interesting: The Subsonic client is not displaying the incorrect cover art for the same album, or any other album.  Got to investigate further.

**Comment by wagnered** [comment] 2018-03-06 20:21
Sorry, with more artists/albums the Subsonic app shows the same problem.

**Comment by gerroon** [comment] 2018-03-06 22:17
Well when Dsub connected to a subsonic server this is what happens

files on Subsonic (pointed to /media/mymusic)
"/media/mymusic/myartist/myalbum/mysong.mp3"

When you download mysong.mp3 from that Subsonic server usig Dsub, Dsub copies it to 
"DSUB_DOWNLOAD_FOLDER/myartist/myalbum/mysong.mp3"

At the moment if Dsub connected to Ampache instance it downloads everything to
"DSUB_DOWNLOAD_FOLDER/rest/mysong.mp3"

**Comment by wagnered** [comment] 2018-03-07 23:28
@gerroon 

> DSUB_DOWNLOAD_FOLDER

I assume that is an environmental variable, I found it though on my Galaxy J3 and deleted everything in that folder.

My only concern is that Dsub is displaying the incorrect images.

Update:

I just discovered that DSub is doing some strange things:

On a single artist/album, I manually removed all images from the database.  On the Web interface, no images are shown for anything about that artist/album as should happen.

DSub still shows the same wrong album.  I cleaned the DSub cache and the phone's cache for Dsub, but nothing changed. 
I was watching the HTTP traffic passing from my phone to Ampache: I never saw a request for cover art. I don't know where DSub might be getting the image it is using, but it isn't from Ampache.

Using Subsonic When I displayed the artist on the library tab and then selected the album, there was no album art as is expected.

What seemed to help:  When I came across an album with the wrong cover art, I added a Musicbrainz id with Picard.  After Adding the mbid, the album displayed the correct cover art. This might be a work-around but I don't know if it would be 100% effective.

So, I'm because of the latest investigation, I'm not convinced that Ampache is at fault. :frowning:

**Comment by wagnered** [comment] 2018-03-08 18:31
@gerroon 

One last suggestion, if I may:

If you haven't already, you might try and compare Ultrasonic to DSub. In my opinion it has more features that Dsub.

**Comment by gerroon** [comment] 2018-03-08 18:43
Thanks, the issue with Ultrasonic is that it does have any upnp casting, otherwise it is nice as well

**Comment by zerodogg** [comment] 2018-06-15 09:49
This actually used to work fine (in 3.8.4, and I think 3.8.5), but no longer does after updating ampache.

**Comment by wagnered** [comment] 2018-06-15 16:32
@zerodogg 

If you are referring to the problem of not creating the correct folders when downloading files to cache, the problem has been fixed in the latest develop version.  I will be releasing 3.8.8  ASAP.

Sorry for the inconvenience.

**Comment by zerodogg** [comment] 2018-06-17 07:35
@wagnered great, thanks!

**Comment by zerodogg** [comment] 2018-06-22 08:18
I can confirm 3.8.8 fixed this. Tyvm @wagnered

**Comment by lachlan-00** [comment] 2019-05-24 03:14
Closing. Fixed.

Caching for my catalog "/mnt/music" looks like this:
* /mnt/music/L7/(2019) Scatter the Rats/
* /sdcard/Android/media/github.daneren2005.dsub/music/L7/(2019) Scatter the Rats/

**Closed by lachlan-00** 2019-05-24 03:14 UTC
