### ISSUE TITLE
Multiple artists per song not cataloged properly

### ISSUE THREAD

**Issue by enthiran** [ampache/ampache#347] opened 2014-07-25 19:53 UTC
I'm on Ampache 3.7.0. When I scan songs which have ID3 tags with a list of artists seperated by null character (ID3 V2.4.0), ampache will only show the first artist in the array. I installed the latest getID3 library and getID3 browse demo is correctly showing a list of artist, but even with the same getID3 library, Ampache will only show the first artist. Is this a bug / known issue?

**Comment by kuzi-moto** [comment] 2016-03-09 22:21
I understand that this issue is being worked on, and can't wait until it is implemented. However, are there any recommendations for a work around in the mean time? It makes my library look really silly when there are some artists whose name appear upwards of 15 times in a row! I would much rather have a sort by "album artist" option as that generally what I'm looking for when browsing albums.

**Comment by PaulWalkerUK** [comment] 2020-07-05 00:09
Being able set multiple artists would be great. I'm guessing not many (no) mobile apps would handle it very well, so it'd need to fall back gracefully for them (e.g. the mobile app sees something like a comma separated list). If the mobile app _can_ handle multiple artists, then even better!

**Comment by lachlan-00** [comment] 2020-07-05 00:21
My plan for multi artists is to allow a primary as normal but allow searching/listing from the other.

I'm thinking this by splitting the string/mbid into an array of IDs in the song_data table.

Not the highest priority but I think you should be able to identify split artists and not make new ones for joined artists

**Comment by mitchray** [comment] 2021-04-30 01:21
Duplicate of #2711 

(consolidating multi-artist issues)

**Closed by mitchray** 2021-04-30 01:21 UTC
Labels: enhancement
