### ISSUE TITLE
Songs from Dropbox catalog get paused and won't resume

### ISSUE THREAD

**Issue by upbeat21** [ampache/ampache#1199] opened 2016-04-07 22:18 UTC
# Environment
 
 * Ampache version: 3.8.2
 * Web server + version: Apache/2.2.15 
 * Server operating system: Unix
 * Client operating system: iOS 
 * Client type:
   - [ ] Web
   - [x] Ampache
   - [ ] SubSonic
   - [ ] Plex
   - [ ] DAAP
   - [ ] UPnP
   - [ ] WebDAV
 * Client application + version: 
 
I am building an iOS app as a player client for Ampache. Everything works fine except for songs added from Dropbox, they will be played normally until around 2min-3min of playing time, it just stops. Tried to search the log, the only error is 
"Attempt to close cURL handle from a callback in file /var/lib/openshift/56fa1ca889f5cf123c000223/app-root/runtime/repo/lib/vendor/dropbox/dropbox-sdk/lib/Dropbox/Curl.php"

I tried to debug in Xcode, playitem cannot get the duration of the song. And the currenttime for playeritem stopped. Failed to pause or replay. But try to get another song works. 

Anyone has any idea about this? Or how dropbox catalog works in Ampache. I suspect if ampache server shut down the connection to dropbox, since if I directly use web UI from the server, the same issue hanppens

**Comment by ricky641** [comment] 2016-04-08 11:01
I am also facing same problem, exact issue with me upbeat21 . I also have iOS Client as a player for ampache with dropbox as a catalog and with similar server configuration. Song plays in my iOS app for 2-3 minutes or 60% length of actual song then suddenly stops and I cant pause or play that song. I think some issue in iOS because I made same app in Android & the songs play fine in my android app. I dont know where the problem is happening. I am also struggling this from last 3-4 months. I have not found any solution to this problem. If you find any solution to this , please do update me also.
Thank you

**Comment by upbeat21** [comment] 2016-04-08 23:07
I think this is caused a timeout when Ampache server tried to stream from Dropbox. Try to see the max_execution_time value and apache timeout setting if it is too short to finish the whole song

**Comment by ricky641** [comment] 2016-04-09 06:02
Where can I find this max_execution_time or apache timeout value?

**Comment by Afterster** [comment] 2016-04-09 06:05
I'm not sure to understand why you get this behavior.
If you're using an app that is based on Ampache API as you said, same url (/play/...) is used to stream the song, then timeout should be the same and it shouldn't work on web player neither.
Could this be a behavior related to the client that cancel the stream request? Maybe you could try with other clients?

**Comment by ricky641** [comment] 2016-04-09 06:07
Yeah right Afterster , it doesnt make any sense. May be some setting with iOS because it plays perfectly fine on my android client of ampache.

**Comment by Afterster** [comment] 2016-04-09 06:10
Looks related to iOS then, maybe something related to http://stackoverflow.com/questions/1988376/connection-time-out-in-iphone-for-http-requests?

**Comment by ricky641** [comment] 2016-04-09 06:17
Yeah , I guess this can be issue. It plays the song which it can buffer in 60 seconds

**Comment by ricky641** [comment] 2016-04-09 06:18
Wait afterster, I just tested on my android client. It just played 50% of all songs.. Where you think this issue might be happening?

**Comment by ricky641** [comment] 2016-04-09 06:51
http://juanynelson-applicationcode.rhcloud.com/ampache/play/index.php?ssid=96f0b2e30558f26d4936ff7d700cdc68&type=song&oid=3572&uid=4&player=api&name=Julio%20Jaramillo%20-%2001%20Ruego.mp3

This is URL which was generated on iOS Client and you can see its just 1 minute of whole song

**Comment by upbeat21** [comment] 2016-04-11 00:07
For me I found out the issue happens even in the web player. I am using rhcloud too. It uses apache server and I think they would limit some resource usage for long time connection. For my understanding, Ampache server would open connection to dropbox and stream songs from dropbox. Somehow, I suspect the server from rhcoloud would close the connection to dropbox after sometime. I never had this issue with local catalog. @Afterster would you please point out if this might be the cause based on how it works for dropbox catalog?

**Comment by Afterster** [comment] 2016-04-14 06:24
Yes this could be the cause. I believe people using Dropbox catalog (both of you here) are using a low ressources server, probably mutualized and with a lot of restrictions. Could be the pattern, otherwise it could also be an issue on Dropbox official PHP library that doesn't handle properly connection timeout with Dropbox servers.

**Comment by upbeat21** [comment] 2016-04-14 17:56
Hi Afterster, thanks for your reply. Any idea how I can debug to identify the issue? Thanks!

**Comment by Phyks** [comment] 2016-06-16 17:11
@upbeat21 I am trying to reproduce the issue, could you confirm I should follow these steps?

* Enable dropbox catalog module.
* Add a new catalog using dropbox backend.
* Play any song from the dropbox backend. It should stop playing in the middle.

Also, how often is the issue appearing?

**Comment by upbeat21** [comment] 2016-06-16 21:57
Yes, that's the right way to reproduce. I see these much often happen to every songs. Especially for those songs newly added to dropbox. But I do see seldom a song can be finished.

**Comment by Phyks** [comment] 2016-06-16 22:50
I have played a FLAC file of length 3:52 several times (a dozen) and I could not reproduce the issue on my laptop =(

**Comment by upbeat21** [comment] 2016-06-16 23:31
Which server do you use? Cause I am using a free server, probably is has some restriction to use the resource. So I suspect that might be the reason. But haven't got a clue to debug to verify that is the case.

**Comment by Phyks** [comment] 2016-06-17 08:01
I am using Nginx + PHP-FPM setup on my laptop at the moment. Do you have access to any other server than your free server, to check if you can reproduce?

Apart from contacting your server provider to see if they can confirm something related to long time connection, or trying to reproduce it on another server (typically a LAMP/WAMP server on your computer), I do not see much other ways to debug. Especially since I cannot reproduce.

cc @ricky641 also who had this issue

**Comment by upbeat21** [comment] 2016-06-17 17:57
I think that you cannot reproduce with your own server is a good example to show that this might be caused by the resource restriction. I will try to use my own server to see if I still have this issue. I appreciated your time and help!

**Comment by Phyks** [comment] 2016-06-17 22:24
Ok. Closing, reopen if you think this is a real Ampache issues after your tests.

**Closed by Phyks** 2016-06-17 22:24 UTC
