### ISSUE TITLE
500 Internal Server Error, Localplay Modules

### ISSUE THREAD

**Issue by BoBeR182** [ampache/ampache#1281] opened 2016-06-21 11:31 UTC
# Environment

 * Ampache version: 086f3b8780c4efde6bd9619e3675b25b25e7cbaf
 * Web server + version: "Apache/2.4.20 (Unix) OpenSSL/1.0.2h PHP/7.0.7"
 * Server operating system:  4.6.2-1-ARCH Linux
 * Client operating system:  4.6.2-1-ARCH Linux

 * Client type:
   - Web 086f3b8780c4efde6bd9619e3675b25b25e7cbaf

# Settings

# Description

When I try to open the localplay modules from the webview I get a 500 server error and nothing loads in the box.

# Logs

**Comment by Phyks** [comment] 2016-06-21 11:48
Closing as most likely a duplicate of https://github.com/ampache/ampache/issues/1232.

Try to clone https://github.com/ampache/ampache/pull/1276 which has not yet been merged or run a `composer update xbmc-php-rpc` on your installation.

Reopen if this does not fix it.

**Closed by Phyks** 2016-06-21 11:48 UTC
