### ISSUE TITLE
404 error when cancelling album art seletcion

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2105] opened 2019-10-20 12:10 UTC
## Description

**Describe the bug**

When editing an album art clicking cancel results in a 404 error. Hitting the back button brings back to the edit album art screen.

**To reproduce**
1. Select any ablum
2. Click on the gear in the album art to edit album art.
3. Click cancel
4. 404 Error.

**Expected behavior**

Return to the album screen.

**Screenshots**

## Environment

* Ampache version: dd8cb46a0467e0a8c05597502df6f63baa46c6f3
* Web server + version: Apache 2.4.41, PHP 7.3
* Server operating system: Debian 11
* Client operating system: Windows 10

**Client type:**

* Web (Firefox)
* Ampache

## Logs

No Ampache log is generated.

**Comment by lachlan-00** [comment] 2019-10-20 23:57
i don't get this when cancelling. is the url generating a 404 in the webserver log?

**Comment by stebe** [comment] 2019-10-21 11:54
Here you go. This time with Chrome in case it was browser specific.

ampache.animeshare.com:443 2001:470:b28c:2::1000 - - [21/Oct/2019:07:53:16 -0400] "GET /https://ampache.animeshare.com/albums.php?action=show&album=36372 HTTP/1.1" 404 4639 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"

**Comment by lachlan-00** [comment] 2019-10-23 11:56
i wonder if it's a config setting. i can't recreate so it must be a config/code error with a setting

do you have the full url https://ampache.animeshare.com/ as one of the settings in the conf file?

**Comment by stebe** [comment] 2019-10-23 22:08
No I have nothing other than the mail domain mentioning the mail server.

**Comment by lachlan-00** [comment] 2019-10-23 23:47
I'll double check that it's not duplicating something but i haven't had this happen yet.

**Comment by lachlan-00** [comment] 2019-10-28 06:00
Your web_path was empty right? I think this might be returning '' for the web_path and connecting the '/' + $burl to make the double up.

The link is created based on two things
```
NavigateTo('<?php echo AmpConfig::get('web_path') . '/' . $burl
```

and $burl is created from JS
```
        <?php
        if (AmpConfig::get('ajax_load')) {
            $iframed = true; ?>
        <script src="<?php echo $web_path; ?>/lib/javascript/dynamicpage.js"></script>
        <?php require_once AmpConfig::get('prefix') . UI::find_template('show_html5_player_headers.inc.php'); ?>
        <script>
            function NavigateTo(url)
            {
                window.location.hash = url.substring(jsWebPath.length + 1);
            }

            function getCurrentPage()
            {
                if (window.location.hash.length > 0) {
                    var wpage = window.location.hash.substring(1);
                    if (wpage !== 'prettyPhoto') {
                        return btoa(wpage);
                    } else {
                        return "";
                    }
                }

                return btoa(window.location.href.substring(jsWebPath.length + 1));
            }
        </script>
        <?php
        } else {
            ?>
        <script>
            function NavigateTo(url)
            {
                window.location.href = url;
            }

            function getCurrentPage()
            {
                return btoa(window.location.href);
            }
        </script>
        <?php
        } ?>
```

In templates/show_get_art.inc.php if you replace line 64 with this let me know if that stops it.
```
        <input type="button" value="<?php echo T_('Cancel'); ?>" onClick="NavigateTo('<?php echo $burl; ?>');" />
```

**Comment by lachlan-00** [comment] 2019-10-28 06:17
you could also look at replacing the $burl with return_referer() which should be doing the same thing

**Comment by stebe** [comment] 2019-10-29 07:48
You are correct, I do not have anything in the configuration for web_path.  When I replaced that line with your first suggestion the 404 error went away and cancel returned me to the previous page.  With $burl replaced with return_referer() I was returned to the main Ampache screen which isn't where I was before.

**Comment by lachlan-00** [comment] 2019-10-29 09:02
Okay, that means I need to do a check on the webpath for anyone using a subdomain but at least this makes sense.
Progress!

**Comment by AshotN** [comment] 2019-10-30 06:20
I am using a sub-domain and I could not reproduce this.

**Comment by lachlan-00** [comment] 2019-10-30 07:07
@ashotn I just mean I need to ensure that I don't break subdomains when I fix this. 

Btw good to see you lurking around

**Comment by lachlan-00** [comment] 2019-10-31 13:51
put a check in to the template for this. hopefully it will fix it. i'll ping this issue when i open the pull so you know it's in

**Comment by lachlan-00** [comment] 2019-11-18 00:47
closing. reopen if you can kill it again but i think we're good here

**Closed by lachlan-00** 2019-11-18 00:47 UTC
Labels: UI, bug, easy
