### ISSUE TITLE
Smart playlist criteria issue

### ISSUE THREAD

**Issue by mariof1** [ampache/ampache#2169] opened 2019-11-15 08:23 UTC
### Describe the bug
Rule for 'Does not contain' does not give the desired output
### To reproduce

Steps to reproduce the behaviour:

1. Add new smart playlist
2. Add rule 'Tag' does not contain 'Rap'
3. Save changes
4. Songs containing 'Rap' in their genres/tags exists in the newly created playlist

## Environment

* Ampache version: develop
* Web server + version: Apache 2.4

**Comment by lachlan-00** [comment] 2019-11-15 08:34
i'm working on the search rules today so this is good timing. will test now.

**Comment by mariof1** [comment] 2019-11-15 08:38
Brilliant, thank you

**Comment by lachlan-00** [comment] 2019-11-17 23:40
I get all my items correctly from what i can tell with upper and lower case (Rap / rap)

One thing i see it that there is no "Is not" which is what you actually want to use.
![image](https://user-images.githubusercontent.com/1305249/69016157-608a6780-09e7-11ea-9177-80c5f5ac7ea8.png)

If you do contains you'll match things like trap as well.

**Comment by lachlan-00** [comment] 2019-11-17 23:50
I've added is not to the search rules and i can still get everything correctly.
![image](https://user-images.githubusercontent.com/1305249/69016271-ba3f6180-09e8-11ea-8949-5500d77fe206.png)
![image](https://user-images.githubusercontent.com/1305249/69016279-c6c3ba00-09e8-11ea-8071-00936e12f622.png)

I'll need to see some more info about your issue to dig into this as i can't really recreate it

**Comment by mariof1** [comment] 2019-11-18 07:39
I have just tested a few sql queries and I think the below describes what I really would like to see

```
select * from
  (
  select a.name artist, s.title, group_concat(distinct(t.name) separator ', ') tag
  from song s
  left join artist a on s.artist=a.id
  left join tag_map tm on s.id=tm.object_id
  left join tag t on tm.tag_id=t.id
  where tm.object_type = 'song'
  group by s.title
  ) as tags  where tags.tag like '%Rap%' and tags.tag not like '%Hip Hop%'
```

**Comment by lachlan-00** [comment] 2019-11-18 07:43
If you add one rule for is/contains and one for is not/does not contain that doesn't do it?

**Comment by mariof1** [comment] 2019-11-18 07:52
No it does not
![image](https://user-images.githubusercontent.com/32400371/69033831-c40c9900-09d7-11ea-9cbe-93d1ef8e8279.png)

It looks like it retrieves the data similar to the below sql query which is not the same as the one I posted earlier
```
  select a.name artist  ,s.title  ,group_concat(distinct(t.name) separator ', ') tag
  from song s
  left join artist a on s.artist=a.id
  left join tag_map tm on s.id=tm.object_id
  left join tag t on tm.tag_id=t.id
  where tm.object_type = 'song' and (t.name like '%Rap%' and t.name not like '%Hip Hop%')
  group by s.title
```

**Comment by mariof1** [comment] 2019-11-18 08:06
And here is the screenshot with just one rule `tag does not contain 'Rap'` as you can see I am getting songs with genre 'Rap' but in my opinion they should not be there at all.
![image](https://user-images.githubusercontent.com/32400371/69034868-1bac0400-09da-11ea-84c4-d38c2a26f4ed.png)

**Comment by lachlan-00** [comment] 2019-11-18 08:42
I don't know how you're getting that. I can't replicate it?

Each tag is compared individually to the input and not the whole string of genres.

The only thing I can think of is those tags aren't song tags.

If you go to the individual song is there a genre?

Also try setting it to artist tag / album tag instead

**Comment by mariof1** [comment] 2019-11-18 08:46
No, I don't use album/artist tags. The only tags that I use are the ones imported from tracks metadata, usually in format "tag1; tag2; tag3"

**Comment by lachlan-00** [comment] 2019-11-18 08:54
The artist and genre get populated from the song tags so it's possible they exist in the album/artist.

I've tested this over that last day and don't get any incorrect tags showing up so there must be a reason why you do.

**Comment by mariof1** [comment] 2019-11-18 09:07
Yes, you are right they exist in albums/artists, however I am still getting the same issue
![image](https://user-images.githubusercontent.com/32400371/69038923-ccb69c80-09e2-11ea-92bd-c911afa43705.png)
![image](https://user-images.githubusercontent.com/32400371/69038957-e1933000-09e2-11ea-93ef-90bcf522a5e5.png)

**Comment by lachlan-00** [comment] 2019-11-18 09:15
These are in a local Ampache Catalog? There is definitely something odd going on here

**Comment by mariof1** [comment] 2019-11-18 09:19
Yes local ampache catalog

**Comment by mariof1** [comment] 2019-11-18 09:33
The rule 'does not contain' seems to work fine for everything else but Tag/ Album Tag

**Comment by lachlan-00** [comment] 2019-11-18 10:01
Okay, that I can reproduce. Does not contains

**Comment by lachlan-00** [comment] 2019-11-18 10:54
I think i've worked out this now. will fix tonight.

**Comment by lachlan-00** [comment] 2019-11-18 11:25
Will be in the next develop update.

it was doing a count on tags which i've changed to straight name searches which is working

**Comment by lachlan-00** [comment] 2019-11-18 20:31
Well that sucks....
Same as before? Changing it to name fixed all the situations I could find.

**Comment by mariof1** [comment] 2019-11-18 20:59
Yeah same as before. I can see you have added artist tag but even that still does not provide correct results.

**Comment by lachlan-00** [comment] 2019-11-18 21:04
I'll do another dig today

**Comment by lachlan-00** [comment] 2019-11-19 01:03
would you be able to uncomment all the //debug_event lines and send me a log of that?

i'll run those queries locally and see whether i can reproduce

**Comment by mariof1** [comment] 2019-11-19 07:20
Here you are...

```
2019-11-19 07:11:32 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:11:32 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:11:32 [user.name] (search.class) -> $join[tag]: 1b9b8d9105d3ab6b923d6fbe387d9847 NOT LIKE '%Rap%' 
2019-11-19 07:11:32 [user.name] (search.class) -> SQL get_items: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN (SELECT `object_id`, `name` FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id` WHERE `tag_map`.`object_type`='song' AND `tag`.`name` NOT LIKE '%Rap%' GROUP BY `object_id`) AS `realtag_1b9b8d9105d3ab6b923d6fbe387d9847` ON `song`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id` WHERE `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` NOT LIKE '%Rap%' 
2019-11-19 07:11:56 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:11:56 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:11:56 [user.name] (search.class) -> SQL get_items: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id` LEFT JOIN `album` ON `song`.`album`=`album`.`id` LEFT JOIN (SELECT `object_id`, `name` FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id` WHERE `tag_map`.`object_type`='artist' AND `tag`.`name` NOT LIKE '%Rap%'  GROUP BY `object_id`) AS realtag_1b9b8d9105d3ab6b923d6fbe387d9847 ON `artist`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id` WHERE `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` NOT LIKE '%Rap%' AND `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` NOT LIKE '%Rap%' 
2019-11-19 07:12:04 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:12:04 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:12:04 [user.name] (search.class) -> SQL get_items: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id` LEFT JOIN (SELECT `object_id`, `name` FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id` WHERE `tag_map`.`object_type`='artist' AND `tag`.`name` NOT LIKE '%%'  GROUP BY `object_id`) AS realtag_b5289217a3252d7522e4eb266dd6eaff ON `artist`.`id`=`realtag_b5289217a3252d7522e4eb266dd6eaff`.`object_id` WHERE `realtag_b5289217a3252d7522e4eb266dd6eaff`.`name` NOT LIKE '%%' 
2019-11-19 07:12:08 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:12:08 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:12:08 [user.name] (search.class) -> SQL get_items: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id` LEFT JOIN (SELECT `object_id`, `name` FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id` WHERE `tag_map`.`object_type`='artist' AND `tag`.`name` NOT LIKE '%Rap%'  GROUP BY `object_id`) AS realtag_1b9b8d9105d3ab6b923d6fbe387d9847 ON `artist`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id` WHERE `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` NOT LIKE '%Rap%' 
2019-11-19 07:12:22 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:12:22 [user.name] (search.class) -> parse_rules: notcontain 
2019-11-19 07:12:22 [user.name] (search.class) -> $join[tag]: 1b9b8d9105d3ab6b923d6fbe387d9847 NOT LIKE '%Rap%' 
2019-11-19 07:12:22 [user.name] (search.class) -> SQL get_items: SELECT DISTINCT(`song`.`id`) FROM `song` LEFT JOIN (SELECT `object_id`, `name` FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id` WHERE `tag_map`.`object_type`='song' AND `tag`.`name` NOT LIKE '%Rap%' GROUP BY `object_id`) AS `realtag_1b9b8d9105d3ab6b923d6fbe387d9847` ON `song`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id` WHERE `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` NOT LIKE '%Rap%' 
```

**Comment by lachlan-00** [comment] 2019-11-19 08:20
Cheers, I'm going to try another all nighter on search and make a few more updates on this as well in a few hours

**Comment by lachlan-00** [comment] 2019-11-19 10:53
Okay these return what i think is correct.
### NOT LIKE
Showing rows 0 - 24 (253872 total, Query took 11.2200 seconds.)
```
SELECT DISTINCT(`song`.`id`)
FROM `song`
LEFT JOIN (SELECT `object_id`, `name`
           FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='song' AND `tag`.`name` NOT LIKE '%Rap%' GROUP BY `object_id`) AS `realtag_1b9b8d9105d3ab6b923d6fbe387d9847` ON `song`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id`
WHERE `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` NOT LIKE '%Rap%';
```
### LIKE
Showing rows 0 - 24 (2610 total, Query took 0.0157 seconds.)
```
SELECT DISTINCT(`song`.`id`)
FROM `song`
LEFT JOIN (SELECT `object_id`, `name`
           FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='song' AND `tag`.`name` LIKE '%Rap%' GROUP BY `object_id`) AS `realtag_1b9b8d9105d3ab6b923d6fbe387d9847` ON `song`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id`
WHERE `realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`name` LIKE '%Rap%';
```

### NOT LIKE
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0009 seconds.)
```
SELECT DISTINCT(`song`.`id`)
FROM `song`
LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id`
LEFT JOIN (SELECT `object_id`, `name`
           FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='artist' AND `tag`.`name` NOT LIKE '%%'  GROUP BY `object_id`) AS realtag_b5289217a3252d7522e4eb266dd6eaff ON `artist`.`id`=`realtag_b5289217a3252d7522e4eb266dd6eaff`.`object_id`
WHERE `realtag_b5289217a3252d7522e4eb266dd6eaff`.`name` NOT LIKE '%%';
```
### LIKE
Showing rows 0 - 24 (261164 total, Query took 0.0013 seconds.)
```
SELECT DISTINCT(`song`.`id`)
FROM `song`
LEFT JOIN `artist` ON `song`.`artist`=`artist`.`id`
LEFT JOIN (SELECT `object_id`, `name`
           FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='artist' AND `tag`.`name` LIKE '%%'  GROUP BY `object_id`) AS realtag_b5289217a3252d7522e4eb266dd6eaff ON `artist`.`id`=`realtag_b5289217a3252d7522e4eb266dd6eaff`.`object_id`
WHERE `realtag_b5289217a3252d7522e4eb266dd6eaff`.`name` LIKE '%%';
```

This issue must be something to do with your tag / tag_map tables instead of the actual search. I'll try and work our where that's managed. i'm guessing with a catalog verify.

**Comment by mariof1** [comment] 2019-11-19 11:57
No, I don't think this is correct. If I run your first query for example, it will still return songs with 'Rap'
Look at the title of the song here - it matches the title of the first song in ampache search which has 'Rap, Hip Hop' in tag

![image](https://user-images.githubusercontent.com/32400371/69144229-bd0e8500-0ac2-11ea-9627-3e697ef4294c.png)

![image](https://user-images.githubusercontent.com/32400371/69144316-ecbd8d00-0ac2-11ea-8baa-9fb2cff7d525.png)

**Comment by lachlan-00** [comment] 2019-11-19 12:02
```
SELECT *
FROM `song`
LEFT JOIN (SELECT `object_id`, `name`
           FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='song' AND `tag`.`name` LIKE '%Rap%' GROUP BY `object_id`) AS `realtag_1b9b8d9105d3ab6b923d6fbe387d9847` ON `song`.`id`=`realtag_1b9b8d9105d3ab6b923d6fbe387d9847`.`object_id`
WHERE `song`.`title` = 'Mac 10'
```

**Comment by mariof1** [comment] 2019-11-19 12:09
**LIKE**
![image](https://user-images.githubusercontent.com/32400371/69145307-48891580-0ac5-11ea-872f-030e4c72a148.png)


**NOT LIKE**
![image](https://user-images.githubusercontent.com/32400371/69145340-5c347c00-0ac5-11ea-8e99-e74209357ee7.png)

**Comment by lachlan-00** [comment] 2019-11-19 12:13
So it's still matching on hip hop.

Is this oracle mysql? maybe it's the grouping in that server as i use mariadb

**Comment by lachlan-00** [comment] 2019-11-19 12:14
let me work on the query a bit more.

**Comment by mariof1** [comment] 2019-11-19 12:18
I use MariaDB.
Even If I exclude both tags it still return that song

![image](https://user-images.githubusercontent.com/32400371/69145914-9a7e6b00-0ac6-11ea-8683-d629ec7d00e4.png)

**Comment by lachlan-00** [comment] 2019-11-19 13:36
yup definitely a query problem. i've got to go to bed now but at least i know what the issue is correctly now.

**Comment by lachlan-00** [comment] 2019-11-19 13:45
I think i can get these with a group_concat which will at least join all the rows together
```
SELECT DISTINCT(`artist`.`id`), realtag.name
FROM `artist`
LEFT JOIN (SELECT `object_id`, GROUP_CONCAT(`name`) AS `name`
           FROM `tag` LEFT JOIN `tag_map` ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='artist'
           GROUP BY `object_id`) AS `realtag` ON `artist`.`id`=`realtag`.`object_id`
LEFT JOIN `song` ON `song`.`artist`=`artist`.`id`
LEFT JOIN `catalog` AS `catalog_se` ON `catalog_se`.`id`=`song`.`catalog`
WHERE `realtag`.`name` NOT LIKE '%Rap%' AND
 `catalog_se`.`enabled` = '1'
```

**Comment by mariof1** [comment] 2019-11-19 13:53
Yeah I think group_concat should do. Thanks for confirming this and hopefully you will be able to solve the issue soon.

**Comment by lachlan-00** [comment] 2019-11-19 14:49
okay it's much later than i wanted to stay up but test out develop!

**Comment by lachlan-00** [comment] 2019-11-19 15:06
I think I have a better way to do the search using the tag id instead of name but it may be slower. I'll test tomorrow

**Comment by mariof1** [comment] 2019-11-19 21:33
Sorry could not test it earlier. Now I can only choose from "is" and "is not" and it is still not filtering as it should.

**Comment by lachlan-00** [comment] 2019-11-19 21:49
Back to group concat then!

**Comment by mariof1** [comment] 2019-11-19 22:02
I think it looks good now.

**Comment by lachlan-00** [comment] 2019-11-19 22:41
I think to stick with this way will need a little tweaking but I think it won't be that hacky.

I'd like to keep it in with the text search if possible without having to split it up but we'll see

**Comment by lachlan-00** [comment] 2019-11-19 23:24
I have a more elegant way of doing it for IS IS NOT using find_in_set. I'll add this tonight again. (just for my memory tonight)

No Rap
```
SELECT * from song
LEFT JOIN (SELECT `object_id`, GROUP_CONCAT(`name`) AS `name`
           FROM `tag` LEFT JOIN `tag_map`
           ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='song'
           GROUP BY `object_id`
           ) AS `realtag`
           ON `song`.`id`=`realtag`.`object_id`
WHERE find_in_set('Rap', cast(`realtag`.name as char)) = 0 AND song.title = 'Mac 10'
```

Has Rap
```
SELECT * from song
LEFT JOIN (SELECT `object_id`, GROUP_CONCAT(`name`) AS `name`
           FROM `tag` LEFT JOIN `tag_map`
           ON `tag`.`id`=`tag_map`.`tag_id`
           WHERE `tag_map`.`object_type`='song'
           GROUP BY `object_id`
           ) AS `realtag`
           ON `song`.`id`=`realtag`.`object_id`
WHERE find_in_set('Rap', cast(`realtag`.name as char)) > 0 AND song.title = 'Mac 10'
```

**Comment by lachlan-00** [comment] 2019-11-20 01:30
i couldn't wait and put it in develop

**Comment by mariof1** [comment] 2019-11-20 07:16
Yeah I like it now. Everything works as it should - thank you

**Comment by lachlan-00** [comment] 2019-11-20 07:49
Love it! You've made Ampache even better!

I also found some other issues as well so really helpful.

**Closed by lachlan-00** 2019-11-20 07:49 UTC
Labels: support
