### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by oppai** [ampache/ampache#740] opened 2015-02-18 06:04 UTC
Fail to install with XAMPP(5.6.3, PHP version is 5.6.3.)
All config are default values.

I fail at following url:
http://localhost/ampache/install.php?action=create_config

Error:
```
Fatal error: Call to a member function quote() on null in /Users/hiroaki.murayama/personal/ampache/lib/class/dba.class.php on line 131
```

Please help :sob:

**Comment by systems-rebooter** [comment] 2015-02-18 21:22
+1 

```
2015/02/18 23:21:02 [error] 5214#0: *24 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function quote() on a non-object in /var/www/vhosts/amd_20150218/lib/class/dba.class.php on line 131"
```

**Comment by oppai** [comment] 2015-02-19 02:48
I solved this problem to use 3.7.0

**Comment by Afterster** [comment] 2015-02-21 07:07
Just tested with XAMPP and I cannot reproduce your issue. Could you tell me more about the configuration choice you did on Ampache installation? Could you try to isolate the problem?
Thank you a lot.

**Comment by oppai** [comment] 2015-02-23 14:23
@Afterster 
Thank you for testing.

My failed brunch is develop. And also failed with PHP 5.5.3.
Put a ampache directory on document root.
Change config parmission to 777:
![](http://i.gyazo.com/7b0edfd1aaa91f20436f334e6baef580.png)

Access to http://localhost/ampache/. Select "English(US)" as Installation Language.
Requirements are all green.

Step 1 config:
![](http://i.gyazo.com/aff37e44f876fc2e890d8995fc3e98f6.png)
Step 2 config:
![](http://i.gyazo.com/feb04129ebc67e97a4f551f9abaec058.png)
Step 2 (File Insight) config:
![](http://i.gyazo.com/e389b966f2bf4cbbf39b38c8dc4e499a.png)

Creating config is failed with following error:
```
Fatal error: Call to a member function quote() on a non-object in /Applications/XAMPP/xamppfiles/htdocs/ampache/lib/class/dba.class.php on line 131
```

Thanks :bow:

**Comment by Afterster** [comment] 2015-02-23 20:18
A short mistake was fixed in sql creation script, maybe it was the issue. But I still cannot reproduce it. You can give a try with latest commits, otherwise I have no clue and will wait for input from other users...

**Comment by systems-rebooter** [comment] 2015-02-24 13:42
I'll give it a check with latest commit and reply soon

**Comment by SUTJael** [comment] 2015-02-24 15:04
Would be nice if you could also try to add some debug_event to see what is returned by the function "dbh()" into the dba.class.php to see what append.

**Comment by oppai** [comment] 2015-02-24 16:27
I failed install using cd8334b.

@SUTJael 
Thank you for your advice, but I cant use debug_event without config/ampache.cfg.php.
There is printing debug with echo.

```php
# lib/class/dba.class.php
235     /**¬
236      * _connect¬
237      *¬
238      * This connects to the database, used by the DBH function¬
239      */¬
240     private static function _connect()¬
241     {¬
242         static $db_count = 0;¬
243         $username = AmpConfig::get('database_username');¬
244         $hostname = AmpConfig::get('database_hostname');¬
245         $password = AmpConfig::get('database_password');¬
246         $port = AmpConfig::get('database_port');¬
247 ¬
248         // Build the data source name¬
249         if (strpos($hostname, '/') === 0) {¬
250             $dsn = 'mysql:unix_socket=' . $hostname;¬
251         } else {¬
252             $dsn = 'mysql:host=' . $hostname ?: 'localhost';¬
253         }¬
254         if ($port) {¬
255             $dsn .= ';port=' . intval($port);¬
256         }¬
257 ¬
258         try {¬
259             debug_event('Dba', 'Database connection...', 6);¬
260             $db_count++;¬
261             $dbh = new PDO($dsn, $username, $password);¬
262         } catch (PDOException $e) {¬
263             self::$_error = $e->getMessage();¬
264             echo "connection called $db_count times.<br/>";¬
265             echo $e->getMessage()."<br/>";¬
266             debug_event('Dba', 'Connection failed: ' . $e->getMessage(), 1);¬
267             return null;¬
268         }¬
269 ¬
270         return $dbh;¬
```

Display Error:
```
connection called 154 times.
SQLSTATE[HY000] [1040] Too many connections
connection called 155 times.
SQLSTATE[HY000] [1040] Too many connections
```

**Comment by SUTJael** [comment] 2015-02-24 16:32
Yes you did the right thing ;)
Could you try to increase the number of connections in mysql and retry? (max_connections to 500 for example)

**Comment by oppai** [comment] 2015-02-24 16:53
@SUTJael 
Thanks, I change $dbh instance as singleton. But config/ampache.cfg.php is not created.
Should I create a config/ampache.cfg.php myself ?

**Comment by oppai** [comment] 2015-02-24 16:58
change max_connections to 500, but display following same error:
![](http://i.gyazo.com/097b1a00b9852055209e30fc10603573.png)

**Comment by SUTJael** [comment] 2015-02-24 17:27
Strange it looks like the .dist file is not up-to-date. Try to create the file manually to see what's happening, if it works, we can revert to try to figure out why it's not working.

**Comment by oppai** [comment] 2015-02-25 16:23
@Afterster  @SUTJael 
Perhaps, my .dist files was too old. I became unable to reproduce the config parse error.
Reset all files, success to install !!!

Thank you :sushi::sushi::sushi:

**Comment by SUTJael** [comment] 2015-02-26 13:15
good to know thanks.

**Closed by SUTJael** 2015-02-26 13:15 UTC

**Comment by systems-rebooter** [comment] 2015-02-26 22:32
Instaled 3.8.0-beta1 without issues.
