### ISSUE TITLE
Dsub caching songs problem.

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#1731] opened 2018-06-05 10:36 UTC
# Environment

 * Ampache version: 3.8.8 develop commit e32bea7bcd541fd9cae813b264fc324d676169c1 and newer
 * Web server + version: Apache 2.4.
 * Server operating system: Debian Buster
 

 * Client type:
   - SubSonic (Dsub on Android)
   

# Description

Ever since commit e32bea7bcd541fd9cae813b264fc324d676169c1 when I cache songs with DSUB all I get are files that end in .complete rather than the artist/ablum folder and the file with the correct extension (.flac .mp3 etc). Dsub does not play these files. When I reset back to commit ea5f14808b38e109610f5488f3e769c4e94c0f11 the issue is not present. I cache songs for offline playing.

# Logs

Logs show no usable information or errors

**Comment by wagnered** [comment] 2018-06-05 23:53
@stebe 

Thanks for bringing this to my attention.  Fix has been pushed to develop branch as commit 0db132f95425232b733425081b06d6b04619dabf.

**Comment by stebe** [comment] 2018-06-07 11:52
Thanks @wagnered, the fix is working.

**Comment by stiqs** [comment] 2018-06-18 16:10
The fix doesn't actually work per se. You don't get the *.complete anymore, but now they all have the suffix *.api

**Comment by wagnered** [comment] 2018-06-18 16:51
@stiqs 

I just tried DSub again and when caching/playing the albums, "I see <song_name>.complete.flac" files in their own folders/subfolders. I've also tried with .mp3 files and they end in .mp3; none end in .api.
Is some setting possibly different from what I have. What song type's are you trying to play?.

I'm running Ampache-3.8.8 which I just released yesterday.

**Comment by stiqs** [comment] 2018-06-18 17:27
It could be an issue with the official subsonic client. My server is
updated to the latest in git.

**Comment by wagnered** [comment] 2018-06-18 19:14
Probably not.  Every client seems to gets it's metadata in a different way.  I'll dig into it.

Because I don't have an IPhone,  not sure what I'll do if the problem pops up on one of those client. :unamused:

**Comment by wagnered** [comment] 2018-06-18 21:34
I just tested Subsonic and sorry to say that all files that are cached, have  their appropriate extensions similar to DSub.

**Comment by stiqs** [comment] 2018-06-18 22:21
So I decided to install dsub to see if it's just subsonic client. This file
just got cached as .api. Again, my git pull is up-to-date.

So I'm not really sure what gives.

P.

**Comment by wagnered** [comment] 2018-06-19 15:55
>Again, my git pull is up-to-date.

Does this mean you installed from the source? Could you try with the latest release; [ampache-3.8.8_all.zip?](https://github.com/ampache/ampache/releases) It's just a matter of moving your current installation out of the way, unpacking the zip file and copying config/ampache.cfg.php from the old installation into the config folder of the new installation.

**Comment by stiqs** [comment] 2018-06-20 07:09
Yes. I am up to date with the dev branch. I'm running the latest. So I did
some sleuthing and found where the "api" was being explicitly set causing
the code to use that and ignore the settings output type. There's nothing
to handle the "api" target properly on the server. So it sends it back as
the extension type and client just uses it. There's probably some reason
why it is explicitly set to "api," but it causes it to ignore config
settings.

Here's my fix that worked for me.

diff --git a/lib/class/subsonic_xml_data.class.php
b/lib/class/subsonic_xml_data.class.php
index ffa6e46a..273efcb5 100644
--- a/lib/class/subsonic_xml_data.class.php
+++ b/lib/class/subsonic_xml_data.class.php
@@ -572,7 +572,7 @@ class Subsonic_XML_Data
         $transcode_cfg = AmpConfig::get('transcode');
         $valid_types   =
Song::get_stream_types_for_type($songData['type'], 'api');
         if ($transcode_cfg == 'always' || ($transcode_cfg != 'never' &&
!in_array('native', $valid_types))) {
-            $transcode_settings =
Song::get_transcode_settings_for_media($null, 'api', null, 'song');
+            $transcode_settings =
Song::get_transcode_settings_for_media($null, null, null, 'song');
             if ($transcode_settings) {
                 $transcode_type = $transcode_settings['format'];
                 $xsong->addAttribute('transcodedSuffix', $transcode_type);

Where it breaks:
lib/class/song.class.php

    public static function get_transcode_settings_for_media($source,
$target = null, $player = null, $media_type = 'song', $options=array())
    {
        $setting_target = 'encode_target';
        if ($media_type != 'song') {
            $setting_target = 'encode_' . $media_type . '_target';
        }

        if ($player) {
            $player_setting_target = 'encode_player_' . $player . '_target';
            if ($media_type != 'song') {
                $player_setting_target = 'encode_' . $media_type .
'_player_' . $player . '_target';
            }
            if (AmpConfig::get($player_setting_target)) {
                $setting_target = $player_setting_target;
            }
        }

        if ($target) { // ******* BREAKS HERE ******
            debug_event('media', 'Explicit format request {' . $target .
'}', 5);
        } else {
            if ($target = AmpConfig::get('encode_target_' . $source)) {
                debug_event('media', 'Defaulting to configured target
format for ' . $source, 5);
            } else {
                if ($target = AmpConfig::get($setting_target)) {
                    debug_event('media', 'Using default target format', 5);
                } else {
                    $target = $source;
                    debug_event('media', 'No default target for ' . $source
. ', choosing to resample', 5);
                }
            }
        }

**Comment by wagnered** [comment] 2018-06-20 19:44
@stiqs 

In order to attempt to replicate your issue, I need:

1. The transcode section of your ampache.cfg.php,
2. The music type, song name, and extension of the song(s) that are giving issue.
3. A PR of your changes  would be very helpful.

Thanks...

**Comment by stiqs** [comment] 2018-06-20 22:44
1. My transcode Config

root@stiqi-six:/var/www/tunes# !grep
grep encode  config/ampache.cfg.php
; for each song. It requires transcode and encode_args_wav settings.
; It requires encode_get_image transcode settings.
encode_target = "opus"
encode_video_target = "webm"
; to stream lossless encoded files in lossy formats.
; encode_target_TYPE = TYPE
encode_target_flac = opus
;encode_target_m4a = mp3
; encode_player_PLAYER_target = TYPE
;encode_player_webplayer_target = ogg
encode_player_webplayer_target = ogg
encode_player_api_target = opus
; encode_args_TYPE = TRANSCODE_CMD_ARGS
encode_args_mp3 = "-vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1"
encode_args_ogg = "-vn -b:a %BITRATE%K -c:a libvorbis -f ogg pipe:1"
encode_args_opus = "-vn -b:a %BITRATE%K -c:a libopus -compression_level 10
-vsync 2 -f ogg pipe:1"
encode_args_m4a = "-vn -b:a %BITRATE%K -c:a libfdk_aac -f adts pipe:1"
encode_args_wav = "-vn -b:a %BITRATE%K -c:a pcm_s16le -f wav pipe:1"
encode_args_flv = "-b:a %BITRATE%K -ar 44100 -ac 2 -v 0 -f flv -c:v libx264
-preset superfast -threads 0 pipe:1"
encode_args_webm = "-q %QUALITY% -f webm -c:v libvpx -maxrate %MAXBITRATE%k
-preset superfast -threads 0 pipe:1"
encode_args_ts = "-q %QUALITY% -s %RESOLUTION% -f mpegts -c:v libx264 -c:a
libmp3lame -maxrate %MAXBITRATE%k -preset superfast -threads 0 pipe:1"
encode_get_image = "-ss %TIME% -f image2 -vframes 1 pipe:1"
encode_srt = "-vf \"subtitles='%SRTFILE%'\""
encode_ss_frame = "-ss %TIME%"
encode_ss_duration = "-t %DURATION%"

2. Song

The type setting happens during the listing for the specific album. Putting
this here because you asked, but is irrelevant for the issue. Me thinks.
It's not one song type, it's practically all of them

2018-06-20 15:32:22 [stiqs] (media) -> Defaulting to configured target
format for flac
2018-06-20 15:32:22 [stiqs] (media) -> Transcode settings: from flac to
opus
2018-06-20 15:32:22 [stiqs] (media) -> Command: ffmpeg Arguments: -i %FILE%
-vn -b:a %BITRATE%K -c:a libopus -compression_level 10 -vsync 2 -f ogg
pipe:1
2018-06-20 15:32:22 [stiqs] (media) -> Changing play url type from {flac}
to {opus} due to encoding settings...
2018-06-20 15:32:22 [stiqs] (session) -> Session created:
8569f9b797a18da1c011eb7725847ca1
2018-06-20 15:32:22 [ampache] (play) -> Asked for type {song}
2018-06-20 15:32:22 [stiqs] (play) -> Playing file
(/home/stiqs/Music/Charles Mingus - In A Soulful Mood/01 - Charles Mingus -
Bugs.flac}...
2018-06-20 15:32:22 [stiqs] (play) -> Media type {flac}
2018-06-20 15:32:22 [stiqs] (play) -> Custom play action {}
2018-06-20 15:32:22 [stiqs] (play) -> Transcode to {}
2018-06-20 15:32:22 [stiqs] (play) -> Transcoding because native streaming
is unavailable
2018-06-20 15:32:22 [stiqs] (stream.class.php) -> Starting transcode for
{/home/stiqs/Music/Charles Mingus - In A Soulful Mood/01 - Charles Mingus -
Bugs.flac}. Type {}. Options: Array
2018-06-20 15:32:22 [stiqs] (stream.class.php) -> (
2018-06-20 15:32:22 [stiqs] (stream.class.php) -> )
2018-06-20 15:32:22 [stiqs] (stream.class.php) -> }...
2018-06-20 15:32:22 [stiqs] (media) -> Defaulting to configured target
format for flac
2018-06-20 15:32:22 [stiqs] (media) -> Transcode settings: from flac to
opus
2018-06-20 15:32:22 [stiqs] (media) -> Command: ffmpeg Arguments: -i %FILE%
-vn -b:a %BITRATE%K -c:a libopus -compression_level 10 -vsync 2 -f ogg
pipe:1
2018-06-20 15:32:22 [stiqs] (stream) -> Configured bitrate is 128
2018-06-20 15:32:22 [stiqs] (stream) -> Final transcode bitrate is 128
2018-06-20 15:32:22 [stiqs] (stream) -> %SAMPLE% not in transcode command
2018-06-20 15:32:22 [stiqs] (stream) -> %MAXBITRATE% not in transcode
command
2018-06-20 15:32:22 [stiqs] (stream) -> %RESOLUTION% not in transcode
command
2018-06-20 15:32:22 [stiqs] (stream) -> %QUALITY% not in transcode command
2018-06-20 15:32:22 [stiqs] (stream) -> Transcode command: ffmpeg -i
'/home/stiqs/Music/Charles Mingus - In A Soulful Mood/01 - Charles Mingus -
Bugs.flac' -vn -b:a 128K -c:a libopus -compression_level 10 -vsync 2 -f ogg
pipe:1
2018-06-20 15:32:22 [stiqs] (stream) -> Transcode command prefix: exec
2018-06-20 15:32:22 [stiqs] (play) -> Starting stream of
/home/stiqs/Music/Charles Mingus - In A Soulful Mood/01 - Charles Mingus -
Bugs.flac with size 55868738
2018-06-20 15:32:22 [stiqs] (play) -> Registering stream stats for {Charles
Mingus - Bugs}...
2018-06-20 15:32:22 [stiqs] (user.class.php) -> Updating stats for
{song/182} {DSub}.

2.1 Listing debug (Without the fix)

2018-06-20 15:20:23 [stiqs] (Recommendation) -> search url :
http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&api_key=d5df942424c71b754e54ce1832505ae2&artist=C%C3%A9line%20Dion&lang=en
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error] Illegal offset type
in isset or empty in file
/var/www/tunes/lib/vendor/rmccue/requests/library/Requests/IRI.php(722)
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error] Illegal offset type
in file
/var/www/tunes/lib/vendor/rmccue/requests/library/Requests/IRI.php(742)
2018-06-20 15:20:23 [stiqs] (session) -> Session created:
737ac2480de0f83c093482fd5619cc3a
2018-06-20 15:20:23 [stiqs] (Recommendation) -> search url :
http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&api_key=d5df942424c71b754e54ce1832505ae2&artist=C%C3%A9line%20Dion&lang=en
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): Entity: line 1: parser error : Start tag expected,
'&lt;' not found in file
/var/www/tunes/lib/class/recommendation.class.php(56)
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): 19A0 in file
/var/www/tunes/lib/class/recommendation.class.php(56)
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error]
simplexml_load_string(): ^ in file
/var/www/tunes/lib/class/recommendation.class.php(56)
2018-06-20 15:20:25 [stiqs] (session) -> p7t6dici3b3kdij48cpbujhgfv has
been extended to Wed, 20 Jun 2018 16:20:25 -0700 extension length 3600
2018-06-20 15:20:25 [stiqs] (ajax.server.php) -> Called for page: {index}

**** NOTE **** Debug for the values for $valid types and $transcode_cfg

2018-06-20 15:20:28 [stiqs] (Song) -> Valid types: "transcode" and
"default"

***** NOTE ****

2018-06-20 15:20:28 [stiqs] (media) -> Explicit format request {api}
2018-06-20 15:20:28 [stiqs] (media) -> Transcode settings: from  to api
2018-06-20 15:20:28 [stiqs] (media) -> Command: ffmpeg Arguments: -i
%FILE%
2018-06-20 15:20:28 [stiqs] (Song) -> Valid types: transcode and default
2018-06-20 15:20:28 [stiqs] (media) -> Explicit format request {api}
2018-06-20 15:20:28 [stiqs] (media) -> Transcode settings: from  to api
2018-06-20 15:20:28 [stiqs] (media) -> Command: ffmpeg Arguments: -i
%FILE%

3. PR
No valid PR. Though the diff I sent earlier shows where I changed it to fix
my problem, I still don't understand how the logic is supposed to work with
the "api" still there. With my configuration, there's no combination of
settings that would make it work without the fix. I can't in good faith
consider it a fix just because it works. So hopefully my config will help
repro and we can understand what is going on.

Pritchard

**Comment by wagnered** [comment] 2018-06-21 00:15
Could you disable `show_similar` in the config file and and any switch that might cause Ampache to do a search on lastfm?

I see an extra error in your debug file, which my log doesn't contain when looking for similar artists.
The first two are also in my debug log and don't seem to affect anything on the client side.

>2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error] Illegal offset type in isset or empty in file /var/www/tunes/lib/vendor/rmccue/requests/library/Requests/IRI.php(722)
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error] Illegal offset type in file /var/www/tunes/lib/vendor/rmccue/requests/library/Requests/IRI.php(742)

>2018-06-20 15:20:23 [stiqs] (Recommendation) -> search url : http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&api_key=d5df942424c71b754e54ce1832505ae2&artist=C%C3%A9line%20Dion&lang=en
2018-06-20 15:20:23 [ampache] (PHP) -> [Runtime Error] simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in file /var/www/tunes/lib/class/recommendation.class.php(56)...

I don't get the third error.  It looks like lastfm is returning improperly formatted XML from your debug file. I don't know how this would affect the Android clients. but better to disable `show_similar` and all then go from there.

**Comment by stiqs** [comment] 2018-06-21 00:28
Those errors have nothing to do with how the decision to land in the API
block is being made. Those are independent function calls along the chain.

The decision is being made by comparing two config settings I highlighted.

I tried to use the official release with my ampache config and listing in a
subsonic client started failing. I'll try to get the two to work together
and see where I get to.  The release was tagged off the master at the head,
right? And it is in sync with Dev branch?

**Comment by wagnered** [comment] 2018-06-21 02:51
> The release was tagged off the master at the head, right?

Yes.

> And it is in sync with Dev branch?

Yes, until the next commit/PR.

Well, until I can replicate the issue and step through it with the Eclipse-PDT, or you can give me a definitive explaination,  I'll have to sit back and let you "do your thing" :smile:

**Comment by FX7** [comment] 2018-07-14 16:32
Hello.
I got the same problem and setting like @stiqs 
I have lates release (3.8.8) installed. Using DSub for playing on android.
I think I jumped one version (updated from 3.8.6 to 3.8.8). The problems definitly began after the update.
All my songs are mp3s and all downloaded via DSub with file extension ".api", so no offline playing is possible.

So if I could help in any way, please let me know!

**Comment by wagnered** [comment] 2018-07-14 18:05
Hello @FX7 

I , again, tested 3.88-release with DSub on my phone and all still works well.  The cached files end in .flac and can be replayed.

Could you try http://demo.subsonic.org and report the caching results from that site? I can't remember where I got the username/password but I use guest2/guest.

**Comment by FX7** [comment] 2018-07-14 19:51
Just tested demo.subsonic.org and cached files are stored as ".mp3", so all right with that.

The are no differences in the transcoding section between my config and the .dist config. But anyway, here are the differences, between my config and the .dist config:

```
http_host = "my.domain"
session_cookiesecure = 1
deferred_ext_metadata = "false"
allow_zip_download = "true"
allow_zip_types = "album"
sociable = "false"
wanted = "false"
channel = "false"
live_stream = "false"
show_footer_statistics = "false"
```

I also turned on debugging. So here is the log for asking explicit for caching of one element:

```
(media) -> Explicit format request {api} 
(media) -> Transcode settings: from  to api 
(media) -> Command:  Arguments: -i %FILE%  
(media) -> No default target for mp3, choosing to resample 
(media) -> Transcode settings: from mp3 to mp3 
(media) -> Command:  Arguments: -i %FILE% -vn -b:a %BITRATE%K -c:a libmp3lame -f mp3 pipe:1 
(media) -> Changing play url type from {mp3} to {mp3} due to encoding settings... 
(session) -> Session created: 69542ae1e7bfa9b2200d21e3eac99a0c 
(subsonic) -> Stream proxy: https://my.domain:443/play/ssid/69542ae1e7bfa9b2200d21e3eac99a0c/type/song/oid/16120/uid/2/client/DSub/noscrobble/1/player/api/name/David%20Guetta%20And%20Sia%20-%20Flames.mp3 
(play) -> Asked for type {song} 
(session) -> 69542ae1e7bfa9b2200d21e3eac99a0c has been extended to Sat, 14 Jul 2018 23:39:12 +0200 extension length 7200 
(play) -> Playing file (/path/to/file/david guetta & sia - flames.mp3}... 
(play) -> Media type {mp3} 
(play) -> Custom play action {} 
(play) -> Transcode to {} 
(play) -> Transcoding is not enabled for this media type. Valid types: {["native"]} 
(play) -> Starting stream of /path/to/file/david guetta & sia - flames.mp3 with size 6599857 
(play) -> Registering stream stats for {David Guetta And Sia - Flames}... 
(user.class.php) -> Updating stats for {song/16120} {DSub}... 
(user.class.php) -> Scrobbling explicitly skipped 
(play) -> Stream ended at 6599857 (6599857) bytes out of 6599857 

```

I also could create an account on my server for you, if this would help.

**Comment by wagnered** [comment] 2018-07-14 21:06
> I also could create an account on my server for you, if this would help.

Please do that. Unless your music is "Creative Commons" licensing, I suggest sending the password to the address listed on my profile. That will enable me to look at the network conversation to see what is being sent and received between your server and the DSub client.

> media) -> Explicit format request {api}
(media) -> Transcode settings: from  to api

These log entries seem suspicious.  I'll take a look at the transcode settings and see if I can duplicate your issue.

**Comment by wagnered** [comment] 2018-07-14 22:08
Could you first set transcoding to "never" in admin/server config/streaming?  It is not needed for DSub. only for the web player if the songs are other than mp3, ogg, or wav depending on the browser.

I noticed that my log shows:
> Transcode to {}

Do you have the switch: `;encode_player_api_target = mp3` uncommented?  If so, try  commenting it out. Checking the code, it looks like that might be the cause.  I don't know what that switch is actually for, because of lack of documentation,  but DSub works perfectly well with it commented out.

I noticed the same log entries in @stiqs comment above.

**Comment by wagnered** [comment] 2018-07-14 23:45
Never mind about the status of the above switch.  I managed to replicate your issue, but am not sure how I caused it. :frowning_face:

**Comment by wagnered** [comment] 2018-07-15 04:50
If you are familiar with patch files [this patch file](https://gist.github.com/wagnered/a380266867c62247ab34d08d983fb5fb#file-subsonic_xml-patch) will apply the fix to lib/class/subsonic_xml_data.class.php.   The zip file can be downloaded and unpacked from that page.

The command will be `patch -p0 lib/class/subsonic_xml_data.class.php <subsonic.patch>` from the doc root folder.

**Comment by FX7** [comment] 2018-07-15 06:29
Thanks a lot! Setting transcoding to never solved the issue.
I will later try the patch file.

Many thanks so far!

**Comment by FX7** [comment] 2018-07-15 11:45
Ok, I applyed the patch and now it also works with transcoding set to "always"!

**Comment by wagnered** [comment] 2018-07-15 17:49
Good, I think this issue can be closed now.

**Closed by wagnered** 2018-07-15 17:49 UTC
