### ISSUE TITLE
Smartplaylist filtering of other playlist doesn't work

### ISSUE THREAD

**Issue by kailledargun** [ampache/ampache#1652] opened 2017-12-28 18:07 UTC
My music library comprises both mine and my wife's music. In iTunes I have a smart playlist that encompasses all the songs except for what is in a special playlist that i call "hideThese". I am trying to reproduce this in ampache. I have a playlist called "hidetest" and i build a smart playlist with the filter set to:
Playlist => is not => hidetest
This shows no songs. I can change the "is not" to "is" and it will show me what is currently there but "is not" does not show me the entire library minus the songs in "hidetest". I have also saved the list and gone back to view it to make sure it wasn't a weird timing issue. Thanks for your assistance.

**Comment by wagnered** [comment] 2017-12-30 02:27
@kailledargun 

Could you give a little more information?What version of Ampache: Is it a release or the develop branch which is at 3.8.5-develop?

I just created a playlist called "Yours" and "All Else".
I did a Search->Songs and entered:
Playlist -> Is Not -> yours and got all songs minus those from "Your" playlist.

**Comment by wagnered** [comment] 2017-12-30 02:45
Also, If a user is logged in without adminr privileges, and the playlists are private, they will not be seen when doing a search.

**Comment by brilthor** [comment] 2018-08-15 00:35
I am seeing this issue in build 3.8.8.  I create a playlist called "ignorenow" and add a couple songs.  I then create a smart playlist with "playlist" "is not" on "ignorenow".  This causes there to be no songs at all in the playlist.  The same result is seen when doing a global search using the playlist as a negative match.  

- A positive match work (eg playlist "is").  
- I have tested this with playlists in both private and public states from an administrative account.

**Comment by wagnered** [comment] 2018-08-15 03:36
If the match type is switched to "Any Rule", it seems to work:

I have two playlists: Test and Test1.

I set rule 1 to "is not" Test1 and rule 2 to title "contains" "I Robot". I get the songs from "Test" and "I Robot" So I think it is working as intended.

**Comment by brilthor** [comment] 2018-08-15 04:34
I've managed to work around the behavior by creating a smart playlist that's sole function is to mirror my "ignore" playlist, then I was able to use the "smart playlist" match instead of the "playlist" match which behaves as expected.

This feels like a step that shouldn't really be needed however I'm not sure what the right answer for behaviour / user experience is.

**Comment by lachlan-00** [comment] 2019-10-16 05:14
I think this is resolved as i can't reproduce it. Are you not able to do this currently?

**Comment by lachlan-00** [comment] 2020-06-10 08:19
closing as this has been fixed for multiple smart lists.

reopen if you can still reproduce; but the lists are run separately instead of making a giant query that would break.

**Closed by lachlan-00** 2020-06-10 08:19 UTC
Labels: waiting
