### ISSUE TITLE
While screen via custom domain

### ISSUE THREAD

**Issue by zhihuilin** [ampache/ampache#3352] opened 2022-09-14 18:53 UTC
https://musicbox.leolin.us

**Comment by zhihuilin** [comment] 2022-09-14 18:54
*blank screen

**Comment by zhihuilin** [comment] 2022-09-14 18:55
It worked before I've upgraded to v5.5.1

**Comment by linucksrox** [comment] 2022-09-14 23:32
possible duplicate of #3348

**Comment by zhihuilin** [comment] 2022-09-14 23:44
Thank you so much for the quick response!👍

**Comment by lachlan-00** [comment] 2022-09-16 05:12
5.5.2 is out now. docker builds should be done in 5ish minutes
![image](https://user-images.githubusercontent.com/1305249/190561386-b8ca9060-f4e1-40ac-b99e-28b891e4b26f.png)

**Comment by zhihuilin** [comment] 2022-09-16 05:42
Hi lachlan-00,
I just ran the service with latest tag and web stopped working with log down below:
ampache    | => Using an existing volume of MySQL
ampache    | 2022-09-16 05:40:52,511 INFO Set uid to user 0 succeeded
ampache    | 2022-09-16 05:40:52,514 INFO supervisord started with pid 1
ampache    | 2022-09-16 05:40:53,518 INFO spawned: 'apache2' with pid 8
ampache    | 2022-09-16 05:40:53,523 INFO spawned: 'cron' with pid 9
ampache    | 2022-09-16 05:40:53,527 INFO spawned: 'inotifywait' with pid 10
ampache    | 2022-09-16 05:40:53,529 INFO spawned: 'mysql' with pid 11
ampache    | 2022-09-16 05:40:54,623 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache    | 2022-09-16 05:40:54,624 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache    | 2022-09-16 05:40:54,624 INFO success: inotifywait entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
ampache    | 2022-09-16 05:40:54,624 INFO success: mysql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by lachlan-00** [comment] 2022-09-16 05:47
![image](https://user-images.githubusercontent.com/1305249/190565560-867fe68a-4d6e-481a-9fee-71d3909307dd.png)
code error, rebuilding

**Comment by zhihuilin** [comment] 2022-09-16 05:47
Thank you!

**Comment by lachlan-00** [comment] 2022-09-16 05:50
my 8.1 local repo had some kind of messed up repo, rebuilding on that release

**Comment by zhihuilin** [comment] 2022-09-16 05:53
No problem take your time for this, the dev branch with tag "preview" works for me, I'm using it temporary.
Once again, thank you so much for your help and you guys are doing great job to make this world better!

**Comment by lachlan-00** [comment] 2022-09-16 05:56
that was the only zip with the error, i'll work on making sure my build script removes those issues before they get built.

new latest/nosql tags will be done soon.

**Comment by lachlan-00** [comment] 2022-09-16 06:38
fixed images for latest/nosql up now @zhihuilin

**Comment by zhihuilin** [comment] 2022-09-16 16:14
Works perfectly! Thank you so much!!!!

**Closed** 2022-09-19 00:00 UTC
