### ISSUE TITLE
Path pattern/Ampache issue with multiple artists

### ISSUE THREAD

**Issue by kuzi-moto** [ampache/ampache#1911] opened 2019-06-03 14:59 UTC
# Environment

 * Ampache version: 3.9.1-develop

# Description

I've had this issue for some time, but since there are other issues relating to the pattern matching wanted to add this as well.

The issue happens when you have a release that is attributed to two artists (ex. [Excision & Datsik - Swagga](https://musicbrainz.org/release-group/607f12b1-7904-45fd-a015-32d07afdbd6d) alongside releases by just one of those artists (ex. anything from [Excision](https://musicbrainz.org/artist/733c6e6f-0306-403e-9243-82b16a4f82d8)). If you have the album "Swagga" and you also have "X Rated" from Excision, they will both have the artist name, "Excision & Datsik". This is driving me nuts!
![Capture3](https://user-images.githubusercontent.com/17068090/58811679-e0fa0f00-85e5-11e9-8c88-d58c9564c707.PNG)

To do some testing, I created a new install, and only added albums by Excision, so far so good:
![Capture1](https://user-images.githubusercontent.com/17068090/58811777-0d159000-85e6-11e9-98ca-79c121fca6f7.PNG)

But then adding the "Swagga" album, it's incorrectly labeled as just "Excision":
![Capture2](https://user-images.githubusercontent.com/17068090/58811817-1bfc4280-85e6-11e9-95e1-7e84d4957ce0.PNG)

It seems that Ampache might have some work when it comes to multiple artists for a single release. I'm not sure what the best solution is, but I'm guessing that the only way to fix it in my install is to do it directly in the database.

**Comment by mitchray** [comment] 2021-04-30 01:19
Duplicate of #2711 

(consolidating multi-artist issues)

**Closed by mitchray** 2021-04-30 01:19 UTC
Labels: bug, database
