### ISSUE TITLE
Genre with & cause XML error in ajax.php

### ISSUE THREAD

**Issue by landure** [ampache/ampache#1842] opened 2019-01-13 18:56 UTC
# Environment

 * Ampache 3.9.0:
 * Apache 2.4.25 + PHP FPM 7.0
 * Debian 9.0 Stretch
 * Ubuntu 18.10

 * Client type:
   - Web

# Description
The bug is due to the client having strict XML validation. In genre list, when clicking a genre with & in its name (example: "Rock & Roll"), the XML generated by Ampache is invalid: the & is not escaped in the genre name (it should be "&amp;" in the XML, it is "&" ).

The faultive line in ajax.php XML is : 

`<td class="cel_tags"><a href="https://music.domain.com/browse.php?action=tag&show_tag=29&type=artist" title="Rock & Roll">Rock & Roll</a></td>`

**Comment by lachlan-00** [comment] 2019-03-23 23:15
So are the strings not being escaped into xml safe values?
* < as &lt;
* & as &amp;

I think i can update xml_data.class.php to replace the strings with this format.
probably as a function to replace the charaters in the string.

Can you tell me what client you're using so i can test?

**Comment by lachlan-00** [comment] 2019-03-29 05:21
I don't really understand what the error you're talking about is here.

All the api calls are returning safe for me and the website isn't using xml for navigation. This looks like HTML from the website? Browsing all my tags has no issue with these genres.

**Comment by mitchray** [comment] 2021-04-30 06:53
Also unable to reproduce so I'm closing. Reopen if its still a problem on the latest version

**Closed by mitchray** 2021-04-30 06:53 UTC
Labels: isolated
