### ISSUE TITLE
SMTP problem

### ISSUE THREAD

**Issue by Rouzax** [ampache/ampache#855] opened 2015-05-12 08:57 UTC
Hi,
With the latest dev GIT version I'm unble to send mails.
My settings are like this:
```
;#############################
;   Mail Settings            #
;#############################

;Method used to send mail
;POSSIBLE VALUES: smtp sendmail php
;DEFAULT: php
mail_type = "smtp"

;Mail domain.
;DEFAULT: example.com
mail_domain = "xxx.xxx"

;This will be combined with mail_domain and used as the source address for
;emails generated by Ampache.  For example, setting this to 'me' will set the
;sender to 'me@example.com'.
;DEFAULT: info
mail_user = "music"

;A name to go with the email address.
;DEFAULT: Ampache
mail_name = "xxx.xxx"

;How strictly email addresses should be checked.
;easy does a regex match, strict actually performs some SMTP transactions
;to see if we can send to this address.
;POSSIBLE VALUES: strict easy none
; DEFAULT: strict
;mail_check = "strict"


;############################
;   sendmail Settings       #
;############################

;DEFAULT: /usr/sbin/sendmail
;sendmail_path = "/usr/sbin/sendmail"

;#############################
;   SMTP Settings            #
;#############################

;Mail server (hostname or IP address)
;DEFAULT: localhost
mail_host = "mail.xxx.xxx"

; SMTP port
;DEFAULT: 25
mail_port = "26"

;Secure SMTP
;POSSIBLE VALUES: ssl tls
;DEFAULT: none
;mail_secure_smtp = tls

;Enable SMTP authentication
;DEFAULT: false
mail_auth = "true"

;SMTP Username
;your mail auth username.
mail_auth_user = "xxx@xxx.xxx"

; SMTP Password
; your mail auth password.
mail_auth_pass = "xxxxx"
```

I get the following error in the debug log:
```
2015-05-12 10:53:43 [ampache] (PHP) -> [Error] ini_set(): Use of mbstring.internal_encoding is deprecated in file C:\inetpub\wwwroot\Ampache\admin\mail.php(42) 
```

**Comment by Rouzax** [comment] 2015-05-12 09:09
During the creation of a test account I get the following errors in the log:
```
2015-05-12 11:08:24 [ampache] (PHP) -> [Runtime Error] Missing argument 1 for debug_event(), called in C:\inetpub\wwwroot\Ampache\lib\class\user.class.php on line 1050 and defined in file C:\inetpub\wwwroot\Ampache\lib\log.lib.php(140) 
2015-05-12 11:08:24 [ampache] (PHP) -> [Runtime Error] Missing argument 2 for debug_event(), called in C:\inetpub\wwwroot\Ampache\lib\class\user.class.php on line 1050 and defined in file C:\inetpub\wwwroot\Ampache\lib\log.lib.php(140) 
2015-05-12 11:08:24 [ampache] (PHP) -> [Runtime Error] Missing argument 3 for debug_event(), called in C:\inetpub\wwwroot\Ampache\lib\class\user.class.php on line 1050 and defined in file C:\inetpub\wwwroot\Ampache\lib\log.lib.php(140) 
2015-05-12 11:08:24 [ampache] () ->  
```

**Comment by Afterster** [comment] 2015-05-15 21:55
Indeed, the warning is probably because you moved to PHP5.6 recently, and I fixed the debug_event error.
Otherwise sending email should work, don't you get the user account validation email then?

**Comment by Rouzax** [comment] 2015-05-16 06:45
Yes I upgraded to 5.6 that is correct :smile: 

No I don't get the mail, In my setup the admin needs to approve the user but then the Admin should get an email.
Although this should be implemented
https://github.com/ampache/ampache/issues/485
https://github.com/ampache/ampache/issues/393

When the admin aproves the user there is an actual mail send, so the mail setup works.

**Comment by Afterster** [comment] 2015-05-16 09:15
So `user_no_email_confirm` isn't enabled, `admin_enable_required` enabled and `admin_notify_reg`enabled too, right?

**Comment by Rouzax** [comment] 2015-05-16 09:37
```
; This disable email confirmation when registering.
; DEFAULT: false
user_no_email_confirm = "false"

; This setting turns on/off admin notification of registration.
; DEFAULT: false
admin_notify_reg = "true"

; This setting determines whether the user will be created as a disabled user.
; If this is on, an administrator will need to manually enable the account
; before it's usable.
; DEFAULT: false
admin_enable_required = "true"
```

**Comment by Afterster** [comment] 2015-06-09 19:55
After several tests this is always working on my side.
Are you sure you setup an email to your Ampache admin account?

**Comment by Rouzax** [comment] 2015-06-10 10:06
Is there an easy way to test email sending?

**Comment by Rouzax** [comment] 2015-06-10 10:18
The send mail to users gives an error.
![image](https://cloud.githubusercontent.com/assets/4103090/8080172/6b60d972-0f6a-11e5-99b5-c125bb83d758.png)

![image](https://cloud.githubusercontent.com/assets/4103090/8080174/72b6365e-0f6a-11e5-9f4b-f328fa400d82.png)

In the debug log on level 6 I see:
```
2015-06-10 12:16:55 [ampache] (PHP) -> [Warning] Undefined index: action in file C:\inetpub\wwwroot\Ampache\admin\mail.php(33) 
2015-06-10 12:16:55 [ampache] (PHP) -> [Warning] Undefined index: subject in file C:\inetpub\wwwroot\Ampache\templates\show_mail_users.inc.php(50) 
```

**Comment by Afterster** [comment] 2015-06-11 04:49
Sending email to admins/users give me `Your E-mail was successfully sent.`.
You should try with a different admin email just in case.

**Comment by Rouzax** [comment] 2015-06-11 09:48
Hmmm,
When I use a different mail address it works. It looks like there is an issue with the gmail address, although I can't figure out what.

I have different sites that use the same email relay as the ampache site without any issue.

If I use the email trace on my cpanel it looks like the mails don't get to the sntp server because there is nothing in the log about the gmail address.

Is there anyway I can troubleshoot more? Debug level 6 does not show anything of significance.

**Comment by Afterster** [comment] 2015-06-11 11:19
Ok. Not sure about that... maybe moving to the latest PHPMailer version (https://github.com/PHPMailer/PHPMailer/releases) would fix the issue? Some tests will be required.

**Comment by vader083** [comment] 2015-12-22 17:39
I tried updating PHPMailer and some other libraries composer suggested but still get this same error.  Trying to use Gmail as well.

**Comment by Phyks** [comment] 2016-06-17 23:47
Is it still reproducible on latest `develop` branch? If it is still the case, could you repost your updated settings (latest settings used concerning emails) and any relevant steps to reproduce? Thanks

**Comment by vader083** [comment] 2016-06-18 10:47
I just switched to one of the other mailers , it works fine with that.

**Comment by Phyks** [comment] 2016-06-20 07:20
Ok. Anyone, feel free to reopen if still experiencing this problem :)

**Closed** 2016-06-20 07:20 UTC
Labels: bug, isolated, waiting

**Comment by trueno-pepe** [comment] 2019-09-02 21:01
Hi. Has someone have a solution for this issue (or #1113)?  Y have the same problem (setting email for Gmail) and have not yet found any one. Thanks.

**Comment by kuzi-moto** [comment] 2019-09-02 22:19
I have also had issues mailing, just haven't brothered to make an issue yet. Have you tried switching to a different mailer as vader083 mentioned?

**Comment by lachlan-00** [comment] 2019-09-03 02:44
Make a new issue and we'll have a look.

I have my own mail domain but I'll check Gmail when I get back

**Comment by trueno-pepe** [comment] 2019-09-03 20:35
Thanks for the answers. I have post another issue (#2032 ) with the description of my settings.
