### ISSUE TITLE
no options available in options menu

### ISSUE THREAD

**Issue by joshp23** [ampache/ampache#1351] opened 2016-07-30 04:30 UTC
# Environment

 * Ampache version: Ampache 3.8.3-develop 
 * Web server + version: Apache/2.4.18 (Ubuntu)
 * Server operating system: Ubuntu 16.06 - fully updated
 * Client operating system: ubuntu 16.06
 * Client type:
   - Web
# Settings

[ampache.cfg.php.txt](https://github.com/ampache/ampache/files/391707/ampache.cfg.php.txt)

# Description

Using the web interface, I just click on the options tab, user or admin server options, and there is nothing there, a big empty box. This is independent of browser, and seems ot be independent of OS so far.

In the Chrome dev console, I get this:

GET https://media.example.com/preferences.php?action=admin&tab=options 500 (Internal Server Error)
# Logs

server access 
[access.log.txt](https://github.com/ampache/ampache/files/391714/access.log.txt)

server error 
[error.log.txt](https://github.com/ampache/ampache/files/391715/error.log.txt)

**Comment by wagnered** [comment] 2016-07-30 05:29
The error and access logs indicate that Ampache is trying to access
"media.example.com".  I'm pretty sure it doesn't exist.

Also, did you execute "composer install" in "/var/www/ampache/"?
Composer installs required components for Ampache and the error log
indicates a missing file.

See https://github.com/ampache/ampache/wiki/Installation for details....

Also, you might disable https(ssl) access until ampache is working
correctly. That is to say: Wwork on one problem at a time.

73 From  AA1AD
Ernie D
Federal Way, WA | CN87ug

**Comment by joshp23** [comment] 2016-07-30 05:42
i replaced my actual url with example.com in the file for privacy, sorry. should have mentioned that.

this AA1Ad issue is new. The options missing pre-dates it, but I take your point. 

I'll try the composer command. 

Since I posted this, I decided to right-click -> open on the 500 server error links appearing in the dev console in chrome, the options menu appears, but there is no save button, so there's that.What appears to be failing on page load is https://media.example.com/lib/components/jquery/jquery.min.js:6

**Comment by joshp23** [comment] 2016-07-30 06:03
composer install didn't do anything.

**Comment by wagnered** [comment] 2016-07-30 07:08
I suggest you take the installation down to it's basic form: No
ssl(https:), redirection, mail server, etc.  I see in the server log
that php was trying to access an undefined variable in an index file in
your home folder chain. (outside of document root). When you get it
running in it's most simple form, then add features, one at a time.  If
the problem exists in the basic installation, then the developers will
have a better chance of duplication the problem.

You might enable php error recording and see what php is trying to do.
There are also php errors that can cause the stated problem.

Your server is trying to access
ampache/lib/components/jQuery-contextMenu/dist/jquery.contextMenu.min.css.map
which doesn't exist in my installation. I am running Ampache
3.8.2-develop. I tried updating with composer, but still don't see that
file that Apache is looking for.  This just might be a bug in Ampache.

ps:  AA1AD is my ham call sign..  I entered the information in the
signature in the wrong order. 

73 From Ernie D
Ham Call: AA1AD
Federal Way, WA | CN87ug

**Comment by Phyks** [comment] 2016-07-30 10:34
First of all, you have many SSL errors in you error log. Actually, these are the only ones present in this error log. Try to fix them first.

Then, I would not worry much about `jquery.contextMenu.min.css.map` not being available. It does not matter and is only required because you have the Chrome dev console opened.

Then, ensure you have PHP error reporting **on** (either as a `display_error` or logging errors to the Apache log).

Finally, this really looks like previous issues related to this, which were due to faulty `composer install` or outdated installations (a few bugs regarding the translation module and XBMC have been solved recently).

Please, check this and come back to me :)

**Comment by joshp23** [comment] 2016-08-05 00:43
Hey, 

So I made sure to do a "composer update" in my ampache folder, there was some activity, and I fixed all of the ssl info messages, and I switched off all of the aliases that had php looking in my home directory, my apache error log reporting is set to info, and is now virtually empty. The machine that this is on is already pretty basic and minimal beyond these points.

I made sure that error reporting was turned on for php at the default levels, and nothing happened. No errors were written to any file.

So I decided to turn on "display errors" and attempt to access the options page. It showed up at that point. But there was no "Update Preferences" or "Save Options" button, just a big empty space.

I'm running this with PHP7 in the latest ubuntu with the latest git pull from Ampache dev.

**Comment by Phyks** [comment] 2016-08-05 12:18
So you don't have any error either in the Apache/PHP logs or in the Ampache logs (setting debug level in Ampache config file)?

Could you take a screenshot of your options page as you see it?

Also, what is your screen resolution? There is a known UI bug which makes options disappear below 970px wide.

**Comment by joshp23** [comment] 2016-08-05 15:27
Here is my ampache log  with debug on set to level 5
[ampache.20160805.log.txt](https://github.com/ampache/ampache/files/404057/ampache.20160805.log.txt)


Here us a screenshot

![screenshot from 2016-08-05 10-55-50](https://cloud.githubusercontent.com/assets/7341917/17440582/3bb196fc-5afb-11e6-9f28-e9feb4e0b509.png)

resolution is 1366 x 768

**Comment by Phyks** [comment] 2016-08-05 20:16
Ok, I have never seen it nor can I reproduce :/ Logs does not contain anything useful.

I see you are using AJAX page loading. Can you try removing `index.php#` from the URL and see if it works? Can you also check in the network (or console) tab of the developper tools (usually opened by `Ctrl+Shift+I`) if you can find anything suspicious?

Last thing to check, can you try with another browser? (or no addons?).

**Comment by joshp23** [comment] 2016-08-05 22:20
Ok, so I haven't tried it on another browser, etc... but I did turn of ajax and I have the preference pages now, but there is no option to save the preferences...

**Comment by Phyks** [comment] 2016-08-05 22:26
Ok, so you do have an issue with AJAX loading of pages. Not sure where it can be coming from, but checking the developer tools (network tab) should give us a hint.

It makes me think of https://github.com/ampache/ampache/issues/1238, but I'm not sure it is actually correlated.

The lack of option to save preferences definitely makes me think in an issue I have already seen, concerning either a gettext bug (but should be fixed) or an issue with xbmc plugin. In both cases, it resulted in a PHP error which should show up in the logs.

**Comment by joshp23** [comment] 2016-08-05 23:40
I'll go look through logs to make sure, nothing seems to show up in dev mode.

another user is having this issue [here](https://groups.google.com/forum/#!topic/ampache/EA03Sst0O90)

perhaps it's an error unique to Ubuntu or Ubuntu 16.04 packaging?

**Comment by Phyks** [comment] 2016-08-06 12:33
Your log error message is completely harmless and I opened a separate issue to fix this https://github.com/ampache/ampache/issues/1361. Basically, it tries to find such a find, but cannot find it, so continue searching elsewhere.

I am not on the Ampache mailing list, I missed this other issue. When reading it, I see:
> I tried setting the directory index to "index.php," but that didn't seem to solve my issue. The weirdest thing regarding this issue: it's only the "Options" section under "Preferences" that doesn't display anything and under "Modules," it won't display "Local Play Modules." Everything else seems to load fine.

Which is exactly the same thing that happened in https://github.com/ampache/ampache/issues/1281 https://github.com/ampache/ampache/issues/1232 or https://github.com/ampache/ampache/issues/1211. But all of them should be solved.

I still cannot reproduce it on a similar setup :/

**Comment by joshp23** [comment] 2016-08-06 17:15
Huzzah! I deleted the modules/xbmc folder as per [this](https://github.com/ampache/ampache/issues/1211#issuecomment-224549165) instruction in modules/ and the update preferences button re-appeared!

So I tried turning ajax back on and... it's still there :)

that xbmc issue is pesky and weird. THANKS!

**Closed** 2016-08-06 17:15 UTC
Labels: support

**Comment by Phyks** [comment] 2016-08-06 17:23
Ok, good to know!

This is really weird, `composer update` should have solved the issue.

If you can try one last thing, it would be very helpful to find why it happened. Could you:
1. Put back the `modules/xbmc` folder and remove the `@` in front of `include_once` [here](https://github.com/ampache/ampache/blob/develop/modules/localplay/xbmc/xbmc.controller.php#L52). Go back to preferences page and see if you can get a PHP error in the logs (you should have one, matching the one from https://github.com/ampache/ampache/issues/1232#issuecomment-222743895, hopefully). This is to check if it is the same issue or not and eventually fix it.
2. Could you check `lib/vendor/krixon/xbmc-php-rpc/rpc/Client.php` line number 255 to see if you have a `continue` or a `return array()` instruction. This is to check [this fix](https://github.com/krixon/xbmc-php-rpc/commit/908078900c3761c54e62d96fc07ba65a3ffc21e1) has correctly been applied.

Thanks!

**Comment by joshp23** [comment] 2016-08-06 19:28
1. So, I just deleted the folder, so it's gone into a data black hole... :( sorry about that.
2. line 255:             continue;

**Comment by Phyks** [comment] 2016-08-06 21:47
Ok, so definitely your error is coming from this. I think you have a faulty `composer update` or do not track the correct branch, this error should no longer be there… =(

**Comment by joshp23** [comment] 2016-08-07 16:04
Ok. I'm using the composer that comes packaged with Ubuntu 16.04.1. I think it's version 1:0:0-beta2. Perhaps I should manually install the latest, off the cuff I think it's 1.0.2.

I bet that's the problem. I had suspected that Ubuntu packaging was to blame.
